### ISSUE TITLE
Component: Define a reusable Gutenberg Block: Highlight box (informs DS)

### ISSUE THREAD

**Issue by chachasikes** [cagov/design-system#1]
We are really excited to share this idea for a component for the ca.gov design system.

# About this component
*Please tell us more about the component.*

Page authors often need to bring users attention to a temporary message. 

## Basic information
To make sure the component serves all Californians, we have identified some things we need to know about this component.
- Please fill in what you can. 

Our design system team will review this component proposal.

### Checklist
- [X] Name
- [ ] Description
- [X] Examples (ca.gov)
- [ ] Examples (design systems)
- [X] Features
- [ ] Requesting agency

### Name of component
*What should we call this component in conversation?*

### Description
*Describe how this component will be used.*

### Examples from ca.gov properties
*(Can be screenshots, a few examples is great. Please include URLs if the examples are live.)*

- Data discrepancy notification on a dashboard:<img width="1251" alt="Screen Shot 2021-04-30 at 3 58 04 PM" src="https://user-images.githubusercontent.com/353360/116762957-f4c86e80-a9d0-11eb-9405-d977d005699f.png">
- Limited time call to action on vaccines page:<img width="980" alt="Screen Shot 2021-04-30 at 4 27 59 PM" src="https://user-images.githubusercontent.com/353360/116762998-0f024c80-a9d1-11eb-9009-bb8ee2c7881e.png">

### Examples from other design systems
*If this component is commonly found in other design systems, please link to it*

### Features
*Critical features to support initially.*

- HTML and CSS for a highlight box
- Message & icon
- Optional image
- Use little to no javascript
- Should work on multiple background colors
- Should work in any container without media queries
- Support translations
- Support RTL
- May include links, links might be PDFs with external tags
- Tab navigation should work for links

### Requesting agency
*Who is requesting this component?*

---

## Reviews

Once a component is initially created, we will use this issue to fill in the additional information. This issue will eventually become part of the documentation.

### Checklist
- [X] Name
- [ ] Short name
- [ ] Version number
- [X] Destination
- [ ] Description
- [X] Features
- [ ] Status

## Metadata
*Our design system uses package control systems, and these systems need names and some basic metadata about the component.*

### Name of component
*What should we call this component in the design system?*

### Short name
*What should the computer call this component? (alpha-numeric characters, dash separated, e.g. "highlight-box")* 

### Version number
*Start at v1.0.0, if this is a proposal for a new version, please say so.*

### Destination
* Where should this component live in the design system?* 

* `design-system/src/components/highlight-box/template.html`
* `design-system/src/components/highlight-box/index.css`

### Description
*How should we describe this in the design system (e.g. in Wordpress, documentation, package.json)*

### Features
*Critical features to support initially.*

### Status
*We plan to manage this mostly with Github labels & Airtable*
- [ ] Has Github labels
- [ ] Final content in Airtable (to autogenerate documentation & keep track of assets)

---

### Checklist
- [ ] User research
- [ ] Design
- [X] Content design
- [ ] Content strategy
- [X] Format
- [ ] Destination
- [X] Data structure
- [ ] Accessibility
- [ ] Analytics
- [ ] Equity
- [ ] Performance
- [ ] Testing plan
- [ ] Support plan
- [ ] Documentation

### User research
*Has user research been conducted?*

### Design
*Anything needed to know about designing this component*

- Location of Figma assets

### Content design 
*What content elements or assets does a content editor need to provide?*

- icon
- message (maximum length)

### Content strategy
*What does a content editor need to know about writing and publishing this content?*

### Data structure
*If this component maps to an existing schema.org microdata format, please include. If it doesnt, that's ok. We will look it up or provide a data structure. We use schema.org for SEO and data management and round-trip data migration to help help the component easy to upgrade.*

- https://schema.org/SpecialAnnouncement

### Format
* Include or reference the expected HTML markup and CSS output (if known)*

- HTML markup sample
   - Desired selectors: (?)
- CSS -  Will be added to the global css file

### Accessibility
*In our design system, we are creating fully-accessible components, for delivery and for the editor experience. We have a [baseline]() of general accessibility practices we are following. Are there any additional accessibility considerings with this component?* 

### Analytics
*How can we measure if this component is succeeding in its intention, or discover new insights about needs that we did not know?*

### Equity
*Are there potential impacts of this component or how it is used that may need special consideration?*

### Performance
*We provide a [baseline]() of tests for basic performance. Will this component present additional performance issues, and if so, how can we address them?*

### Testing plan
*We provide a [baseline]() of tests for basic component features. Are there additional tests that need to happen for this component?*

## Publishing
Once development is completed and the component is in use throughout ca.gov websites, any changes will need well communicated updates that will roll up into bigger updates. Additionally, documentation and support will be required.

### Documentation
*This document will inform the documentation we create for the finished component.*

- [ ] Screenshots
- [ ] Sample code
- [ ] How to use
- [ ] Video walkthrough (with captions) (editorial experience)

### Support plan
*We provide a [baseline]() of support. What kinds of additional support are needed for this component?*

**Comment by chachasikes** [comment]
We can use the Gutenberg Blocks props + a page rendering script that pulls out the props to generate JSON-LD formatted schema.org data

Here is a special example from Google's Special Announcement schema (from their COVID-19 response support.)
https://developers.google.com/search/docs/data-types/special-announcements#json-ld_1

And the spec from schema.org:
https://schema.org/SpecialAnnouncement

As we are figuring out which selectors to include, we may want to consider these additional properties or how the alert can extend.

Note: the microdata approach to schema.org is cumbersome & the JSON-LD approach is becoming the standard, but we need to pull the data from the stored block content when rendering a page to be able to inject the JSON-LD into the page.

`
{
      "@context": "https://schema.org",
      "@type": "SpecialAnnouncement",
      "name": "Shelter-in-place for 3 California counties",
      "text": "<a href=https://example.org/california/executive-order-123>Executive order 123</a> requires residents to shelter-in-place through April 30. Additional disease prevention and quarantine guidelines are also available.",
      "datePosted": "2020-04-01T08:00",
      "expires": "2020-05-03T23:59",
      "quarantineGuidelines": "https://example.org/california/shelter-in-place",
      "diseasePreventionInfo": "https://example.org/california/prevention-tips",
      "category": "https://www.wikidata.org/wiki/Q81068910",
      "spatialCoverage": [
        {
          "type": "AdministrativeArea",
          "name": "Santa Clara County, CA"
        },
        {
          "type": "AdministrativeArea",
          "name": "Marin County, CA"
        },
        {
          "type": "AdministrativeArea",
          "name": "Santa Clara County, CA"
        }
      ]
    }
`

**Comment by chachasikes** [comment]
Special announcement will work

**Comment by kkoryaka** [comment]
Added branch kk-highlight-component with initial attempt to develop highlight box with image and without image. There are two components added into /components/ folder (just html template and pure css):
- highlight-img (is using an image but image is optional, but layout is left justified, no media queries are used)
- highlight (layout is centered)

**Comment by chachasikes** [comment]
@TODO should proposal hang out in our git repo forever? Can we archive them?
