### ISSUE TITLE
Last updated notation for content pages

### ISSUE THREAD

**Issue by jaredwyee** [cagov/design-system#126]
As gov sites are often content heavy, it's important for users to know when a given page has been updated.

Similar to the last updated notation on Covid, the design system should have a "**last updated: date time**" notion. This would first roll out to Cannabis and Drought.

* The datetime message should ideally be included every time a page is saved in Wordpress, if the publisher has enabled the "last updated" function. 
* Consider different treatments. On Covid the update message is in the top banner. In other circumstances, I think it could be more subtle where there is less frequency than rapid changes to public health information. eg in the top portion of a body of content or at the bottom of a content page.

**Comment by jaredwyee** [comment]
@adam-little created this per our standup chat with Angie

**Comment by adam-little** [comment]
@jaredwyee Here are three options (https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/Design-system-components?node-id=89%3A2867)

1. In breadcrumb
2. Underneath page title
3. Bottom of page

Some questions to consider:

- Will this appear on every page? or only when an admin enables it?
- Is there a risk that seeing an old date will give people the impression that the content/website is outdated and therefore not to be trusted?
