### ISSUE TITLE
Content style guide: when should something be an action button

### ISSUE THREAD

**Issue by LizNobriga** [cagov/design-system#150]
(bringing over from jira)

Check if we describe how to determine when to use an action button in our handbook. Requested by Angie.

**Comment by m-sullivan7** [comment]
@LizNobriga Think the [link I shared earlier](https://teamdocs.covid19.ca.gov/components/text-links-buttons.html#action-button-(action-link)) satisfies this issue and we can consider it closed?

**Comment by LizNobriga** [comment]
Yes.
