### ISSUE TITLE
Design system information architecture

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/design-system#154]
Create an information architecture infrastructure that contains the following:

- A homepage to serve as a storefront for the Design System
- Principles for each discipline
- Style guides
- Components
- A standard component template

cc @wrendo

**Comment by aaronhans** [comment]
The site architecture in Adam's latest figma is looking great, ok to close this ticket now @wrendo?

**Comment by wrendo** [comment]
Looks good! will close.
