### ISSUE TITLE
grid utility class

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#197]
We need utility classes to create the 2 column and 3 column flexible grid layouts used in figma design card layouts.

We have some similar code in components/card-grid but there is a problem with that CSS syntax when SASS tries to run.

Suggested utility classnames:
- card-grid-3
- card-grid-2

These utility classes should be part of base-css

In order to avoid confusion also want to rename the component/card-grid to button-block

**Comment by aaronhans** [comment]
Remaining task: rename card-grid to button-grid. Jim, Ehb and Aaron decided on button-grid as the new name for the card-grid component while we were writing the component documentation.

**Comment by kkoryaka** [comment]
This one is done. Jon has renamed card-grid to button-grid on Nov 2
