### ISSUE TITLE
component: page alert

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#209]
### Origin Story
*What prompted this proposal?*
The page alert component was missed when we moved everything out of cannabis into design-system. There is a js and css file for this in cannabis and probably drought. We need to remove that and replace it with a design system component. 

### Name
*What should we call this component in conversation?*
ds-page-alert

# About this component
*Please tell us more about the component.*
Page alert provides brief, important or time-sensitive information. Yellow background color is used to grab users attention and create sense of importance and urgency.

### Description
*Describe how this component will be used.*
Page/departmental alert box usually appears beneath the site navigation on the homepage.  It can include a hyperlink, but not a button or image.

### Examples from ca.gov properties
*(Can be screenshots, a few examples is great. Please include URLs if the examples are live.) This helps everyone understand what you are referring to.*
CA>GOV alert:
![Screen Shot 2021-11-15 at 2 41 58 PM](https://user-images.githubusercontent.com/31669748/141864294-8e7f8a4e-9f9c-4341-b416-4f3ad93388e0.png)

Cannabis.ca.gov. page alert:
![Screen Shot 2021-11-15 at 2 41 25 PM](https://user-images.githubusercontent.com/31669748/141864310-80b2da29-fc53-4ada-a063-d35239441dc0.png)

### Examples from other design systems
*If this component is commonly found in other design systems, please link to it. This helps everyone understand real-world examples of this idea.*

 U.S. Web Design System (USWDS) Alert:
![Screen Shot 2021-11-15 at 2 43 42 PM](https://user-images.githubusercontent.com/31669748/141864664-620b778c-f353-48b2-adf4-c853a243086c.png)

### Features
*Critical features to support initially.*
- SVG icon
- Dismiss/close button

---

**Comment by kkoryaka** [comment]
This one is already added to design system.
