### ISSUE TITLE
Component: breadcrumbs (informs DS)

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#21]
# Breadcrumbs component

Breadcrumbs are used on internal pages to display how the current page fits into the navigation structure

### Examples
Here is a breadcrumbs frontend component from another design system that pays attention to accessibility and clean markup: https://democracyclub.github.io/design-system/components/breadcrumbs/

### Design

<img width="668" alt="breadcrumbs" src="https://user-images.githubusercontent.com/353360/121031630-6083c100-c75f-11eb-8d2a-9bd9a9f6d306.png">

## Development

This ticket will result in a PR to the design-system repository containing a web component that attempts to lookup its own url via the designated site nav API and populate the breadcrumbs

A separate ticket will be opened to track the integration of this into WordPress Gutenberg patterns and custom blocks

**Comment by chachasikes** [comment]
For cannabis site Phase 1 - added PHP code. 
As communicated to Aaron this morning: the plan is to update our CA Design System WP plugin to use the web component version instead (which will use on the WP Menu API) - we will swap the web component markup into our breadcrumb building function in the plugin.
