### ISSUE TITLE
page feedback: create network diagram

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#210]
A network diagram describing the page feedback system was requested.

**Comment by aaronhans** [comment]
Here are some beginning exports to start the page feedback network diagram conversation. There are png exports from cloudcraft. They are both the same but I included both the 2D and 3D versions

Probably left out some important stuff here right @jefferymarino @rsanjabi?

![page feedback (1)](https://user-images.githubusercontent.com/353360/139952819-eccc2dbf-4cc9-43eb-b967-7e75e971ce02.png)

![page feedback](https://user-images.githubusercontent.com/353360/139952845-8a0ec9ff-30fd-4705-90e3-5b17c4b7430f.png)

cc @mediajunkie

**Comment by rsanjabi** [comment]
This looks great! The only part that is missing would be a node for Syntasa. It would sit between API Gateway and BigQuery.  It's both storing the code (python and SQL pipelines) and executing said code on a schedule, in this case daily. But it looks like you don't necessarily need that level of detail here.

Also the current BI tool is Data Studio but it could be any of them (Looker, Power BI, SQL queries, etc.)

**Comment by aaronhans** [comment]
Updates to add Syntasa API ste
![page feedback (3)](https://user-images.githubusercontent.com/353360/140233391-7121386c-6557-4b46-8111-a0a7c060f1cd.png)
![page feedback (2)](https://user-images.githubusercontent.com/353360/140233395-d08f7068-7178-4862-a3bb-1a0778431ff7.png)
p

**Comment by aaronhans** [comment]
Good discussion with team on this architecture.

Action item: Should submit data to central storage controlled by insights team instead of copying data to multiple dbs. It will be better not to store this in multiple place. Need to make sure we use method of storage that scales as smoothly as our Azure FAAS + CosmosDB

**Comment by rsanjabi** [comment]
Curious as to why multiple locations is bad here? Having separate operational and analytical databases seems typical. The system requirements for gathering data are different than what analytics databases are optimized for. It also gets into ownership of pipelines - where engineering can ensure that the data is captured and data folks can then take it from there, vs. engineering needing to understand how our warehouse is structured or Insights needing to be in the loop on how the data is collected.

**Comment by aaronhans** [comment]
Thanks for bringing this up @rsanjabi 

The motivation for centralizing data sources was the possibility of people entering personally identifying information into the feedback form and making that easier to clean up.

One advantage of keeping the separate databases is that we are confident in the stability, ease of management and scalability of our FAAS + CosmosDB frontline data collection setup.
