### ISSUE TITLE
Design System information architecture v2

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/design-system#218]
Iterate on the Design System information architecture to:

- [x] Break out principles into digital.ca.gov v2.0 iteration
- [x] Create a set of Design System principles from the [existing discipline principles](https://docs.google.com/document/d/1IAMGLJbsLqXMxlHGgeTt2Qr9rInpn6iJYeh-bUsYTwI/edit)
- [x] Update component list based on [audit matrix](https://docs.google.com/spreadsheets/d/1bRHQod0tWuULEHIdKaGB2F4M6Lk1py8eGfvu8GyKqng/edit#gid=0)
- [x] Create [homepage narrative](https://docs.google.com/document/d/1CAUUP4nrWHfgB_IqcZcF62iQzzdAua1C-G_Mrpic3OM/edit)

Information architecture for both sites will be in [FigJam](https://www.figma.com/file/c5suoREmws7kkpKHzyd1tW/Design-System-IA?node-id=0%3A1).

cc: @wrendo @adam-little

**Comment by m-sullivan7** [comment]
@wrendo I looked at the principles across the disciplines. I chose top-line principles in the cases of research and engineering for the sake of simplicity.

I created a [space in the FigJam](https://www.figma.com/file/c5suoREmws7kkpKHzyd1tW/Design-System-IA?node-id=0%3A1) below the two information architectures to group like principles. I see six big principles here. We can discuss in conjunction with creating the homepage narrative, but I thought I'd share the preliminary work now.

cc: @adam-little

**Comment by adam-little** [comment]
**Re: principles**

I layered in the original Alpha principles because i was curious to see the evolution.

The "outliers" that I think are relevant to the design system:
- Be consistent but not uniform
- Optimize performance
- Make things open

**Comment by m-sullivan7** [comment]
Thanks @adam-little ! I appreciate the feedback and adding in of alpha principles.

**Comment by m-sullivan7** [comment]
@wrendo I think the work from the ticket description is done. OK to close and spin up a new issue from the next pieces of work?

**Comment by wrendo** [comment]
Ok to close!
