### ISSUE TITLE
Combine link treatment icon components into one  ds-link-icon component

### ISSUE THREAD

**Issue by kkoryaka** [cagov/design-system#225]
We already have two link icons components  such as pdf-icon and external-link-icon. Combining those two into one will fix JS import order issue that came up on the drought website as well as will give opportunity to safely add more link icons treatments.

### Requesting agency
*Who is requesting this component?*
ODI 

### Origin Story
*What prompted this proposal?*
On drought website there was issue when both "pdf-icon" and "external-link-icon" was present in the same link because components' JS imports were not in correct order. To avoid need for additional JS import order instructions we can combine these link treatment icons components into one component. 

### Name
*What should we call this component in conversation?*
ds-link-icon

# About this component
*Please tell us more about the component.*
ds-link-icon component adds an icon next to a link. 
- PDF icon: The pdf icon is the letters PDF surrounded by a box outline. It indicates that the link opens a PDF. PDF link should not appear in combination with any other link icon.
- External link: this component can also add an external-link icon next to a link that goes outside current website. It lets people know they will leave the site when that link is opened. However, if link is already link to pdf file the external link icon (or any other icon) will not be displayed.  

### Description
*Describe how this component will be used.*
#### PDF link icon
This can be important for mobile users, who may not want to use up their data plan allowance opening PDFs. 

It’s also important for those who use screen readers, as it will announce “This is a PDF file” before they click the link. 

If a link is both external and a PDF, only the PDF icon will appear. It’s more important to tell people they’re going to a PDF than it is to tell them that it’s not hosted on the same site.

#### External link icon
This component adds an icon next to a link that goes outside your website. It lets people know they will leave the site when that link is opened. 

### Examples from ca.gov properties
*(Can be screenshots, a few examples is great. Please include URLs if the examples are live.) This helps everyone understand what you are referring to.*
![Screen Shot 2021-11-30 at 12 56 47 PM](https://user-images.githubusercontent.com/31669748/144126905-75cd0a77-40e2-4f0d-94d1-c052b7e0f3cd.png)

### Features
*Critical features to support initially.*
As this component addresses some accessibility issues, we recommend you use it by default.

Once installed, the icons is applied automatically whenever you create a hyperlink that goes to a PDF or it's an external link.

---

Thank you!

[Learn more about our review process.](#tbd)

**Comment by aaronhans** [comment]
Nice job @kkoryaka! 

Moving this ticket to done and closing
