### ISSUE TITLE
Organize components into categories

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#229]
Use the categories defined in figma:

Structural, Visual, Navigation, Content

organize the components into these categories, make the nav work with them

**Comment by aaronhans** [comment]
@m-sullivan7 are the names for the components in the v1 design system site finalized now? If so I'll grab the names and double check the categories from the spreadsheet so that the list here matches https://designsystem.webstandards.ca.gov/ds-components/

**Comment by m-sullivan7** [comment]
The names are now final in the spreadsheet. You are ready to proceed with this work! Thanks for your patience as we tripled checked them. 🙂

**Comment by aaronhans** [comment]
Thanks @m-sullivan7 names in all markdown docs have been updated in the component-gallery/rocket branch based on the spreadsheet https://docs.google.com/spreadsheets/d/1bRHQod0tWuULEHIdKaGB2F4M6Lk1py8eGfvu8GyKqng/edit#gid=0
