### ISSUE TITLE
Increase size of text

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#233]
As per feedback from @artuoma, let's improve legibility and accessibility by increasing the size of text in the design system. Art's proposal was to match the approach taken on the State Web Template.

To do:

- [x] Adam to sync with Konstantin to better understand approach taken on State Web Template
- [x] Konstantin to stage the changes so that we see how it impacts current designs (e.g. DCC)
- [x] If approved, implement into design system
- [x] Update documentation in visual design style guide

**Comment by adam-little** [comment]
Assigning to @wrendo for visibility.

**Comment by kkoryaka** [comment]
In State Template beta I have applied Responsive Font Functionality (similar to Koji's "golden ratio" responsive font idea, but I am not using "golden ratio", because if I do everything pretty much explodes (increase is too big). In my approach i am using "vw" increments. Body text and headings font sizes are automatically calculated into appropriate values based on the dimensions of the browser viewport. For the body text we are using 0.3vw value to calculate font-size responsiveness relative to the viewport width (1vw is 1/100th the width of the viewport). Headings are using 0.5vw value that will make them bigger on the big screens but not too big on the smaller screens. So, please review and test. I wanted to apply this and all other jQuery less updates to the State Template production on Friday. 

https://beta.template.webstandards.ca.gov/sample/typography.html
![Screen Shot 2021-12-09 at 10 19 03 AM](https://user-images.githubusercontent.com/31669748/145453640-f0d04bd2-0c4b-4e3d-9bd1-6e60f56f67da.png)

**Comment by adam-little** [comment]
Assigning this to @kkoryaka to stage this so we can see how it impacts current design system websites

**Comment by kkoryaka** [comment]
Responsive font size is now applied to https://designsystem.webstandards.ca.gov/. Please review @adam-little

**Comment by adam-little** [comment]
@artuoma per your request to increase the size of text and be consistent with text on the state web template, please look here:  https://designsystem.webstandards.ca.gov. Konstantin has applied responsive font sizes. 

Do people feel comfortable applying this to the design system?

Please note: this design system staging site has not yet undergone design QA. As such, there are many inconsistencies in spacing and other layout issues. But hopefully this is good enough to evaluate font size.

cc @wrendo @kmbrlygl

**Comment by wrendo** [comment]
Text sizing all looks consistent and legible to me.

**Comment by kmbrlygl** [comment]
Overall, looks fine to me! 

I don't know if I should ignore the line heights for now, but I noticed some inconsistencies. There are places it looks like we follow 1.5/1.6 ratio and others where we use a relative scale (rem). Should that be consistent throughout?

**Comment by kkoryaka** [comment]
@kmbrlygl you are talking about line hight for body regular text, right? If so, could you send me screenshots where you saw inconsistencies

**Comment by kmbrlygl** [comment]
@kkoryaka I am not able to replicate so maybe it loaded an older version when I last saw it. You can ignore my comment re: line-height. 

One thing I did notice was that p tag that has **"cagov-section-highlight"** styles applied to it, the font-sizes for don't scale down on smaller screens (mobile). The font size stays 23px. The other place I saw this class applied is the titles of the cards under _What's in the Design System_ so I do think it would need to target that class if we were to update it.  It seems like it should scale down as well, what do you think? 

Here are screen shots: 
![desktop-cagov-section-highlight](https://user-images.githubusercontent.com/20393247/150195976-ef5e6afe-40d5-4d4b-b914-c629c2a4d5b4.png)
![mobile-cagov-section-highlight](https://user-images.githubusercontent.com/20393247/150195982-f19e8d15-49fb-4180-b8b0-393a4b5d5d71.png)

**Comment by kmbrlygl** [comment]
@adam-little @kkoryaka  I drafted the updated documentation on the [Visual Design Google doc](https://docs.google.com/document/d/17MtpWf1rZIl_Ge05DEQqIsd_NxBYha6krjRBhSUhdXg/edit?disco=AAAAVD1_g8I). Can you both review what I updated (the blurb before the table, mobile & desktop font sizes, and new line-heights ratios) before we update the Visual Design Style Guide page? 
Thank you.

References that Konstantin provided:
- [_typography.scss](https://github.com/cagov/design-system/blob/main/components/base-css/src/_typography.scss)
- [_variables.scss](https://github.com/cagov/design-system/blob/main/components/base-css/src/_variables.scss)

**Comment by kmbrlygl** [comment]
Thanks @adam-little for your edits to the content! Much better.

@kkoryaka let me know if it's good to go (see Adam's note in the doc) and I will update the content on the website. Let me know if you have any trouble accessing it.

**Comment by kkoryaka** [comment]
@kmbrlygl Documentation is good, except I would not add line-hight to the website yet since it's not implemented yet. It will be there next release.

**Comment by kmbrlygl** [comment]
Got it, thanks @kkoryaka I will work on updating the documentation on the website. 

I will hold off on updating line-heights until you give me the go-ahead on that ticket 👍

**Comment by jaredwyee** [comment]
@adam-little  @kmbrlygl  please confirm this is fixed as expected in https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/

**Comment by kmbrlygl** [comment]
@jaredwyee Yes, this looks good 👍
