### ISSUE TITLE
create site header and footer sections using our existing components

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#238]
Build the site header and footer including statewide header, footer, branding, site specific header, top menu using our design system components

**Comment by aaronhans** [comment]
We built this in rocket and deployed it on designsystems.webstandards.ca.gov

We need to rebuild this now because we are migrating off rocket. Assigning to @xjensen because he is redoing the site chrome in the 11ty-build system branch

**Comment by xjensen** [comment]
Ready for review.
