### ISSUE TITLE
Draft About Page content

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#239]
Christina and Ashley are drafting the content for the About page.

[Draft link](https://docs.google.com/document/d/1lUlbetYHbDzVmo0r1VPmt17FTYJCxOROObgSts9b2KE/edit#heading=h.avilpnxfol6j)

**Comment by wrendo** [comment]
With Art for review

**Comment by ashleydraper** [comment]
@artuoma Ready for final review. 
[About us](https://docs.google.com/document/d/1lUlbetYHbDzVmo0r1VPmt17FTYJCxOROObgSts9b2KE/edit?usp=sharing)

**Comment by ashleydraper** [comment]
@wrendo  This draft is now ready for your review. Have at it!

**Comment by wrendo** [comment]
@ashleydraper Took a look and gave my suggested two cents. Let me know what you think. Thanks!

**Comment by wrendo** [comment]
@ashleydraper How are we looking on this content? We're shooting for content lock next week and I'd like to start bringing all content into the site so we can start our QA process also.
