### ISSUE TITLE
Create deprecation warnings for all design system NPM packages that are no  longer used.

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#241]
https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions

For example @cagov/accordion is should only be in use on covid19. Since it has been replaced with @cagov/ds-accordion, a warning should be issued if someone attempts to install it.

**Comment by wrendo** [comment]
Who to assign to?

**Comment by zakiya** [comment]
Sorry. This one belongs in dev backlog. Anyone could pick it up when the time is right.
