### ISSUE TITLE
Test scripts on accordion component produce errors. 

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#242]
@xjensen and @aaronhans before I work on this more I want to make sure I'm honoring the intent of the refactoring that was done around testing for the design system a few weeks back. Since all three of us are chock full of meetings tomorrow I was hoping we could handle it asynchronously. 

TL;DR: The scripts in ./components/accordion/package.json have issues.

### Steps to reproduce:

**Terminal input:**
```bash
gh repo clone cagov/design-system ds-delete
cd ds-delete/components/accordion
npm install 
npm run test
```
_Terminal output:_
```bash
> @cagov/ds-accordion@1.0.8 test
> web-test-runner "test/**/*.js" --node-resolve

sh: web-test-runner: command not found
```
**Terminal input:**
```bash
npm install -save-dev @web/test-runner 
npm run test
```

_Terminal output:_
```bash
> @cagov/ds-accordion@1.0.8 test
> web-test-runner "test/**/*.js" --node-resolve


Chrome: |██████████████████████████████| 1/1 test files | 1 passed, 0 failed

Finished running tests in 1.4s, all tests passed! 🎉
```
(Yay)

**Terminal input:**
```bash
npm run test:visual
```

_Terminal output:_
```
> @cagov/ds-accordion@1.0.8 test:visual
> web-test-runner "test/**/*.js" --node-resolve --config test-config.js


Error: You are using es module syntax in a config loaded as CommonJS module. Use require/module.exports syntax, or load the file as es module by using the .mjs file extension or by setting type="module" in your package.json.
```
(Boo)

**Comment by aaronhans** [comment]
We need a line in the package.json specifying "type": "module"

I thought we did this in all the components but it looks like it is inconsistent. Adding that section like https://github.com/cagov/design-system/blob/main/components/back-to-top/package.json#L6 lets the test script run

**Comment by zakiya** [comment]
Ok cool. Wanted to make sure we still were expecting tests on the per-component basis. I'll add @web/test-runner and define the type.
