### ISSUE TITLE
Draft Get started page content

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/design-system#244]
Create content for the _Get started_ page for the Design System website.

**Comment by m-sullivan7** [comment]
@LizNobriga Ehb asked at today's sprint planning meeting if it seemed realistic to write this content by Friday, December 17 (the end of our current sprint). What do you think?

**Comment by LizNobriga** [comment]
Updating this ticket with links to draft content:
- [Overview](https://docs.google.com/document/d/1IeYxY4wXDGwX82-q1GpT1T1SC7oRgP29gALeFuJiNvo/edit#heading=h.25pxoan2vuy0)
- Developer intro (in [Notion](https://www.notion.so/Get-started-891c365572fc4554b2e528ed1db6f539#3135622db730438e983eb8e835e6ee26) and [google doc](https://docs.google.com/document/d/1OYG9FCLsjP9zSjKkqpEU4jtAergbyj2mVFJc6T5W4Ns/edit#))
