### ISSUE TITLE
Draft homepage content

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/design-system#245]
Create content for the homepage page for the Design System website.

[Google Doc for drafting content](https://docs.google.com/document/d/1eU7Y0Hacs8oPUloLaIN0koK15zur0HXa663abvvhviw/edit?usp=sharing)

**Comment by m-sullivan7** [comment]
@wrendo 

We're most of the way there for the homepage content thanks to the great work from last week. Here's what I think is still outstanding:

- Review of the text for the _Be a part of the Design System_
- In _Who's using the Design System_:
  - Do we want to feature COVID19.ca.gov?
  - We have space for text under each example. What, if anything, do we want to say about each example?
- Final sign off on content

These seem like questions for the onboarding governance team. Since that team hasn't met, I'm happy to work with another decision maker(s) to tie up these pieces by December 17.

[Google Doc version](https://docs.google.com/document/d/1eU7Y0Hacs8oPUloLaIN0koK15zur0HXa663abvvhviw/edit?usp=sharing)
[Figma](https://www.figma.com/file/A1DSo765cWjvBWoLd6tvEE/DS-website-screens?node-id=0%3A1) with Adam's mock ups

**Comment by wrendo** [comment]
Onboarding gov team had our kickoff meeting this morning and will be meeting weekly. The purpose of the gov team to be macro and look at long term strategy for 2022-2024. They shouldn't be involved with tactical decisions like these, so we can sort this out amongst ourselves.

Let's set a review time for the Be a part... section.

Ok to showcase covid19 and we can talk specifically about the success behind the ppf component
Cannabis is obviously a full site using DS components.

Hope that helps.

**Comment by m-sullivan7** [comment]
Thanks for that direction! I'm ready for a review of the page as a whole. I think it should be quick. Want me to find 15 minutes to look at it together?

**Comment by m-sullivan7** [comment]
@adam-little Ehb and I reviewed the remaining pieces of the homepage content (_Be a part of the Design System_ and _Who's using the Design System_). He asked I run it by you before it goes to the onboarding governance team.

If all looks good to you, would you like me to drop this content into your mockup?

**Comment by adam-little** [comment]
Looks good to me. Go ahead and drop it in Figma. LMK if you have any problems.

**Comment by m-sullivan7** [comment]
@wrendo Homepage content is ready for onboarding governance team final review. I'm handing the assignment to you to facilitate that.

Both of these have the latest content loaded in:

- [Google Doc](https://docs.google.com/document/d/1eU7Y0Hacs8oPUloLaIN0koK15zur0HXa663abvvhviw/edit?usp=sharing) version
- [Figma](https://www.figma.com/file/A1DSo765cWjvBWoLd6tvEE/DS-website-screens?node-id=0%3A1) with Adam's mock ups
