### ISSUE TITLE
Create visuals for Design System homepage

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#247]
Create visuals (photos, illustrations, etc.) for design system homepage.

Homepage mockup is here: https://www.figma.com/file/A1DSo765cWjvBWoLd6tvEE/DS-website-screens?node-id=0%3A1

**Comment by kmbrlygl** [comment]
[Explorations/concepts presented 1/14/2021](https://www.figma.com/proto/S4lfJfR2e4CcpwwJSJrQrk/DS-Illustration-Design-Exploration?page-id=51%3A54&node-id=51%3A55&viewport=254%2C48%2C0.11&scaling=contain)*

[**Updated homepage mockup with new design direction**](https://www.figma.com/proto/S4lfJfR2e4CcpwwJSJrQrk/DS-Illustration-Design-Exploration?page-id=51%3A54&node-id=51%3A55&viewport=254%2C48%2C0.11&scaling=contain) (going into implementation) combining concepts A & C from the explorations above*
