### ISSUE TITLE
Draft Components page content

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/design-system#248]
Create content for the _Components_ page for the Design System website.

[Google Doc for drafting content](https://docs.google.com/document/d/1PWM79uSjY6ffwQabJah9C4F0BcKiGY3Jt6F97GSCc1A/edit?usp=sharing)

**Comment by m-sullivan7** [comment]
@wrendo The remaining pieces for the Component page are:

- Introductory page text
- Section descriptions

Since engineers are a major (if not primary) audience for this page, I'd like to collaborate with an engineer on doing these pieces? Who do you recommend I work with for some brief pair writing?

**Comment by wrendo** [comment]
I think the pool is: Aaron, Chach, Zakiya, Jon. Each bring their own flavor, so your call. You can always start with one and test with the others.

**Comment by m-sullivan7** [comment]
@aaronhans volunteered to be the engineering expert for this content.

After getting an introduction from Aaron on how other design system pages talk about their components, I wrote first draft content in this [Google Doc](https://docs.google.com/document/d/1PWM79uSjY6ffwQabJah9C4F0BcKiGY3Jt6F97GSCc1A/edit?usp=sharing).

Things I could use a review of:

- The introductory text at the top
- The organization of components into group (I eliminated the _Visual components_ group because I felt most of it belonged in the _Structural components_ group, with another one properly belonging in _Navigation components_ after reviewing them again)
- The text describing each component group

I need to check in with the content team to see if anyone looked at the component descriptions I wrote, so that doesn't need to be reviewed right now.

**Comment by m-sullivan7** [comment]
@wrendo Aaron and I did some great collaboration on the [Components page](https://docs.google.com/document/d/1PWM79uSjY6ffwQabJah9C4F0BcKiGY3Jt6F97GSCc1A/edit?usp=sharing) content. The combined ODI/CDT content team also took a look. Do you want anyone to perform a final review of this content before we consider it ready to go?

**Comment by wrendo** [comment]
I think we should actually test the content with some engineers since they're the primary audience. What do you think?

**Comment by m-sullivan7** [comment]
Yeah, let's do it! 👍

**Comment by m-sullivan7** [comment]
@aaronhans I've gotten feedback from the majority of the engineers. I might get some later today, but would be surprised. Do you have time today or tomorrow to look at what we've received to determine if we want to implement it? Everyone's feedback was distinct, so there were no areas of overlap that I could identify as a clear case to make a change.

**Comment by aaronhans** [comment]
The doc looks great! I say ship it. I am happy to chat if you want to go over it a bit more too. Feel free to ping me on slack or schedule a meeting

**Comment by m-sullivan7** [comment]
I actually made a Google Doc for each engineer so they could provide independent feedback. 😉 I can send you all the doc links to see their comments. One includes a couple component naming suggestions that impact https://github.com/cagov/design-system/issues/256. I'll package those shortly!

**Comment by m-sullivan7** [comment]
The content team had a final discussion on component names and have finalized them. The [content in this Google Doc](https://docs.google.com/document/d/1PWM79uSjY6ffwQabJah9C4F0BcKiGY3Jt6F97GSCc1A/edit?usp=sharing) is final.

Closing the issue as done!
