### ISSUE TITLE
Draft Style guides page content

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/design-system#249]
Create content for the _Style guides_ page for the Design System website. This includes any subpages of content for individual guides.

**Comment by wrendo** [comment]
Need to schedule time to scope out further this week

**Comment by m-sullivan7** [comment]
@adam-little I looked at the [Figma mockups](https://www.figma.com/file/A1DSo765cWjvBWoLd6tvEE/DS-website-screens?node-id=301%3A6879) and didn't see a general page for the style guides, just one for the visual design guide and the content guide. Do we plan on a landing page that directs to each of these pages or would people just choose one or the other from a dropdown in the navigation?

**Comment by m-sullivan7** [comment]
@wrendo , @ashleydraper , and I discussed this content today. We decided that we will not have any kind of landing page, but allow the guides to stand on their own.

Adam has created the visual design guide, which is in Figma. We will use the [ODI content design principles](https://docs.google.com/document/d/1orQyak_oQ2dSrDBYCRjauHTIQE51QGE_Cn4TssYrNX0/edit?usp=sharing) for the content design guide. Light rewriting to the introduction will fit this content to the Design System.

As a result, we have all the content we need for these pages and this issue can be closed.

**Comment by m-sullivan7** [comment]
Note from the content team: we'd prefer to label the content design resources as **guidelines** since style guide has a certain association and use in the content world.

**Comment by adam-little** [comment]
Sorry for the late reply:

- For the interim, I agree that a landing page is not needed
- You make a good point about "style guides." Another name to consider is "Foundations" which I see used with some frequency (see [here](https://ux.mailchimp.com/patterns/color), [here](https://polaris.shopify.com/) and [here](https://spectrum.adobe.com/⁤))

In the future, I can see a need to break the visual design guide into multiple pages ([like the State Web Template does](https://template.webstandards.ca.gov/sample/typography.html)). For example, pages dedicated to typography, colors, etc.. At that point, we can consider using the landing-page/subnav structure that our Components page has.
