### ISSUE TITLE
airtable backend for inquiries

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#251]
We'd like to use airtable to store the responses to the "Find out how you can be part of the design system" form

This is going to be a great way to review the data

There are many ways to feed the data into airtable. We want to choose a method that doesn't provide too much frontend weight. 

One possible method:
Form submits to an Azure function or AWS Lambda
The function sends an email notifying people of new submission and sends data to airtable/CosmosDB/DynamoDB all of which can accept any number of fields and work smoothly with changing sets of fields

**Comment by wrendo** [comment]
To do:

checklist, content strategy
