### ISSUE TITLE
Draft Support page content and form

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/design-system#252]
Create content for the _Support_ page for the Design System website.

**Comment by ashleydraper** [comment]
Using [Apple](https://developer.apple.com/support/), [USWDS](https://designsystem.digital.gov/), and Salesforce, we are drafting 2 options for the design system. 

Will connect with Chad regarding a support mailbox.

Connect with engineering about a Git option similar to USWDS.

Look at a form option that negates the need for a specific mailbox.

**Comment by ashleydraper** [comment]
[Draft link](https://docs.google.com/document/d/1TKKQzQhwkyvU8g4a-zJx9fYPx0xdMvjYnnP_kDF72Cs/edit)

**Comment by ashleydraper** [comment]
@extinah Pinging you here to take a look at the draft of the [Support page](https://docs.google.com/document/d/1TKKQzQhwkyvU8g4a-zJx9fYPx0xdMvjYnnP_kDF72Cs/edit#heading=h.tg39pluhniaj).

**Comment by extinah** [comment]
Hi there - looks great. Concise, well written. Win!

**Comment by wrendo** [comment]
@ashleydraper Same as the About page content. How are we looking on support content?

**Comment by ashleydraper** [comment]
@wrendo Aside from Christina's note, I've gotten no feedback on the support page. Michael and I are going to enter what we have in Github, and solicit comments after.

**Comment by wrendo** [comment]
Sounds good. I did take a look at the draft and it looks good. We can review further on Thurs.

**Comment by ashleydraper** [comment]
Thanks @wrendo

**Comment by chachasikes** [comment]
Form is already done
