### ISSUE TITLE
Draft Principles page content

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/design-system#253]
Create content for the _Principles_ page for the Design System website.

[Google Doc for drafting content](https://docs.google.com/document/d/1OeSOexU4WyEkKe_b3oD6-_bJ_G9BNI9TsoX4jj54jLs/edit?usp=sharing)

**Comment by m-sullivan7** [comment]
@wrendo Only a couple of loose items to tie down and we can call the _Principles_ page locked.

Item 1: Adam called out the "eyebrow headers" that are _Principle [#]_. I like each principle being an H2 on the page. That would make these numbered preceding headers tricky if we cascade headers cascade properly. Here are solutions that use a single line, pulling the number into the H2:

- `Principle 1: Design for people's needs`
- `#1: Design for people's needs`

I'm open to other ideas to achieve the design Adam suggested. There might be something I haven't thought of. 🙂 

Item 2: Any final tweaks to the content itself?

- [Google Doc](https://docs.google.com/document/d/1OeSOexU4WyEkKe_b3oD6-_bJ_G9BNI9TsoX4jj54jLs/edit?usp=sharing) where I'm editing
- [Figma](https://www.figma.com/file/A1DSo765cWjvBWoLd6tvEE/DS-website-screens?node-id=0%3A1) where Adam's mocked it up

**Comment by wrendo** [comment]
Love the first example you gave. Let's run it by @adam-little 

Can't think of anymore tweaks off the top of my head

**Comment by adam-little** [comment]
Since the developers already gave the green light to the custom design, I would prefer to keep it because it adds visual variety to the page.

We can talk about semantics separately. Just because the eyebrow sits above the principle title visually doesn't necessarily mean it has to semantically.

**Comment by wrendo** [comment]
Sounds good. We can iterate on that post launch if need be. Maybe we can spin off a mini issue on this to revisit.

**Comment by m-sullivan7** [comment]
Adam and I discussed on Slack and I too am OK with this organization (helpfully made concise by Adam!):

- [h1] Principles
- [h2] Principle #
- [h3] Principle title
- [p] Principle description 

With that settled, this content is done on my end. Any final review you want for it @wrendo ? If not, does that mean this issue is closed?

**Comment by wrendo** [comment]
Closed!
