### ISSUE TITLE
site search

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#254]
Rocket has a built in search component, see if that works for us, if not use google search widget

**Comment by chachasikes** [comment]
Un-assigning Koji cause this hasn't moved in a while.

What is the priority of this feature & is it on our list of DS tasks @aaronhans ?

**Comment by aaronhans** [comment]
This doesn't seem like a high priority to me but would like to get @yesenia-gtz's opinion.

If we add search I'd like to evaluate some of the build time indexing tools that are available as 11ty plugins against the legacy google site search tool

**Comment by yesenia-gtz** [comment]
lets send this to the backlog for now.
