### ISSUE TITLE
Review all component names

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#256]
The component names being used for the titles of the component pages were taken from the docs collaboration spreadsheet

We need to review these to make sure we are using the right names

**Comment by m-sullivan7** [comment]
The content team has been reviewing the names as we've done component documentation reviews for our pieces. We've got 5 to go (7 if you could _Promotional card_ and _Scrollable card_). Right now we're just doing it as we do each component. If we keep to that practice, we estimate we'll be done by December 22.

We have a work meeting tomorrow. If it helps the engineering team, we could do a pass on the remaining names and sort those out. Would you like us to do that @aaronhans and @wrendo ?

**Comment by wrendo** [comment]
@m-sullivan7 Please do. I think we trust the content team on this :)

**Comment by m-sullivan7** [comment]
We'll tackle it tomorrow. Would you like us to do Promotional card and Scrollable card reviewed? Yesterday it was up in the air if they'd be in the January launch components.

**Comment by wrendo** [comment]
Actually, yes. I just realized it's already in our component matrix sheet so it'll be in the DS under "In research", or possibly Alpha. Will let you know later about the progress stage.

**Comment by m-sullivan7** [comment]
The content team has reviewed all the components and considered their names. We've updated the component documentation and the [spreadsheet](https://docs.google.com/spreadsheets/d/1bRHQod0tWuULEHIdKaGB2F4M6Lk1py8eGfvu8GyKqng/edit?usp=sharing) with the new names with our recommendations.

We had some minor questions around the promotional card and related scrollable card gallery (our new, preferred term for that component), but these names will probably hold. Perhaps part of moving from research to alpha is making a decision on the name?

Who should get this issue next for internal review? The content team would be happy to discuss our names if people are not a fan of one. 😉

**Comment by aaronhans** [comment]
Were many of the component names changed in the spreadsheet last couple of days?

I used the names from the spreadsheet to create the set of components in the left nav here https://designsystem.webstandards.ca.gov/ds-components/

**Comment by m-sullivan7** [comment]
This week we made these changes to names:

- Per page feedback became **page feedback**
- Branding/site logo became **department header**
- Scrollable card became **scrollable card gallery**

**Comment by m-sullivan7** [comment]
@aaronhans quick note: I'm soliciting input on the overall _Component_ page content we worked on from other engineers. In the first set I got back there were some suggestions to the component names. If we have time before we need to lock names in, we may want to briefly discuss any feedback on names once it's all in. I asked for thoughts by Thursday.

**Comment by aaronhans** [comment]
No problem, thanks for carefully considering the names

**Comment by m-sullivan7** [comment]
The content designers changed three more names:

- _Department header_ is now **site header**
- _Department footer_ is now **site footer**
- _Button grid_ is now **link grid**

I've asked the content designers to confirm there will be no more name changes and let them know that tomorrow is the cutoff for name changes so we can get engineering going.

**Comment by m-sullivan7** [comment]
The content team has decided on our final names. They are all in the [Component Audit Matrix](https://docs.google.com/document/d/1P-lFCCVyo-A8YKECr5c8euzK-hxKitblxsJKKZbOZq0/edit). Thanks for your patience!

OK to close the ticket @aaronhans and @wrendo or is there anything left on your end to do?

**Comment by wrendo** [comment]
The names look great to me. Ok to close by me. Will defer to @aaronhans for his opinion.

**Comment by m-sullivan7** [comment]
Based on some activity https://github.com/cagov/design-system/issues/248, I think Aaron has what he needs. I'm going to go ahead and close it.
