### ISSUE TITLE
11ty directory structure standardization

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#259]

**Comment by xjensen** [comment]
The main thing to come out of this research is that we should ensure the **layouts** folder is nested within the `_includes` folder. This makes it much easier to `extend` or nest layouts within 11ty.

For now, I'm going with the following defaults.

11ty content/input directory: `site` 
11ty includes directory: `site/_includes`
11ty layouts directory: `site/_includes/layouts`

I believe I can make this configurable by each project too.
