### ISSUE TITLE
Technical Review: Content Navigation component

### ISSUE THREAD

**Issue by chachasikes** [cagov/design-system#26]
# Technical Review

A component proposal for the design system needs a technical review.

The initial version of the content navigation component is under development for the cannabis.ca.gov website (phase 1).

Using this issue to record more of the technical requirements and technical discoveries.

## Development Review Checklist

- [X] Features
- [X] Data structure
- [X] Format
- [ ] Accessibility
- [ ] Analytics
- [X] Performance
- [X] Testing plan
- [X] Prototype code samples (if any)

### Features
*Critical features to support initially.*

* Is a web component
* Can embed in a Wordpress PHP template
* Accept a selector to use to search for header tags
* Read through markup and generate functioning anchor links that can be used in a sidebar navigation element.
* Fill in any missing ID tags.

Future features
* Update url hash so anchor link can be linked to from another page

Notes for UX:
* Content editors will need to know to manage their ID elements appropriately for consistency.

Notes:
* hgroup exists, but we are not currently using that markup pattern.

### Data structure
*If this component maps to an existing schema.org microdata format, please include. If it doesnt, that's ok. We will look it up and provide a data structure. We use schema.org for SEO and data management and round-trip data migration to help keep the component upgradable.*

Not really applicable here.
The https://schema.org/SiteNavigationElement is meant for main page navigation. We use JavaScript to generate the links (though these could be converted to static markup in "static site generation mode")

Will not do this, but if anyone can think of improvements so that the navigation elements can connect better to screen-readers, let's do what we can to make this optimal.

### Format
* Include or reference the expected HTML markup and CSS output (if known)*

`<cagov-content-navigation data-selector="main" data-type="wordpress" data-label="On this page">
</cagov-content-navigation>`

This code current lives in [`includes/templates/template-page.php`](https://github.com/cagov/ca-design-system-gutenberg-blocks/blob/main/includes/templates/template-page.php). 

* For translation in Wordpress, we could create a string interface registry & load in the translated label. (If needed, not needed if we move to headless page delivery.)
* Content editors will not alter this component.
* The `data-label` should be translatable through an API based translation service. 
* For headless page templates, replace `data-label` with a variable from a string interface, scoped (somehow) to the "content-navigation" component. This component is meant to be rendered in a two column layout. Hopefully our WP template  `<div id="page-container" class="with-sidebar page-container-ds">...</div>` element can be used as a source for headless templates with minimal conversions.

Future-proofing:
The data-type is meant to communicate that the source is Wordpress. If needed, this component can be altered with additional types (like data-type="headless") - and altered to support other systems. Not clear on this yet, but it is our plan to keep these components agnostic to CMS. Creating a scope should help in case there are subtle interaction behaviors like adjusting sticky behavior or anchor link behavior that require additional manipulation based on the environment they are rendering in. 

### Accessibility
*In our design system, we are creating fully-accessible components, for delivery and for the editor experience. We have a [baseline]() of general accessibility practices we are following. Are there any additional accessibility considerations with this component?* 

* These are standard anchor links.

Q: What other improvements can we do to assist with page navigation in other devices?

### Analytics
*How can we measure if this component is succeeding in its intention, or discover new insights about needs that we did not know?*

Q: Do we want to measure this? 
NOTE: This probably belongs also in the UX review AND in Technical Review, but the technical review is where we would say what we need to measure & how.

### Performance
*We provide a [baseline]() of tests for basic performance. Will this component present additional performance issues, and if so, how can we address them?*

* Creates a small amount of JS code (in the web component) and some Javascript load to parse through the page.
* Could be statically generated instead, too - using the web component as a basis to compile & not requiring the component to be delivered headlessly for the tiniest possible footprint.

### Testing plan
*We provide a [baseline]() of tests for basic component features. Are there additional tests that need to happen for this component?*

* After we go through scoping out how we register this to the CA Design System as a new web component, we would want to build the following tests:

* Finds exact header tags, including header tags with attributes
* Doesn't include header tags in body content code blocks
* If statically compiling, rendering changes to the selector (adding anchor id's when missing) are captured.
* Links work
* Links scroll without header tag hitting top of page (i.e. has sensible CSS default behavior in the component)
* Links can be restyled with any CSS
* anchor-links with emojis, RTL characters, other UTF-8 characters work. (NOTE: we may want to be more specific here about character support. Current version replaces spaces with dashes and converts to lower case & that's it. Supports any length of anchor link)
* Existing ID tags are not overridden.
* Missing ID tags are created.

## Prototype code samples (if any)

[content-navigation](https://github.com/cagov/ca-design-system-gutenberg-blocks/blob/main/blocks/content-navigation/web-component.js)

* This is the initial version created for cannabis.ca.gov website, Phase 1. 
(The "metadata" issue will talk about where this component belongs.)

**Comment by chachasikes** [comment]
Related issues:
https://github.com/cagov/cannabis.ca.gov/issues/53
https://github.com/cagov/design-system/issues/25

**Comment by chachasikes** [comment]
@aaronhans  @carterm 

Created this technical review for this content navigation component.
@kkoryaka Konstantin: any Accessibility notes (see https://github.com/cagov/cannabis.ca.gov/issues/53 for example links)

@aaronhans Anything to add to this?

@carterm Started to describe how this component works in a Page template. It's not in the design system yet, but will be part of a page template. Is this helpful for you? (p.s. I'm about to write the last "sub-issue" about the naming of this component & where it lives in the design system.)

**Comment by chachasikes** [comment]
Updated with code sample of initial component.

**Comment by aaronhans** [comment]
Any web component should provide a custom elements manifest based on this schema: https://github.com/webcomponents/custom-elements-manifest

You can automatically generate the custom elements manifest json file based on your jsdoc style comments using the wca analyzer: https://github.com/open-wc/custom-elements-manifest/tree/master/packages/analyzer

interactive previews can be automatically built based on the custom elements manifest like https://cagov.github.io/design-system/components/accordion/preview.html

^ This is not required for components that are just HTML & CSS

**Comment by chachasikes** [comment]
Fun fact: Finally found a reference to issue which exact encoding spec we need for the anchors.

https://www.w3.org/TR/CSS21/syndata.html#characters

When we convert this component to a design system & add stories & tests, we will need a test data set of various characters in different encoding types to run (an anchors).

https://mathiasbynens.be/notes/css-escapes

"On the other hand, if you were to use these selectors with the Selectors API (i.e. document.querySelector() and document.querySelectorAll()) or libraries that rely on the same syntax (e.g. jQuery/Sizzle), you would have to take the escaped CSS selectors and escape them again. All you really have to do is double every backslash in the CSS selector (and of course escape the quotes, where necessary):"

* double escaping
* escape the reserved CSS selector characters
* Test with multiple languages and emojis (emoji also triggered a fail in document.querySelector Selector API)

(already applied trim & converting spaces to dashes)
