### ISSUE TITLE
service worker options/functionality review

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#260]

**Comment by aaronhans** [comment]
Rocket has a built in service worker that does some client side full page caching. I notice this getting a little annoying during development because it is caching and I then have to hard refresh to see my latest changes

We discussed service worker usefulness for
- HMR
- Siloing heavy 3rd party scripts so they don't interfere with the main thread like https://dev.to/adamdbradley/introducing-partytown-run-third-party-scripts-from-a-web-worker-2cnp
- A performance improvement if used very carefully, https://developers.google.com/web/tools/workbox is a well known big solution for this.

Let's review the options and see if we can provide value without too much complexity. If so we can augment our tooling with some of these techniques or we can defer and leave service workers alone for now.

**Comment by xjensen** [comment]
I have no plans to do this in the DS site at this time. So I'm removing my assignment, for now.

FWIW, I may experiment with service workers on Drought for loading data-viz below the fold.

**Comment by aaronhans** [comment]
Our local builds are pretty fast already and there are some nice improvements coming in 11ty so this ticket isn't a high priority for the design system.

I'd recommend closing this until we have a more immediate use case. If we encounter a state site whose performance is being dragged down by several 3rd party scripts using partytown to encapsulate them in a service worker could help a lot.
