### ISSUE TITLE
Metadata Recommendation: Content Navigation

### ISSUE THREAD

**Issue by chachasikes** [cagov/design-system#27]
# Component Metadata

A component proposal for the design system needs a metadata recommendation.

Initial Issue: https://github.com/cagov/design-system/issues/24

Our design system uses package control systems, and these systems need names and some basic metadata about the component, and will help with registering the component in the documentation and any libraries.

## Component Metadata Checklist
- [X] Component name
- [X] Short name
- [X] Version number
- [X] Destination
- [ ] Description

### Name of component
*What should we call this component in the design system? The name originally proposed might not follow our naming conventions, or may have a conflict.*

Content Navigation is what we are currently calling it. Everyone seems to understand what we are talking about, but we can use this thread to track if we actually think this is a good name. The name is used in issue reporting too & for training content editors.

### Short name
*What should the computer call this component? (alpha-numeric characters, dash separated, e.g. "highlight-box")* 

Is currently `content-navigation`

### Version number
*Start at v1.0.0, if this is a proposal for a new version, please say so.*

1.0.0
* We are missing the package.json for this component, so we can use this issue to collect the information that belongs in the package registry.

### Destination
* Where should this component live in the design system?* 

`components/content-navigation`

### Description
*How should we initially describe this in the design system (e.g. in Wordpress, documentation, package.json. This content will be revised in the final publishing step.)*

Great question. We had a mini "naming hackathon" for other components, but this, being a utility component is slated to go through a group process to actually discuss the name & generate descriptions that are meaningful to anyone interacting with this component.

**Comment by chachasikes** [comment]
Initial description.
"This component will be used to help page viewers find content on the page."

Content editors are currently doing a UX review which will surface the "how & why" of this component.

In our "mini hackathon" the formula we used to describe the component was:

4 sentences:
Format: 
- [ ] What is it? (quick description for conversation) 

*Block of jump links meant to help page users find important content.*

- [ ] Where does it appear? 

*Intended to be displayed in a sidebar on a webpage.*

- [ ] What does it do? (purpose, intent, why did we build this)

*Reads the header tags in a web page element and dynamically builds a list of links.*

- [ ] What does it include? (features, data elements, etc) (Tips, if any)

*Creates missing anchor links. Content editors can create ID tags in the Advanced area in the Wordpress side panel when entering header links. View page in preview mode to see updated header links.*

**Comment by chachasikes** [comment]
@m-sullivan7 @wrendo 

This is an example of a component that will need a description for publishing to the design system. 

Since content editors can only change the content by adding header tags, this is something that might need to be discussed in a guide.

I don't feel like my description captures the full history of the jump links though. This would be a good description to invite @adam-little into because he worked on this a lot.

**Comment by m-sullivan7** [comment]
Is this work related to (or maybe even the same as) https://github.com/cagov/design-system/issues/25 ? Just trying to keep the streams straight. 😃

**Comment by chachasikes** [comment]
This component is in the design system now. We can close this, but I'm adding a label for it so we can trace issues related to it.

**Comment by chachasikes** [comment]
Already labeled. Closing!
