### ISSUE TITLE
Use sentence case in 3 components

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/design-system#283]
In reviewing the component documentation, the ODI/CDT content designers noticed 3 components that use title case where we think sentence case is more appropriate:

- The statewide footer uses title case. (Example: “Contact Us” should be “Contact us”)
- The back to top button uses title case. (Example: “Back to Top” should be “Back to top”)
- The skip to content link uses title case. (Example: “Skip to Main” should be “Skip to content”)

We recommend updating these components to use sentence case.

**Comment by wrendo** [comment]
No hard coded text. Need to review

**Comment by zakiya** [comment]
Skip to content was handled under another issue.

**Comment by chachasikes** [comment]
@m-sullivan7 
Found these while closing out issues: 

For statewide footer, what's is the correct sentence case - should we change these as well? 

        <a href="https://www.ca.gov">CA.gov home</a>
        <a href="https://www.ca.gov/use/">Conditions of Use</a>
        <a href="https://www.ca.gov/privacy-policy/">Privacy Policy</a>
        <a href="https://www.ca.gov/accessibility/">Accessibility</a>
        <a href="/contact-us/">Contact Us</a>

**Comment by chachasikes** [comment]
Back to top is already updated.

**Comment by m-sullivan7** [comment]
Yay for back to top being covered!

Yes, please update the ones you found to sentence case as well. That would be great. Thank you for catching them!
