### ISSUE TITLE
Skip to content text

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/design-system#284]
In reviewing the skip to content component, the ODI & CDT content designers noticed that the component refers to itself inconsistently:

- The display text reads “Skip to Main”
- The technical example shows display text that reads “Skip to Main Content”

We recommend these be standardized to the component name: "Skip to content" using a capital S since the phrase begins the text string in both instance.

**Comment by zakiya** [comment]
This is done and merge except on the design system website and I've create a new task for that.
