### ISSUE TITLE
Update color of Step List component

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#294]
As per [discussion on Slack](https://cadotgov.slack.com/archives/C024CFNQRDF/p1640729996304200), let's change the color of the Step List component from the "secondary" color variable to the "highlight" color variable.

This will make the step list more prominent and add more visual variety to the pages that it appears on.

- [x] Update [component in Figma](https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/Design-system-UI-kit?node-id=0%3A1) [@adam-little]
- [x] Update color on Cannabis (from #2F4C2C to #C0633B) [@chachasikes]
- [x] Update color for Design system (from #FF8000 to #FEC02F) [@kkoryaka]

**Comment by adam-little** [comment]
The new step list on the design system will look like this by default 
![image](https://user-images.githubusercontent.com/69167298/147983830-c9c4191a-e0bd-468d-a49f-52a003109ec8.png)

**Comment by chachasikes** [comment]
@adam-little  What will the color be for drought - for @xjensen ?

**Comment by adam-little** [comment]
Highlight color for drought is #FBAD23

https://www.figma.com/file/3N4dFWhFqiGpWr1DRQoJUM/Design-system-colors?node-id=0%3A1

**Comment by kkoryaka** [comment]
@chachasikes I have updated design system package to v2.0.1 and published it to NPM, now you can go ahead and update cannabis (and drought?) website.

**Comment by kkoryaka** [comment]
Updated it in headless: https://headless.cannabis.ca.gov/applicants/how-to-apply-renew/

**Comment by adam-little** [comment]
Looks good to me. Thanks!
