### ISSUE TITLE
Create post-launch plan for adding icons to the design system

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#299]
Creating this issue to capture the need to make icons available in the design system.

For reference is the [web template icon font](https://template.webstandards.ca.gov/sample/icon-fonts.html).

Hypothesis is that SVGs are the best format.

**Comment by adam-little** [comment]
Tagging @kkoryaka into this. He mentioned that the icons from the state web template have been integrated into the design system already.

Let's pick this up post soft launch.

**Comment by zakiya** [comment]
Going to close this in favor of #608
