### ISSUE TITLE
Component: State site universal footer (informs DS)

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#3]
All California government state sites should share a footer component. This provides a bookend of familiar branding at the bottom of pages and contains links to common state sites.

## Requirements:
- Create a footer component that matches Adam's designs.
- This component should be installable independently. 
- It should inherit the appropriate parent styles but contain enough code to work on its own. 
- Use only the minimal amount of code to ship this tool. This component probably does not require javascript so it should be created with HTML and CSS only. 
- Component should work smoothly with screenreaders
- Component should be as lightweight as possible not dragging down page performance
- Component should be independently responsive without media queries so that this element can be use appropriate layouts inside any size parent container, not just the entire page 

## Tasks:
- Create the HTML, CSS for the component 
- Get design signoff from Adam on standalone component
- Publish the component as part of the component collection in the design system repository
- Implement the component on digital.ca.gov

Screenshots from [figma](https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/cannabis.ca.gov-screens?node-id=381%3A3318)

<img width="318" alt="footer" src="https://user-images.githubusercontent.com/353360/117727717-445f2500-b19d-11eb-8043-f2ce2f477547.png">

**Comment by kkoryaka** [comment]
Added kk-footer branch with initial development of the universal footer component (placed inside of /components/ folder.)

**Comment by kkoryaka** [comment]
Added footer WP styles: https://github.com/cagov/cannabis.ca.gov/commit/d054503669eb98026140684310f035d26d5c53bb
