### ISSUE TITLE
Add necessary accessibility properties to content navigation component

### ISSUE THREAD

**Issue by kkoryaka** [cagov/design-system#309]
- Make sure that content navigation component is using a navigation landmark (enclosed into `nav` tag) and has ARIA label (has `aria-labelledby` attribute).
- Make sure that content menu’s visual heading (which is usually “On this page”) has `id` attribute that is referenced in nav’s `aria-labelledby` attribute.

**Comment by kkoryaka** [comment]
@zakiya since you are currently working on it maybe you can incorporate this a11y fixes?

**Comment by zakiya** [comment]
This is done and merged.
