### ISSUE TITLE
Decrease line height on headers for improved readability

### ISSUE THREAD

**Issue by kmbrlygl** [cagov/design-system#313]
Current line height across all typography is 1.6 (golden ratio) x font-size. This works for body text but is too large for headings (h1-h5) and should be reduced (tightened up) for [readability](https://accessibility.digital.gov/visual-design/typography/).

To do

- [x] Work on optimal line height ratios for h1-h5
- [x] Review and approve the change with Konstantin
- [x] Update [Documentation](https://docs.google.com/document/d/17MtpWf1rZIl_Ge05DEQqIsd_NxBYha6krjRBhSUhdXg/edit?usp=sharing)
- [x] Update Figma UI Kit
- [x] Update DS Typography Page

**Comment by kkoryaka** [comment]
Unfortunately, we have this ugly accessibility rule that requires us to do line height (line spacing) to at least 1.5 times the font size;  So, the closest we can bring it is 1.5 :(   
Also, if we make it less than 1.5 the accessibility tools will mark it as an error and our score will go down. 
So, making it 1.5 is not a big difference from 1.6, But at lest we can make that.

**Comment by kmbrlygl** [comment]
Thank you for your input @kkoryaka! Let's go with 1.5 for headers then if that's the minimum. I don't want to affect the scores negatively.

I'll update the documentation, Figma UI kit, and website mockup to reflect 1.5 for headings. 

FYI, I will probably create a separate ticket for myself to think about this a bit more at a later date. I want to have a convo around accessibility beyond the technical requirements at some point. [USWDS](https://designsystem.digital.gov/design-tokens/typesetting/line-height/) and [Accessibility.digital.gov](https://accessibility.digital.gov/visual-design/typography/) allow for less than 1.5 on headers, so I'd like to look into how they've justified being able to use smaller line height (maybe trade-offs, other research, etc.)

**Comment by kkoryaka** [comment]
Actually, i found pretty interesting take on headings: https://ux.stackexchange.com/questions/140142/accessible-line-height-for-headings-h1-h2-h3-etc
So, since headings aren't the main paragraph content, the line-height doesn't have to be 150% to be accessible. And we can fool accessibility checkers by adding line-hight to the html tag (the way accessibility.digital.gov does it)
![Screen Shot 2022-01-07 at 2 35 26 PM](https://user-images.githubusercontent.com/31669748/148616233-e042c04f-6d7e-4adb-9ab7-04e0cf095eea.png)
. So, I think we can pull it off.

**Comment by kkoryaka** [comment]
@kmbrlygl let me know when you have something ready

**Comment by kmbrlygl** [comment]
Here's what I'm proposing for the [line heights for headings (in Figma)](https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/UI-Design-kit?node-id=720%3A4447)
I initially had different ratios for each heading but I thought that was too many different variables, so I landed on **1.4** ratio looking the best without being too tight or too loose for all headings. Let me know what you think!

FYI - I made a note re: why I used Vietnamese. I pulled random text from the Cannabis site (Google translated).

cc @adam-little

**Comment by adam-little** [comment]
That looks good to me @kmbrlygl. Just please be sure to update the text styles in our shared Figma library. Thanks!

**Comment by kmbrlygl** [comment]
@kkoryaka I changed my mind about using only one ratio for headers. I'd decided to decrease the ratio by 1/8 step for each ascending level. Essentially as font-size increases, the ratio decreases. Here's it is in the [UI Kit Library](https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/UI-Design-kit?node-id=720%3A4447). The updated spacing is published. I am working on updating the documentation on the Visual Design style guide. 

Let me know if you have questions.

**Comment by jaredwyee** [comment]
@kmbrlygl  can you confirm that the headers are per your spec in the release branch: https://1-0-2-a11y-design.pr.designsystem.webstandards.ca.gov/

**Comment by kmbrlygl** [comment]
Yes, this is good to go.
