### ISSUE TITLE
Reconsider ds-dropdown-menu component with progressive enhancement in mind. 

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#319]
When javascript is disabled on drought and cannabis, many of the pages are not reachable because the main navigation drop downs are generated by javascript. This seems especially an issue on cannabis because the main nav links are dummy links that lead to pages like https://cannabis.ca.gov/about-us/  I think it’s fair to argue that very few users have javascript disabled but this feels like it goes against the way we’ve talked about progressive enhancement.

Possible failure cases:
JavaScript is disabled or not supported
JavaScript is executing but custom elements are not supported
JavaScript is executing but asset failed to load

Possible solutions CSS/HTML only solutions:
https://codepen.io/markcaron/pen/wdVmpB

**Comment by aaronhans** [comment]
We can consolidate this with https://github.com/cagov/design-system/issues/741
