### ISSUE TITLE
Code block design update

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#322]
Need to review the look and feel of code block syntax highlighting.

**Comment by adam-little** [comment]
Is there such a thing as standard (i.e. neutral) colors for this type of code? For example, the colors that you see when you view the page source for a website.

My preference would be to use those colors ([the example here](https://opensource.adobe.com/spectrum-web-components/components/divider/) or [here](https://ux.mailchimp.com/patterns/buttons) feels more neutral to me)

OR to define a set of colors more in line with the rest of the website ([here's an example](https://www.lightningdesignsystem.com/components/accordion/) that feels on brand with the rest of the website)

**Comment by xjensen** [comment]
Those examples are really helpful, thanks!

We are currently uses a syntax highlighter called highlight.js. There are a lot of [open source themes](https://highlightjs.org/static/demo/) that would be very easy for us to integrate. We're currently using the "A11Y Dark" theme.

I wouldn't say there's a common standard at the moment. The closest thing is probably the default in Visual Studio Code. I see similar colors used to display source across various web browsers, etc. See the "VS" and "VS 2015" themes on that demo page linked above. GitHub's highlighting colors are also popular. The Mailchimp example you provided looks very GitHub-ish. 

Creating our own theme from our own colors sounds like fun. I'd love to do it. But I'm not sure if we can fit it into our activities before launch in a few weeks.

**Comment by adam-little** [comment]
Let's stick with A11Y Dark until we have the time and bandiwdth to create a custom theme. Sound good?

cc @kmbrlygl

**Comment by chachasikes** [comment]
Is this done now @xjensen ?

**Comment by xjensen** [comment]
@chachasikes Not started. I don't believe it's a high priority. 

Ideally, we would have #304 in hand before attempting to create our own syntax highlighting theme. Not sure what the status is there. Paging @kmbrlygl.

**Comment by kmbrlygl** [comment]
What's paging? 😉 @xjensen @chachasikes 
Yep, I'm prioritizing #304 first in this upcoming sprint since it affects buttons and forms and will help solve other color-related issues like this one. I'll loop back on this after I get it sorted out since it's a bit complicated.
