### ISSUE TITLE
Social media metadata

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#325]
What does the default sharing look like right now?

Is it good enough for launch or too messy and needs to be fixed pre-launch?

**Comment by aaronhans** [comment]
Assigning to Jon because I remember you mentioning you fixed some of this already

**Comment by xjensen** [comment]
The plumbing is in the site and ready to go. We just need content. I'm meeting with content team this afternoon to show them how to add social metadata to the site.

**Comment by xjensen** [comment]
Much of this work appears to be complete. Might be worth checking with content team to see what's left. Tagging in @m-sullivan7.

**Comment by m-sullivan7** [comment]
The content team added metadata to all pages and components. This is done!
