### ISSUE TITLE
Page alert: sort out color alerts

### ISSUE THREAD

**Issue by chachasikes** [cagov/design-system#348]
The State Template uses some colors on page alerts.
Currently the page alert color is hard coded as highlight colors.

Sort out:
* What colors do we need to support
* Update documentation
* Any accessibility requirements

**Comment by chachasikes** [comment]
Follow up on this (scope it out) in upcoming accessibility sprint

**Comment by zakiya** [comment]
Assigning to myself. 
Notes from Chach  on Slack:

- Christina knows things about page alerts & colors of existing State template component
- I added this to the sprint as “let’s use this as an example” and talk it through so we understand how we merge things - page alert is in the State Template & it needs someone to start the conversations on what the colors of the messages should be

**Comment by zakiya** [comment]
Un-assigning myself so my Issue list is current. Feel free to assign to me when/if it leaves the backlog.
