### ISSUE TITLE
Pagination needs code love

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#349]
Creating this issue since I saw a note on it in Notion.

@chachasikes Assigning you just to start, but feel free to reassign to the appropriate person.

**Comment by aaronhans** [comment]
Action plan:

- Add code sample and description for how to consume the events sent by the pagination component. This can be taken from cannabis' recent implementation
- Add explanation that this component relies on underlying site functionality to replace paged content

**Comment by aaronhans** [comment]
Code changes merged
