### ISSUE TITLE
Update component file names to match updated names

### ISSUE THREAD

**Issue by extinah** [cagov/design-system#367]
Not a priority. Do this when there is time. Example: content navigation is now page navigation. Update the component name (including the design system web page).

**Comment by chachasikes** [comment]
Subscribing

**Comment by xjensen** [comment]
This is ready for review at #602. And it should really be reviewed carefully by the engineering team; it's a big change.

Better to do this sooner than later. The longer we let this wait, the more difficult it will become to make these changes out in the world.
