### ISSUE TITLE
Statewide footer: contact us

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/design-system#368]
In working on the statewide footer component, I'd like to confirm some things that might have been settled in the discussion yesterday about the _Contact us_ link.

- Do the state web standards require a _Contact us_ link in a site's footer?
- If so, do the state web standards require it go to a certain place? For example, does it have to go a general ca.gov contact us page? Could it go to a department contact us page?

We'll use the answers to these questions to update the guidance around the statewide footer component. There may be associated changes to the site footer component, depending on the answers.

These questions are not Design System stealth launch blockers.

Tagging @artuoma and @rkojik since they know the CA Web Standards well!

**Comment by rkojik** [comment]
Doesn't require a "contact us" link, however, the footer must contain "Contact information or link to contact information of the Agency/state entity that owns the website so there is no question as to which Agency/state entity the user may contact."

**Comment by m-sullivan7** [comment]
Thanks for the clarification @rkojik ! I'm going to update this component (and the site footer) to make it clear that:

- You use the statewide footer to provide a contact us link for your site.
- It's required in the statewide footer.
- A contact us link does not go in the site footer.

When that's done, I'll close this ticket.
