### ISSUE TITLE
Issue: Fix highlight section option that has no content

### ISSUE THREAD

**Issue by kkoryaka** [cagov/design-system#369]
When highlight section doesn't have much text the right column width is getting smaller. Make sure that right section always have full width. 
![Screen Shot 2022-01-14 at 9 49 10 AM](https://user-images.githubusercontent.com/31669748/149561633-6c4383e2-d198-4649-9b22-853c798ff834.png)

**Comment by aaronhans** [comment]
Thanks @kkoryaka. Good fix to make sure the CSS retains desired width. Also need to figure out where the body copy went because they should all have it

**Comment by aaronhans** [comment]
@xjensen just fixed the missing copy https://github.com/cagov/design-system/pull/373#event-5896439022
