### ISSUE TITLE
Link icon: content edits

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/design-system#370]
The content for the link icon uses "important" several times close together:

> In the case of PDF links, this can be important for people on mobile devices. They may not want to open a PDF for various reasons (use up their data, do not want to download a file, etc.). It’s also important for those who use screen readers, as it will announce, “This is a PDF file.”
>
> If a link is both external and a PDF, only the PDF icon will appear. It’s more important to tell people they’re going to a PDF than it is to tell them that it’s not hosted on the same site.

This is a post-January launch issue to rewrite this content to decrease the use of "important".

**Comment by m-sullivan7** [comment]
Proposed new content:

> In particular, the PDF link icon provides benefits to some groups of people. People on mobile devices may not use their data or download a file. Screen readers will also announce that the link goes to a PDF file.
>
> If a link is both external and a PDF, only the PDF icon will appear. It’s more important to tell people they’re going to a PDF than it is to tell them that it’s not hosted on the same site.

@extinah @ashleydraper @LizNobriga @thepegisin Any thoughts about this revision to get at this thorny piece of content we deferred during launch? All edits are in the first paragraph, where I wrote around saying "important" since I thought it was more important (ha!) to convey the idea of importance in the second paragraph.

For those keeping score: grade 5 reading level, no adverbs, no passive voice, no simpler alternatives, no hard/very hard to read sentences. 🙂 (Doesn't mean there isn't room to improve though!)

**Comment by LizNobriga** [comment]
I like how you've rewritten it to avoid repeated use of "important". 

We could describe how it functions for screen readers earlier in our description, and include both pdf and external. 

We could also explain why anyone would need to know it's a PDF before opening a link (even if that seems obvious), and then note how that specifically helps people on mobile. 

Suggested language (same readability scores):
> The link icon adds an icon next to links that go:
> 
> - Outside your website (an external link)
> - To a PDF
> 
> The external link icon is a box with an arrow pointing to the upper-right corner. `For people using a screen reader, it will announce the full URL.`
> 
> The PDF icon is the letters PDF surrounded by a box outline. `For people using a screen reader, it will announce that the link is a PDF file. `
> 
> These icons tell people they are leaving the current website in some way.
> 
> `Knowing that a link goes a PDF lets people decide if they want to open it. This may be helpful to people using mobile devices with limited data plans.`
> 
> If a link is both external and a PDF, only the PDF icon will appear. It’s more important to tell people they’re going to a PDF than it is to tell them that it’s not hosted on the same site.

**Comment by m-sullivan7** [comment]
I like these changes @LizNobriga. Thank you for thinking about them!

Anyone else have revisions they'd like to suggest?

**Comment by m-sullivan7** [comment]
Published these changes.

**Comment by extinah** [comment]
Sorry so late - great updates. Nicely done.

**Comment by m-sullivan7** [comment]
Thanks! This is a good example of one of the types of edits we'll want to think about for content management and maintenance.
