### ISSUE TITLE
Regulatory outline description and demo

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/design-system#375]
In the description of the regulatory outline, markdown seems to be creating a gray box around some of the example of how the pattern example.

![image](https://user-images.githubusercontent.com/69169190/149566363-77e0d3f1-2718-4402-80f9-42ba660162b8.png)

Is there a way to prevent this box from showing up? Alternatively, does the demo make this duplicative? We could also consider paring down the demo example to not use as many items per level.

This is a post-January launch issue.

**Comment by m-sullivan7** [comment]
I believe I've solved (at least temporarily) the gray box issue by moving all of the content into a gray box through the use of extra spaces.

![image](https://user-images.githubusercontent.com/69169190/149568685-f74457fe-986f-4e7c-9476-be65e1128724.png)

I'd still like to discuss if there's a better solution, or if we need this at all, after the January launch.

**Comment by xjensen** [comment]
When indenting text in Markdown, it's interpreted as a code block. That's why the gray box appears only for the rest of the lines in your first screenshot, and around everything in the second screenshot.

One way to cheat this is by using the non-breaking space, `&nbsp;`. It's ugly, but it'll work. Here's how it would look in the file.

```markdown
(a)(b)(c)

&nbsp;&nbsp;(1)(2)(3)

&nbsp;&nbsp;&nbsp;&nbsp;(A)(B)(C)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(i)(ii)(iii)
```

**Comment by m-sullivan7** [comment]
I suspected it was something like that. I appreciate the `&nbsp;` trick, Jon. I've updated with that since it's closer to the original idea for the content. Thanks!

**Comment by zakiya** [comment]
It looks like this is fixed. Can we close?

**Comment by m-sullivan7** [comment]
Yes. Any further work should be a different issue. We're good for now! I'll go ahead and close since I'm already in here.
