### ISSUE TITLE
Header font size exploration

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#379]
**Context:**
Feedback from the team at DCC is that it's difficult to visually differentiate headers which makes it hard to understand hierarchy of content. 

Here's an example of a page that has H1, H2, H3 and H4: https://cannabis.ca.gov/applicants/equity-fee-waivers/

**Opportunity:**
How can we make different headers contrast more with each other?

**Ideas to explore:**
- More variation of text size
- More variation in text line weight
- Incorporate colors into headers
- More white space between section of a webpage (i.e. more white space above h2s)
- Consider finding a unique typeface for use on some or all headers (e.g. a serif type for H1s and H2s)

**Comment by adam-little** [comment]
Assigning to @kmbrlygl as well. This is something we can both be exploring when we have free time. This is for post launch.

**Comment by adam-little** [comment]
Here's a resource that could provide a framework for how we think about this:
https://blog.prototypr.io/10-practical-steps-to-create-a-predictable-accessible-and-harmonious-typography-system-a-case-6c85d901bedd

**Comment by kmbrlygl** [comment]
Thanks for that resource @adam-little I like how there were notes around heading usage. 

I riffed on a few type treatments with different fonts and additional spacing on the [Sketchpad](https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/UI-Design-kit?node-id=852%3A4964). I think the added spacing is making the biggest difference with differentiating the sections and defining a clearer hierarchy.

On v5, I tried out styling the H5 to be used as an eyebrow heading (for other contexts, not for this particular issue). Unsure if we want to be styling titles in all-caps but just an idea to help think of ways to create more variation in the headings.

**Comment by adam-little** [comment]
@kkoryaka Kimberly and I did some explorations for improving our text header styles so that there is more contrast between H1, H2, H3, etc...

https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/UI-Design-kit?node-id=89%3A2867

What do you think of these? Would it be possible to stage these on a Cannabis page (for example: https://cannabis.ca.gov/applicants/equity-fee-waivers/) so that we can see how they look with real content?

**Comment by kkoryaka** [comment]
@adam-little cannabis monolith is not good candidate for it. Maybe headless cannabis instance would work better. Why don't you explore it in the design system site? We can create a new page and make a PR and it will have a preview link for you.

**Comment by adam-little** [comment]
> @adam-little cannabis monolith is not good candidate for it. Maybe headless cannabis instance would work better. Why don't you explore it in the design system site? We can create a new page and make a PR and it will have a preview link for you.

The reason i suggested DCC is because this is a request that has come from the DCC team. I would like to get their feedback by showing them how it looks with their content. Let's discuss during our design call today.

**Comment by adam-little** [comment]
Hey @kkoryaka can you prototype this on the DS website?

**Comment by yesenia-gtz** [comment]
Update:
Will be completed by close of sprint.

**Comment by kkoryaka** [comment]
Added [prototype page](https://1-0-6-headings.pr.designsystem.webstandards.ca.gov/pr/1-0-6-headings/typography/) with real time content that is displaying headings and their font-weight variations
NOTE: THis is font exploration is case study that will be presented to DCC customer. New headings font weight applied to the headings in the [prototype page](https://1-0-6-headings.pr.designsystem.webstandards.ca.gov/pr/1-0-6-headings/typography/) only and is not applied globally yet.

**Comment by kkoryaka** [comment]
@yesenia-gtz who can present this [prototype page](https://1-0-6-headings.pr.designsystem.webstandards.ca.gov/pr/1-0-6-headings/typography/) to DCC?

**Comment by yesenia-gtz** [comment]
In review with cannabis SMEs

**Comment by adam-little** [comment]
IMO, we should push this update since the design system team feels like it addresses the initial problem.

The [feedback from Department of Cannabis Control](https://cadotgov.slack.com/archives/C01N25FCCPN/p1649960658959159) was that it might now go far enough, but I would consider this an iterative improvement.
