### ISSUE TITLE
Promotional Card

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#39]
We are really excited to share our idea for a design system component.

Our design system team will review this component proposal.

*To make sure the component serves all Californians, we have identified some things we need to know about this component.*

- Please fill in what you can. 

---

### Checklist
- [x] Name
- [x] About this component
- [ ] Description
- [x] Examples (ca.gov)
- [ ] Examples (design systems)
- [ ] Features
- [x] Requesting agency

### Name
We're calling this a promotional card as it pertains to the campaign toolkit (for now).

# About this component
This component is an initial preview into current or archived departmental campaigns. It is a link to the corresponding campaign page.

### Description
Pic
Title
Start/End date
Desc
URL

### Examples from ca.gov properties
See Landing Page V2 

![Screen Shot 2021-07-30 at 11 25 09 AM](https://user-images.githubusercontent.com/1387973/127696255-9cb387b8-3ee8-48ff-8c24-306b5713744d.png)

[Figma link](https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/Design-System-Projects?node-id=3036%3A10628))

### Examples from other design systems
TBD

### Features
Pic
Title
Start/End date
Desc
URL

### Requesting agency
Department of Cannabis Control

---

Thank you!

[Learn more about our review process.](#tbd)

**Comment by chachasikes** [comment]
This is the draft of a README I wrote for this component.


# Promotional Card

Card that highlights content. Designed for page content. Provides image asset, name, description and hyperlink.

Designed to give equal promotion to a set of assets.

This component is being developed as part of the California Design System.
* Initial proposal: https://github.com/cagov/design-system/issues/39
* Technical review: https://github.com/cagov/design-system/issues/45
* Metadata: https://github.com/cagov/design-system/issues/46

Any bugs or issues can be reported to [design-system](https://github.com/cagov/design-system).

**Comment by chachasikes** [comment]
@aaronhans, I'm using this issue to vet recurring assets we need to keep track of (and revise our issue templates again.)

What is the best component in the design system to review for any other metadata we might need to collect?

**Comment by aaronhans** [comment]
Page feedback has the basic pieces: https://github.com/cagov/design-system/tree/main/components/feedback

JSDoc style comments in the index.js
^ used to generate a custom-elements-manifest.json
^ used to create interactive docs+preview with api-viewer
It has a readme, package.json (just noticed the source code location is missing from package.json, probably other stuff missing too)
