### ISSUE TITLE
Site header requirement discussion

### ISSUE THREAD

**Issue by ashleydraper** [cagov/design-system#394]
In the site header component, we state that this is required if using the design system. An engineering discussion is needed to true up this language.

**Comment by m-sullivan7** [comment]
@ashleydraper I think we evened this out in our final content pass. Is that your recollection? If so, let's close this and celebrate! 😄

**Comment by ashleydraper** [comment]
@m-sullivan7 You're right and I see that reflected on the site. We can close and celebrate!!
