### ISSUE TITLE
Add Support page

### ISSUE THREAD

**Issue by ashleydraper** [cagov/design-system#395]
The Support page was removed from the initial launch to allow time to build infrastructure. Team must decide who will field public inquiries and an appropriate response time.

Building this page will require both content and engineering.

Content 
* draft content for page
* add page to top menu navigation
* add metadata

Engineering
* Build "other" option in drop down menu so that users can write in their responses

**Comment by chachasikes** [comment]
Not sure on status of "Other" - let's flag for review

**Comment by chachasikes** [comment]
@ashleydraper  - Does the Contact us page have the correct metadata you wanted?
