### ISSUE TITLE
Content style guide navigation improvements

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/design-system#402]
The content style guide pages are disconnected and do not make it easy to move between them (or even realize there are others). These pages are:

- https://designsystem.webstandards.ca.gov/style/content/
- https://designsystem.webstandards.ca.gov/style/content/focus-on-user-needs-services/
- https://designsystem.webstandards.ca.gov/style/content/meet-your-audience-where-they-are/
- https://designsystem.webstandards.ca.gov/style/content/build-accessibility-from-start/
- https://designsystem.webstandards.ca.gov/style/content/be-concise/
- https://designsystem.webstandards.ca.gov/style/content/write-in-plain-language/
- https://designsystem.webstandards.ca.gov/style/content/write-with-conversational-official-voice/
- https://designsystem.webstandards.ca.gov/style/content/organize-content-strategically/

One possible solution: use the navigation that we use on the component pages that shows all the pages in that section in one place. This would make it easier for people to switch between principles without having to leave the page to get back to the main content style guide page.

This was deferred from the initial launch to allow engineering to focus on other priorities.

**Comment by m-sullivan7** [comment]
Assigning to @jaredwyee for analytics pull to see if we can intuit out any trends in these pages.

**Comment by jaredwyee** [comment]
![image](https://user-images.githubusercontent.com/85529382/153965850-e917a1a3-6a30-405a-94d0-a3522ad72162.png)


[https://analytics.google.com/analytics/web/#/report/content-drilldown/a20973992w42130624p25947[…]~2Fstyle~2F,analytics.pagePathLevel2:~2Fcontent~2F/](https://analytics.google.com/analytics/web/#/report/content-drilldown/a20973992w42130624p259474870/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePathLevel1:~2Fstyle~2F,analytics.pagePathLevel2:~2Fcontent~2F/)

**Comment by m-sullivan7** [comment]
We might be able to close this issue as it's the same as #744 and design work took place in that one.

**Comment by m-sullivan7** [comment]
I'm closing this issue in favor of #744
