### ISSUE TITLE
Fix staggering of social media icons

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#404]
![Screen Shot 2022-01-21 at 3 56 41 PM](https://user-images.githubusercontent.com/1387973/150614965-6e4da1f0-e774-4167-8b0a-c4b718112a81.png)

**Comment by zakiya** [comment]
https://github.com/cagov/design-system/pull/409

@todo 

- [ ] Figure out why it happens on designSystem but not drought and cannabis
- [ ] Visual regression tests

**Comment by zakiya** [comment]
This is done for the design system website but there are things that need to happen to the component before we change the issue status.

**Comment by zakiya** [comment]
Done in https://github.com/cagov/design-system/pull/471 and https://github.com/cagov/design-system/pull/409
