### ISSUE TITLE
Simplify and reduce text on homepage

### ISSUE THREAD

**Issue by thepegisin** [cagov/design-system#421]
The text on the homepage is not meeting our standards for readability:
- Reading level is Grade 9
- There are 3 very-hard-to-read sentences, including the first sentence
- There are 4 hard-to-read sentences
- The overall volume of text seems quite high. There are 12 paragraphs to read. At least some could be one sentence.

Tasks:
- [x] Check text in Hemingway and rewrite VHTR and HTR sentences
- [x] Substitute simpler words for terms like "performant" to lower reading level
- [x] Convey meaning more directly with fewer words
- [x] Review
- [x] Edit
- [x] Get approval
- [x] Stage
- [ ] Check
- [ ] Publish
- [ ] Check

**Comment by m-sullivan7** [comment]
@jaredwyee looping you into this future issue so it can be on the fringes of your brain. The content designers would like to look at the homepage content once we're beyond (perhaps well beyond) stealth/soft launch. It was written with a v1, soft launch mindset. In looking back on it, we were probably guessing at who we were speaking to with this page and may have wound up trying to speak to several at once (never a great idea). Some guidance from the onboarding governance team would be a good starting point for this work!

**Comment by m-sullivan7** [comment]
@thepegisin and I will work on this together. I synced the [old working doc](https://docs.google.com/document/d/1eU7Y0Hacs8oPUloLaIN0koK15zur0HXa663abvvhviw/edit?usp=sharing) with the current content so it reflected some pre-launch changes.

Before Peggy and I begin work, I'll ask some questions of @yesenia-gtz to make sure we're approaching our work with the right frame of mind. 🙂

**Comment by m-sullivan7** [comment]
@thepegisin I left one question in the doc and took the liberty of checking the first three items in your list based on our work today. Once we answer that question, I think we're ready for a review before sending our proposed edits to our Design System stakeholders.

**Comment by m-sullivan7** [comment]
@yesenia-gtz has approved these edits. I will get them up today.

**Comment by m-sullivan7** [comment]
https://github.com/cagov/design-system/pull/765 contains these edits for review.

**Comment by m-sullivan7** [comment]
Readability edits have been published. Thanks to all who were involved in making this happen! Closing this issue.
