### ISSUE TITLE
Resolve where to offer contact link

### ISSUE THREAD

**Issue by mediajunkie** [cagov/design-system#428]
Goal: Make it as easy as possible to respond to the site

To do:
Determine whether and if so how to add a "Contact Us" link to the global site menu while also respecting the rules governing state website footers, without running afoul of any legitimate accessibility concerns.

**Comment by adam-little** [comment]
I asked Greg Duncan if any accessibility rules are broken by having the same link in the site header and the site footer. He said there is not, as long as they are the same link to the same page [[see Slack thread](https://cadotgov.slack.com/archives/CQSM886RK/p1643057779023700)].

As per CA Web Standards, every site needs to offer a "Contact" link in the footer. In the Design System, this can be in the Agency Footer _or_ the Statewide Footer. The current policy is not specific about language.

**Design System Approaches:**

**Option 1: Forced compliance**
![Screen Shot 2022-01-24 at 4 22 04 PM](https://user-images.githubusercontent.com/69167298/150867135-395218e2-a8f8-4fce-85e7-59b0f6adcd4e.png)

- Force compliance by including a contact link in the state wide footer. Discourage any editing to this component.
- Link to https://www.ca.gov/contact/ for universal applicability
- User a label such as "State Contact Directory" to ensure it is not confused with an agency's contact page, when available
- **Pro:** Ensures all websites are in compliance
- **Con:** May result in two contact links in the footer which could create confusion

**Option 2: Default contact link in Statewide Footer**
![Screen Shot 2022-01-24 at 4 33 18 PM](https://user-images.githubusercontent.com/69167298/150868561-0481ab2d-50a0-42a1-aa96-e5a3430ff915.png)

- Create compliance by default by including a Contact Us link in the Statewide Footer
- By default, link to https://www.ca.gov/contact/ for universal applicability
- Allow website admin to customize this link with agency contact page when available
- **Pro:** Ensures all websites are in compliance
- **Con:** Incorporates agency links into Statewide Footer, which blurs the separation between the two

**Option 3: Contact link in Agency Footer**
![Screen Shot 2022-01-24 at 4 38 58 PM](https://user-images.githubusercontent.com/69167298/150869312-5ac91966-5455-4a42-821e-5a55a8f22eba.png)
- No link in Statewide footer
- Agency must create contact link in Agency footer
- **Pro:** More intuitive and prominent place to find agency contact info
- **Con:** Agency's who do not add link here will not be in compliance

**Comment by adam-little** [comment]
If we go with Option 2 (which is what we currently have), then I would argue that we make the Contact page on designsystem.webstandards.ca.gov more discoverable by including it in the Site Header (given that we are trying to collect as much feedback as possible right now).

As per the feedback from Greg Duncan, this will not violate any accessibility issues.

**Comment by m-sullivan7** [comment]
Thanks for exploring this with Greg, @adam-little! I was unaware that putting a contact link in the site footer satisfied the state web standards. Since that's the case, I endorse option 3. I like pulling department- or site-specific contact info in a space that's specific to the website, rather than blurring the lines by placing it in a statewide space.

There's one use case I'd like to explore with option 3: if a site does not have a site-specific contact information (like is the case with [drought](https://drought.ca.gov/)) and they fall back to https://ca.gov/contact/, would we still recommend that link go in the site footer?

**Comment by adam-little** [comment]
> There's one use case I'd like to explore with option 3: if a site does not have a site-specific contact information (like is the case with drought) and they fall back to https://ca.gov/contact/, would we still recommend that link go in the site footer?

- For the sake of making the Statewide Footer a component that agency's do not have to give any thought to, I would say No.
- I would argue that we should make it a requirement that the agency footer provides a link to some form of contact channel
- This does not have to be a dedicated contact page per se. It could be:
- An email link
- A link to the About Page if it contains contact information
- In the case of Drought, I think it's our responsibility to create content that directs people to the appropriate department/agency. It could be a part of the [Resources](https://drought.ca.gov/resources/) page. While linking to https://www.ca.gov/contact/ may satisfy the policy requirement, it provides little to no value to a user who has a question/comment related to Drought.

**Comment by mediajunkie** [comment]
@ashleydraper I know you were part of this conversation? Can you share your take on it, given he above breakdown of this issues involved by Adam?

**Comment by adam-little** [comment]
Noting duplicate issue here (from QA): https://github.com/cagov/design-system/issues/475

**Comment by chachasikes** [comment]
(I see this thread now (re: my comments on #475)

**Comment by ashleydraper** [comment]
I lean toward option 2 mainly for aesthetics. But fully recognizing that it does indeed blur the distinction between the state footer and site footer. 
I propose moving forward with option 3 and updating our state footer component to highlight that departments that do not add such link will be out of compliance.

**Comment by m-sullivan7** [comment]
We'll definitely have some documentation edits to make if we go with option 3. I volunteer to take care of them.

**Comment by chachasikes** [comment]
Think we decided this. There is another issue to generally revisit it. Recommend we close this out and pick back up after more user feedback.

**Comment by chachasikes** [comment]
can @jaredwyee or @adam-little  or @m-sullivan7 confirm that this doesn't belong in backlog?

**Comment by m-sullivan7** [comment]
OK to close by me!

**Comment by adam-little** [comment]
We updated the DS website footers based on a decision made in this thread, but we have not updated documentation for the footers.

@m-sullivan7 Do you think we should update the documentation?

**Comment by m-sullivan7** [comment]
Yes. I thought I'd updated the documentation, but that might have been an interim update. I'll create a new issue for that work.
