### ISSUE TITLE
Mail icon on state footer preview is huge

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#430]
Seen on chrome on mac desktop

icon should be same size as other ones

**Comment by aaronhans** [comment]
<img width="954" alt="Screen Shot 2022-01-24 at 1 08 49 PM" src="https://user-images.githubusercontent.com/353360/150865268-8874c1e9-c67d-4bcb-9cf5-d0cf77aa5300.png">

**Comment by xjensen** [comment]
Looks like the SVG mark-up for the mail icon does not have a hard-coded `width` and `height` like the other icons.

**Comment by m-sullivan7** [comment]
This appears to be a duplicate of https://github.com/cagov/design-system/issues/418. Flagging for whoever works on this.
