### ISSUE TITLE
Create spacing utility classes and make better naming conventions

### ISSUE THREAD

**Issue by kkoryaka** [cagov/design-system#439]
- Change these variables names into something more practical and logical. 
- In base-css create spacing utility classes using renamed variables.
![Screen Shot 2022-01-24 at 4 06 24 PM](https://user-images.githubusercontent.com/31669748/150886093-f16b0249-f9fd-4129-b921-363647b34725.png)

**Comment by xjensen** [comment]
I saw someone mention [Open Props](https://open-props.style) in another issue. Their [sizes](https://open-props.style/#sizes) might be a great place to get inspiration for naming.
