### ISSUE TITLE
Skip to the content

### ISSUE THREAD

**Issue by kkoryaka** [cagov/design-system#44]
When keyboard-only users interact with your site they use the tab key to jump from link to link. If you have a lot of links at the first of your page in your header or in a menu, they must tab through those every time they come to a new page just to get to the main content. Providing a skip to main content link allows them to easily bypass this.

---

### Checklist
- [ ] Origin Story
- [x] Requesting agency
- [x] Name
- [x] About this component
- [x] Description
- [x] Examples (ca.gov)
- [ ] Examples (design systems)
- [ ] Features

### Requesting agency
*Who is requesting this component?*
CDT, California State Template development unit

### Origin Story
*What prompted this proposal?*
Having skip to the main content link is accessibility requirement (WCAG 2.4.1)

### Name
*What should we call this component in conversation?*
Skip to the main content

# About this component
*Please tell us more about the component.*
The objective of this technique is to provide a mechanism to bypass header links and main navigation links are repeated on multiple Web pages by skipping directly to the main content of the Web page. The first interactive item in the Web page is a link to the beginning of the main content. Activating the link sets focus beyond the other content to the main content. 

### Description
*Describe how this component will be used.*
When keyboard-only users interact with your site they use the tab key to jump from link to link. If you have a lot of links at the first of your page in your header or in a menu, they must tab through those every time they come to a new page just to get to the main content. Providing a skip to main content link allows them to easily bypass this.

### Examples from ca.gov properties
*(Can be screenshots, a few examples is great. Please include URLs if the examples are live.) This helps everyone understand what you are referring to.*
https://template.webstandards.ca.gov/

### Examples from other design systems
*If this component is commonly found in other design systems, please link to it. This helps everyone understand real-world examples of this idea.*
https://designsystem.digital.gov/

### Features
*Critical features to support initially.*
- Should be first focusable element on the page.
- Should be hidden on initial view but visible on focus.
- Should be linked to the main content tag

---

Thank you!

[Learn more about our review process.](#tbd)

**Comment by chachasikes** [comment]
Nice! 
Super helpful to have some notes on the State's standards to refer to. I'm adding a question on the thread.

Question: This is a small component that would be included in the page layout?
