### ISSUE TITLE
Create social media share graphics

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#441]
When posting links to social media, a thumbnail is automatically generated from the site's metadata.

Let's create the graphics that we want to use as thumbnails.

**Comment by adam-little** [comment]
Example: 
![image](https://user-images.githubusercontent.com/69167298/151048039-57838324-175a-42fb-a136-d530daf64298.png)

**Comment by kmbrlygl** [comment]
Saw this ticket that Chach created that's related to this so linking it here for reference:
https://github.com/cagov/design-system/issues/601

**Comment by Angsv** [comment]
Here is the final illustration for social media: 
![hero_bear_social_image](https://user-images.githubusercontent.com/95935944/154372388-3022c562-4d3f-4187-91b4-c40b77de13b4.png)

**Comment by Angsv** [comment]
@chachasikes I've created a pull request with the SVG code for the image and assigned you to it.
