### ISSUE TITLE
Make Back to top button show up faster.

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#442]
The biggest UX complaint I have so far is scrolling around the site on long pages (desktop or mobile) and needing to go all the way to the bottom for the Back to top button. This has been a consistent UX pain point since cannabis (at least for me).

**Comment by adam-little** [comment]
It appears that the component is not behaving [as documented](https://staging.designsystem.webstandards.ca.gov/components/back-to-top/readme/):

> The button appears when the user has scrolled past the first screen and begins to scroll back up. It disappears after 7 seconds by default. If someone scrolls again, it will reappear. If the user reaches the top of the page at any point, the button will disappear right away.

According to the documentation, it should appear immediately on backscroll (as soon as the user sets the intention of going back up the page, we immediately provide them a shortcut).
 
@kkoryaka Is this how it is implemented? Do you know why it's not behaving this way?

**Comment by m-sullivan7** [comment]
Noting a potential duplicate issue: https://github.com/cagov/design-system/issues/473

**Comment by chachasikes** [comment]
#442 is a duplicate & can be ignored.

**Comment by chachasikes** [comment]
Adding to next sprint with a bunch of other back-to-top improvements.
