### ISSUE TITLE
Navigating between components on mobile is a much pleasurable experience than on desktop.

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#443]
On desktop, clicking component index links feels jarring as it pushes me to the top of the page and my eyes away from the index link I was looking at. On mobile, the component nav is always at the top and accessbile.

**Comment by adam-little** [comment]
Hey @wrendo can you do a screen recording (e.g. Loom) so i can better understand what you are referring to?

**Comment by chachasikes** [comment]
No screen recording. 
Adding to next sprint (accessibility) to figure out what this was about.
