### ISSUE TITLE
iPad: Contact form sizing is way off in profile mode

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#446]
https://drive.google.com/file/d/1XUyXNX7KntnnlBCfIJC9fKHyC4q_eTs6/view?usp=sharing

**Comment by chachasikes** [comment]
The big issue is probably resolved, but could use some fresh reviews.

**Comment by chachasikes** [comment]
This is okay. Marking as done.

**Comment by chachasikes** [comment]
(prior worked resolved this)
