### ISSUE TITLE
iPad: When clicking between Readme and Changelog, the font size and margins change

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#448]
[Profile screenshot 1](https://drive.google.com/file/d/1W35U-IKWpO5jpHsPNqERT_ypIFbfqEUZ/view?usp=sharing)
[Profile screenshot 2](https://drive.google.com/file/d/1Lf1M4D2zpjVJlP3W6tukYjslWeCBl0np/view?usp=sharing)
[Landscape 1](https://drive.google.com/file/d/1_ndBH1rM1tmuZadZ38Yke2mOOM1WFPYv/view?usp=sharing)
[Landscape 2](https://drive.google.com/file/d/1obw4ht7juIsgjSgcbO7zaPYIti5AknQp/view?usp=sharing)

**Comment by xjensen** [comment]
I'm unable to recreate this bug. Two possibilities come to mind.

1. The observed problem was actually related to our poor heading hierarchy on the Changelog pages, which we've now fixed.
2. This is some artifact of the responsive font changes we made to the Design System about a month ago. But I'm not seeing that right now.

**Comment by chachasikes** [comment]
I can't recreate this either. Your explanations make sense @xjensen.
Marking as Done & closing.
