### ISSUE TITLE
iPad: Statewide footer external icon link get pushed to 2nd row

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#449]
https://drive.google.com/file/d/1t0-276WxF9mwdr938b0sUrq8COHNaktR/view?usp=sharing

**Comment by m-sullivan7** [comment]
@kkoryaka Out of curiosity, did this QA bug get fixed with your other work on the statewide footer?

**Comment by kkoryaka** [comment]
@m-sullivan7 Unfortunately, i can't view the issue, so I can't say if I fixed it or not.
![Screen Shot 2022-02-08 at 4 47 41 PM](https://user-images.githubusercontent.com/31669748/153100757-0eb2eedd-0e6c-4dd0-95a1-42fa4384aa0b.png)

**Comment by m-sullivan7** [comment]
Here's the original image:

![image](https://user-images.githubusercontent.com/69169190/153101416-fcf35275-7e64-4286-a810-07a6e09de8da.png)
