### ISSUE TITLE
iPhone: Home page form anchor link wrong after clicking submit

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#452]
https://drive.google.com/file/d/1Kv7kMlHWla2uPCAJd9VqhBDd6tZ5K3Qi/view?usp=drivesdk

**Comment by chachasikes** [comment]
Not sure exactly the issue (which anchor link) - but assume there is a mismatch in IDs somewhere. Will hunt down whatever this issue is.

**Comment by chachasikes** [comment]
Whoops this one got lost in last sprint.

(The video is also in the trash now)

I understand this issue now. On iPhone there is a jump after submission - it may have to do with losing the form ID - but a chance it's something else (scrolling related)

There is an ID on the <form> element that's used for the web component - that's necessary - but it needs some transition love so users won't get lost. (Sorry folks!)
