### ISSUE TITLE
Contact Us page: Git links don't match

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#453]
In the "Get support from developers" section, the GitHub link takes me to a sign-in page. But when I click the GitHub link in the footer I go to GitHub without needing to sign in. I'd expect those two links to take me to the same place.

**Comment by chachasikes** [comment]
Was trying to link straight to the issues page, but - if you are logged out of github it will require a log in which will be disorienting to anyone less used to using Github. 

[Issues page](https://github.com/cagov/design-system/issues/new/choose)

Switching the link just point to the repo.
