### ISSUE TITLE
General: All ca.gov links should not be links

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#460]

**Comment by m-sullivan7** [comment]
@kkoryaka taught me that `CA&#46;gov` will make the text not be formatted as a link. I'm picking up this issue to review the whole Design System site to find and replace this text since an engineer is not required to do this work.

**Comment by m-sullivan7** [comment]
@kkoryaka I used this fix on the [About page](https://designsystem.webstandards.ca.gov/about/#history) and the [Visual design page](https://designsystem.webstandards.ca.gov/style/design/#color), but in both instances it's still coming up as a linked CA.gov. Any idea why it's not working here?

**Comment by kkoryaka** [comment]
I see what you are saying @m-sullivan7 . I don't know why it's working on one page and doesn't on another. Here is other alternative that that works on both pages CA<span>.</span>gov. So, you pretty much enclosing period into span tag.

**Comment by m-sullivan7** [comment]
This worked like a charm! Thanks @kkoryaka ! I'll take it from here. 🙂

**Comment by m-sullivan7** [comment]
I've reviewed the Design System site for all instances of CA.gov and have used the `<span>` tag to change them so they're no longer creating links. This issue is done.
