### ISSUE TITLE
A different approach page index link not work for "Use your..."

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#463]

**Comment by m-sullivan7** [comment]
This is potentially due to the presence of a comma in the H2 that isn't working. This could be solved in one of two ways:

- Rewrite the H2 to not include the comma
- Engineering fix to support the use of punctuation marks in the page navigation

This decision will also likely affect https://github.com/cagov/design-system/issues/462

**Comment by chachasikes** [comment]
Thanks Michael . There is support already for punctuation handling.
* I'll check that comma is included in that list.

There may be another issue if you had been testing on Windows - the prefers motion accessibilty option may be in effect on those devices. I'm working on that.

**Comment by m-sullivan7** [comment]
Cool! Based on what I see in https://github.com/cagov/design-system/issues/462, question mark should probably be added too. Thanks!

**Comment by chachasikes** [comment]
I tracked down what was going on here. Sharing some notes on this thread.

* The build converts the markdown h2 to "<h2 id="use-your-preferred-framework%2C-or-none-at-all" tabindex="-1">"
* This string was re-encoded back to commas, which conflicted with how the h2 titles got converted to anchor links
* The outliner also needed an adjustment to the logic on when and how the existing id elements were pulled in.

Context:
For our anchor tags, I decided to strip punctuation and special characters. In the code you can see the two RegEx expressions. 
* One that removes special characters that are not allowed by the Selector API, and 
* Another that limits the characters to those in the UTF-8 non-special character ranges for English and other languages.

When originally working on this, had some plans to build multilingual test cases, that will still be helpful.

For now, will continue with this plan of stripping out commas and special punctuation for the anchor links.
