### ISSUE TITLE
iPhone: Sometimes Back to top button doesn't work

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#464]
Sometimes it only brings up the browser action footer for Safari instead of taking user to the top of the page.

**Comment by zakiya** [comment]
@yesenia-gtz  I cannot reproduce this. I think this can be closed.

FYI - if this comes up again, I would suggest the reporter use the [Bug Report Template](https://github.com/cagov/design-system/issues/new?assignees=&labels=Bug&template=01-bug-report.md&title=Bug%3A)
