### ISSUE TITLE
iPhone: Site header component example search box issue

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#465]
On mobile the search box appears outside of the example at the top of the component page under the main site header.

**Comment by wrendo** [comment]
https://drive.google.com/file/d/1FtNYab6W7dSETBfkswaUkG5I5QImBEke/view?usp=sharing

**Comment by chachasikes** [comment]
@zakiya will figure out what needs to happen for this

**Comment by zakiya** [comment]
Looks like this bug was fixed. Closing.
![IMG_31A6C1273393-1](https://user-images.githubusercontent.com/915352/158270974-d0236444-7e28-47ae-b563-a50f3ee65ef9.jpeg)
