### ISSUE TITLE
Site navigation - Demo fixes

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#466]
At small screen sizes, the menu link doesn't work. 

![CleanShot 2022-03-14 at 15 05 12](https://user-images.githubusercontent.com/915352/158268854-1b6111d3-9454-4626-a368-8ab16293e425.gif)

At medium screen sizes, the menu overlaps the border.

<img width="479" alt="CleanShot 2022-03-14 at 15 06 37@2x" src="https://user-images.githubusercontent.com/915352/158269029-0765d47a-8e04-4582-a141-d45415140d76.png">

**Comment by chachasikes** [comment]
@zakiya will add a description about what this is

**Comment by zakiya** [comment]
Description added. Moving to backlog.
