### ISSUE TITLE
iPhone: Components menu arrow should point right when not open

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#468]

**Comment by adam-little** [comment]
Components menu closed:
![image](https://user-images.githubusercontent.com/69167298/151226271-8ee7275d-c6e5-4cf2-a052-0e027d858934.png)

Components menu open:
![image](https://user-images.githubusercontent.com/69167298/151226310-fcf89ec7-82c0-4c4b-80a3-a1d5db95efca.png)

When open, it uses the same "Close" icon as the site menu.

**Comment by xjensen** [comment]
#636 partially addresses this issue. We still need to add the "X" icon when the menu is open, so leaving this open.

**Comment by jaredwyee** [comment]
@xjensen given this is partially fixed, can you update the title/description to better reflect what is addressed here vs the the new issue #640?

Thanks.

**Comment by zakiya** [comment]
QA result: The first part of the issue which is addressed in the title is complete. #640 correctly identifies the second issue. Ready to merge/close.
