### ISSUE TITLE
General: Need improved alt text for images and component icons

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#470]
See QA spreadsheet for feedback

https://docs.google.com/spreadsheets/d/1Q8HZTOdiDB2Yu5MNbriOu-tN7iUWKkjNXDVM3Uqn-BY/edit#gid=75411241

We use images in several places on the Design System site:

- Homepage
  - Hero bear
  - _What's in the Design System_ card images that use circles
  - Principle rotator circles
  - _Be part of the Design System_ circles
  - _Who's using the Design System_ example screenshots
- Components main page
  - Component icons
- Social media sharing
  - The shape of California in white against a black background
 
These images need to be considered through the lens of accessibility. We have two options:

- Create alt text
- Mark images as decorative

W3C has guidance about what constitutes:

- [Informative images](https://www.w3.org/WAI/tutorials/images/informative/), which "convey a simple concept or information that can be expressed in a short phrase or sentence. The text alternative should convey the meaning or content that is displayed visually, which typically isn’t a literal description of the image." If we decide an image is informative, there are varying levels of detail we can use for the alt text.
- [Decorative images](https://www.w3.org/WAI/tutorials/images/decorative/), which "don’t add information to the content of a page" and do not require alt text. They are marked as decorative to tell screen readers that the images are decorative and have no content.

**Comment by jaredwyee** [comment]
@m-sullivan7 kindly will lay out options for how we might proceed. Then we ask teammates with accessibility backgrounds to assess them -> make decision (PM if needed can tip scale if we don't have clear consensus).

**Comment by chachasikes** [comment]
@m-sullivan7  - can you include the social media graphic on this list - there is a way to add alt text for it - not sure we've tried or tested it yet - but I made notes on this here: on https://github.com/cagov/design-system/issues/601

**Comment by m-sullivan7** [comment]
I updated the description of this ticket with the issue at hand (alt text vs decorative) and some guidance on how we can make the decision.

Here's my take for each of the images:
- Homepage
  - Hero bear - I think this an **informative image**. The key decision to make is what level of detail we want to go to. Tiffany suggested a very extensive description, while Christian and I came up with shorter ones.
  - _What's in the Design System_ card images that use circles - I think they are **decorative images**. They do not add to the understanding of the concepts they're associated with.
  - Principle rotator circles - I think this is a **decorative image**. It does not add to the understanding of the principles.
  - _Be part of the Design System_ circles - I think this is a **decorative image**. It does not add to the feedback form.
- Components main page
  - Component icons - I think these are mostly _informative images_ in that they often show what a component looks like (in the abstract) or where it sits. Tiffany had mentioned when bringing the issue up that this information could be included in the existing description, but I think that could be duplicative for people who use the site without a screen reader.
- Social media sharing
  - The shape of California in white against a black background - I think this is a decorative image...but I also know that social media is often underserved by alt text in general. That might make it valuable for us to include alt text as a way of showing that we think about this use case. I'm unsure which way to go on this one.

While I know how to create good alt text, I'd appreciate getting the opinion of someone with a deeper accessibility skill set, like Tiffany, to talk about when to call something decorative. I would also benefit from their perspective on what level of description to include in alt text when we use it (the hero bear would be a good way to discuss this). 🐻 

@jaredwyee Is there anything else I can add to this issue to help the team consider it?

**Comment by jaredwyee** [comment]
Thanks @m-sullivan7. I agree with your assessment. Re social media, I think something describing the CA design system (similar to the hero blurb) is prefered over describing the black CA "logo" or if it was the sitting bear with circles.

Noting there was also input from Tiffany on the alt text of the cannabis and covid19 site preview images:

1.	Accessible name: cannabis.ca.gov website homepage
Updated name: screenshot of the Department of Cannabis Control’s homepage: cannabis.ca.gov
2.	Accessible name: covid19.ca.gov website homepage
Updated name: screenshot of the Covid19.ca.gov website homepage

**Comment by m-sullivan7** [comment]
You're right--I forgot about those! I would call both those screenshots **informative images** and add alt text for them.

**Comment by chachasikes** [comment]
Tagged all social media issues with "Social media"
https://github.com/cagov/design-system/labels/Social%20media

**Comment by chachasikes** [comment]
See Luke Fretwells comment as well: https://www.metatags.org/all-meta-tags-overview/the-important-meta-tags/social-media-metatags/

**Comment by xjensen** [comment]
Removing my assignment here because I've been working on other things for months. Happy to assist as needed.

**Comment by chachasikes** [comment]
Chatted with Ashley.

Ashley will write ALT text for the bear image.
Chach pinged @kmbrlygl about the PNG file rendered in the correct aspect ration.


The goal is *to create clear guidance on adding accessible social media cards for any ca.gov website page on the Design system, working according to current social media URL specs.* 

Since we have documentation in a few different places, we discussed writing consolidated guidance in possibly a June sprint & coordinating with DS team and @yesenia-gtz. 

The tooling on the engineering site is already complete & heavily worked on & in alignment with Luke's comment. We have a schema for front matter and our 11ty systems will render OG & meta tags correctly for all platforms. 

There is currently non-descriptive alt text that says "California Design System" for an image of boundaries of California. This is incorrect/undesirable. We will replace it with updated content & a process for updating social card content.

**Comment by chachasikes** [comment]
Wrong thread - moving my comments.

**Comment by ashleydraper** [comment]
FYSA- here is the proposed alt text for the homepage bear image from Tiffany:

_The State of California grizzly bear is shown sitting with four circles surrounding his body in the colors yellow, blue, orange and green. Each color represents various colors you see in nature. An Abstract swirl connects the colors behind him representative of connecting the Design System to meet Californian’s needs._

Based on some industry best practices on character count and info needed in the description, here is what I'm proposing:

![image](https://user-images.githubusercontent.com/62437425/166590857-231ceb2a-4fe6-4d1c-95f7-a613b6667345.png)

Text: _The brown State of California grizzly bear is seated and surrounded by four circles. The circle colors are yellow, blue, orange and green representing various colors you see in nature. An abstract swirl connects the colors behind the grizzly bear._

Cc: @chachasikes

**Comment by chachasikes** [comment]
Suggestion: consider having a content captain (or ranger) - for each sprint - to make sure that any new images have alt text.

**Comment by chachasikes** [comment]
We may need to review the original google doc from January since we have new content.
