### ISSUE TITLE
Accordion page "Used on" section content doesn't make sense or read well

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#472]

**Comment by m-sullivan7** [comment]
I propose moving the heading information to the bottom of the section and updating the content to read as follows:

> Write a heading that is brief and descriptive. People will use the heading to decide if they should open the accordion. Headings can be a:
> - Word or phrase
> - Sentence
> - Question

I am gathering content designer feedback on this suggested draft.

**Comment by m-sullivan7** [comment]
Published edits.
