### ISSUE TITLE
Component changelog header texts don't always match

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#477]
See examples:

https://drive.google.com/file/d/1FeI2MmCDOiWI68BRJXI0cnNg4rDMiC0G/view?usp=sharing

https://drive.google.com/file/d/1E9jJgCU1B9nw1A3B89ZJzaP3ZV-Qhod8/view?usp=sharing

Should the really long ones be shortened?

**Comment by xjensen** [comment]
You could go ahead and do it if you like. We already have some of these changes in the project to rename components, #602.

**Comment by m-sullivan7** [comment]
Sounds good! I'll use that PR to make sure I don't duplicate work.

**Comment by m-sullivan7** [comment]
I updated the headings for the changelogs not listed in https://github.com/cagov/design-system/pull/602. I'm handing the assignment back to @xjensen to oversee the ones in #602.

**Comment by m-sullivan7** [comment]
Remaining changes made in https://github.com/cagov/design-system/tree/1.0.1-rc-post-launch-fixes. This issue will remain open until that branch is merged.

**Comment by jaredwyee** [comment]
Confirmed that no reference to version is in header for change log pages on https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/components/back-to-top/changelog/

**Comment by m-sullivan7** [comment]
Published with branch. Closing issue as done.
