### ISSUE TITLE
Link grid example links all go to 404s

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#480]
[Link grid page](https://designsystem.webstandards.ca.gov/components/button-grid/readme/) for reference (added by Michael).

**Comment by m-sullivan7** [comment]
@aaronhans I will talk about better content and links for this with the content team in Slack. Feel free to hand assignment to me while I do so.

**Comment by m-sullivan7** [comment]
I've updated these links with `#` dummy links and improved the text of each link. This issue is complete.
