### ISSUE TITLE
Site header component page example search bar goes to 404 when testing

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#485]

**Comment by aaronhans** [comment]
We don't have site search implemented yet.

We are showcasing a couple versions of the header code one of which has search. We could create a page saying search is not yet created on designsystem.webstandards.ca.gov yet but we do have a sitemap.... Is that a helpful interim fix @wrendo?

**Comment by xjensen** [comment]
@aaronhans I believe this is a reference to the search box that appears in the demo on our site-header page.

I put in a fix for this at #554.

<img width="831" alt="Screen Shot 2022-01-26 at 14 08 47" src="https://user-images.githubusercontent.com/1208960/151255919-8c0e8016-98b3-40d8-b972-50f212f24de2.png">

**Comment by wrendo** [comment]
@aaronhans see @xjensen comment above. Sorry for any confusion
