### ISSUE TITLE
Mobile: Principles page hyperlink formatting issue

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#491]
https://drive.google.com/file/d/1gygsZILKNpPBt9XprjlEe1uCxmSTXzWG/view?usp=sharing

Where hyperlinks overlap on adjacent lines, the underline doesn't continue on the top hyperlink. Additionally, the period seems disconnected from the word it should be attached to

**Comment by zakiya** [comment]
https://designsystem.webstandards.ca.gov/principles/
iOS and and MacOS Safari

**Comment by zakiya** [comment]
@adam-little and @kkoryaka I want to get your opinion on this. 

- The reported issue only seems to affect webkit browsers (Safari on iOS and macOS, Firefox). 
- I can fix it by removing `text-underline-position: under;` from the <a> tag globally. 
- There's no way I know of to reliably/responsibly target webkit browsers across screen sizes.

with under (Webkit)
![CleanShot 2022-02-01 at 17 45 30](https://user-images.githubusercontent.com/915352/152080582-0c8dd24e-9bc6-453d-8986-a53a97cc127e.png)
![CleanShot 2022-02-01 at 17 47 41](https://user-images.githubusercontent.com/915352/152080745-397f98d0-0254-4ea0-8bb8-79fd9754b077.png)

with under (Chrome)
![CleanShot 2022-02-01 at 17 50 15](https://user-images.githubusercontent.com/915352/152080963-516c1b7b-8629-43a9-8230-378e3e7a8b41.png)


without under (Webkit)
![CleanShot 2022-02-01 at 17 46 15](https://user-images.githubusercontent.com/915352/152080622-b73c9448-232a-498a-b125-cfcb68fe2f42.png)

![CleanShot 2022-02-01 at 17 46 46](https://user-images.githubusercontent.com/915352/152080664-3911859d-583c-4da0-be74-205c24386ea4.png)

without under (Chrome)

![CleanShot 2022-02-01 at 17 51 06](https://user-images.githubusercontent.com/915352/152080996-daa07196-6753-4ed6-af8b-d7afa957a6d6.png)


Should we:

a) Leave as is (with under)
b) Remove the `text-underline-position: under;` declaration
c) Something else

**Comment by adam-little** [comment]
I'll defer to @kkoryaka. I don't understand the implications of removing the declaration.

**Comment by zakiya** [comment]
The declaration changes the position of the line under the link. With it, the line goes under letters like g and y. The  first three screen shots are with the declaration, the last three screenshots are without.

**Comment by adam-little** [comment]
Got it! I don't see any problem with removing it.

**Comment by kkoryaka** [comment]
Definitely remove text-underline-position: under;.

**Comment by zakiya** [comment]
Code merged. Closing issue.

**Comment by kkoryaka** [comment]
@jaredwyee Looks good in mac chrome 
![Screen Shot 2022-02-09 at 11 57 33 AM](https://user-images.githubusercontent.com/31669748/153280353-cdf31031-e038-4ee2-804d-aa73ca35e78a.png)

https://644-fix-changelog-layout.pr.designsystem.webstandards.ca.gov/principles/
