### ISSUE TITLE
Pixel 3a on Firefox: Feature card example has a lot of extra space

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#492]
https://drive.google.com/file/d/17b-tvyKwzMfRshM5gnXU1b4sUCdE6EiF/view?usp=sharing

**Comment by m-sullivan7** [comment]
@yesenia-gtz I originally reported this issue in the launch QA. I took a look again and found that the extra space I saw is no longer there. It looks like we fixed this and can close this issue. I'll give you the honor of doing so!
