### ISSUE TITLE
Mobile: Regulatory outline fixes

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#493]
Mobile: Regulatory outline example missing border where bullet point starts

https://drive.google.com/file/d/1ynaFnFp60CKi0HEWDQRL9dDmJ8p87Mil/view?usp=sharing

Mobile: Regulatory outline example level 3 and level 4 bullet content formatting issues

https://drive.google.com/file/d/1bjFXrv3Qofofgq0ODLJC5fR0nHlksxev/view?usp=sharing

https://drive.google.com/file/d/13crlW0bB5k0njyXCCv99bndQD0mxOfMS/view?usp=sharing

**Comment by chachasikes** [comment]
@zakiya can you look at this one?
