### ISSUE TITLE
Mobile: Regulatory outline example level 3 and level 4 bullet content formatting issues

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#494]
https://drive.google.com/file/d/1bjFXrv3Qofofgq0ODLJC5fR0nHlksxev/view?usp=sharing

https://drive.google.com/file/d/13crlW0bB5k0njyXCCv99bndQD0mxOfMS/view?usp=sharing

**Comment by chachasikes** [comment]
@zakiya do you want to look at this one?

**Comment by zakiya** [comment]
Closing. Moving all details to #493 since they can all be fixed together.
