### ISSUE TITLE
Visual design style guide missing hyperlink in first paragraph

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#499]

**Comment by m-sullivan7** [comment]
@adam-little or @kmbrlygl if you know what and where the missing link is, I'd be happy to add this to you. I'll be editing a few other pages, so it's no trouble for me to do it while I'm in the code.

**Comment by adam-little** [comment]
@m-sullivan7 The first sentence on the [Visual design style guide](https://staging.designsystem.webstandards.ca.gov/style/design/)  should link to https://staging.designsystem.webstandards.ca.gov/principles/

**Comment by m-sullivan7** [comment]
Thanks Adam! I will fix after the presentation with Amy. (I will use a relative link so that it only goes to staging if someone's on the staging site unless I hear otherwise.)

**Comment by m-sullivan7** [comment]
The code appears to be right in markdown. If I remove the `text-lead` class it works. I think the class is interfering with the markdown behaving appropriately.

@xjensen Is the fix for this to use HTML formatting for the link and switch to `<a href="/principles/">Design System principles</a>`?

**Comment by xjensen** [comment]
@m-sullivan7 That's correct. As soon as you wrap that paragraph in the `<p class="text-lead">` tag, the markdown processor will assume it's complete HTML and ignore it completely. Your suggested fix, using the `<a>` tag, should do the trick.

**Comment by m-sullivan7** [comment]
It did indeed! Closing this issue as done after confirming the fix worked. Thank you Jon!
