### ISSUE TITLE
Content style guide "Write in an official..." Voice checklist section is messy. Make a table?

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#500]
https://drive.google.com/file/d/1x0asU72L_nTmPqAMgdFMXir2DS8eAoQA/view?usp=sharing

**Comment by m-sullivan7** [comment]
I will review this to see if we're using similar formatting to other tables on the site that are working.

**Comment by m-sullivan7** [comment]
It turns out I was missing one crucial fotmatting piece in markdown. I added it and the table now displays properly.
