### ISSUE TITLE
Changelog titles should be H2

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#501]
https://drive.google.com/file/d/1xT0-pHKCmj7Ky3AjNghQrfYi8_O7y4mH/view?usp=sharing

**Comment by m-sullivan7** [comment]
I could pick this issue up too since I'll be in most of the changelogs.

**Comment by m-sullivan7** [comment]
I added H2s to all the changelogs, except for those in #602. I'm handing this issue back to @xjensen to see the remainder through.

**Comment by m-sullivan7** [comment]
Remaining changes made in https://github.com/cagov/design-system/tree/1.0.1-rc-post-launch-fixes. This issue will remain open until that branch is merged.

**Comment by jaredwyee** [comment]
Changelog headers look good in https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/
