### ISSUE TITLE
Home page "What's in the..." cards need rounded corners of 5px

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#503]

**Comment by adam-little** [comment]
Staging site (Chrome): 
![image](https://user-images.githubusercontent.com/69167298/151223455-6b18593d-2709-4a03-8ffa-4bc639a61a91.png)

Figma (preferred style):
![image](https://user-images.githubusercontent.com/69167298/151223506-5c05a461-4f54-448e-93ec-a70e0619ec06.png)

https://www.figma.com/file/A1DSo765cWjvBWoLd6tvEE/DS-website-screens?node-id=0%3A1
