### ISSUE TITLE
Forms missing dropdown arrows

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#504]

**Comment by adam-little** [comment]
Please use arrow style[ in Figma](https://www.figma.com/file/A1DSo765cWjvBWoLd6tvEE/DS-website-screens?node-id=0%3A1)
![image](https://user-images.githubusercontent.com/69167298/151220465-458d87a7-5cc8-4cd2-91f3-38a9ba43b66b.png)

Note this is the same arrow icon that is used in the main site nav.

**Comment by adam-little** [comment]
Arrow icon also needs to be fixed on https://staging.designsystem.webstandards.ca.gov/contact-us/

**Comment by chachasikes** [comment]
Got an arrow in an upcoming branch/PR.

Minor issues:
* Getting arrow to be flush right - not sure what margin or other css it's inheriting, so need to suss that out.
* Using an inline SVG - but wondering if @kkoryaka would want to make this arrow CSS only as well. 

I'll submit the PR tomorrow
