### ISSUE TITLE
Submit button color should be "highlight" color

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#506]
Submit button should be highlight color so that it's highlight state is different than background color

**Comment by adam-little** [comment]
Staging site:
![image](https://user-images.githubusercontent.com/69167298/151223138-baab796b-5f16-41af-bace-4f45bf7232f8.png)

Figma (desired color):
![image](https://user-images.githubusercontent.com/69167298/151223190-df69e04e-31ff-4db0-9aad-3ef7cfca7726.png)

**Comment by chachasikes** [comment]
Waiting on hover text color for low contrast primary color dark + blue text

**Comment by jaredwyee** [comment]
Confirmed working in release branch. Closing. Will be moved to Done once release merged tomorrow.
