### ISSUE TITLE
Submit button: Mouse hover state doesn't change

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#507]

**Comment by adam-little** [comment]
On Chrome, my cursor remains an arrow when i mouse over the Submit button the homepage. It does not change to the pointed-finger.

**Comment by adam-little** [comment]
This is related issue for the same button: https://github.com/cagov/design-system/issues/506

**Comment by jaredwyee** [comment]
Confirmed working

**Comment by chachasikes** [comment]
Did we confirm this is all good?

**Comment by adam-little** [comment]
Looks good to me. Note we have a separate issue focused on standardizing button behaviors -  hope to have the design for this finalized soon: https://github.com/cagov/design-system/issues/662
