### ISSUE TITLE
External link icons not vertically centered to links.

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#509]

**Comment by adam-little** [comment]
Currently, in Chrome, the icon looks higher than the line height:
![image](https://user-images.githubusercontent.com/69167298/151222410-bae3bcc4-3e74-4025-aad7-035c471776dd.png)

Ideally, the icon is better aligned to the text. Here is how it looks in Figma:
![image](https://user-images.githubusercontent.com/69167298/151222558-b4328cee-b15a-4c61-a048-7cd828fbd862.png)

**Comment by adam-little** [comment]
@kkoryaka I am noticing the icon on the website is different than the icon in Figma.

Is the icon on the website from the state icon font? If so, can you provide me an SVG so that I can incorporate it into Figma?

**Comment by kkoryaka** [comment]
![external-link](https://user-images.githubusercontent.com/31669748/152060415-001d247f-fbbc-42b7-82d6-e41266011f44.svg)
Here you go @adam-little

**Comment by zakiya** [comment]
Figma: https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/?node-id=0%3A1 Frame 170

**Comment by zakiya** [comment]
This is merged. Closing issue.

**Comment by jaredwyee** [comment]
Confirmed fixed  https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/principles/
![image](https://user-images.githubusercontent.com/85529382/153266386-37618abe-d157-45f6-a617-0374f476d15b.png)
