### ISSUE TITLE
Desktop Firefox: Site horizontal width seems to extend too far

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#512]
https://drive.google.com/file/d/1w1nsnt7yppCllZRW6PHBeRGHEmHA4fom/view?usp=sharing

**Comment by kkoryaka** [comment]
This is caused by full-bleed class width property of `width:100vh`.... When Changed to 99vw the issue is gone. I wonder if changing width to 99vw will cause other issues.

**Comment by kkoryaka** [comment]
![Screen Shot 2022-01-26 at 12 41 35 PM](https://user-images.githubusercontent.com/31669748/151244391-b41769c5-aeb9-4711-9b91-16a9a7513919.png)

**Comment by kkoryaka** [comment]
or we simply can  hide overflow-x on the body and call it a day.     body {overflow-x: hidden;}
