### ISSUE TITLE
Site header component: Do we need 2 header examples?

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#515]

**Comment by aaronhans** [comment]
Assigning to @jaredwyee for decision

**Comment by m-sullivan7** [comment]
@xjensen Based on this morning's conversation, alerting you to another example of where we may have more demo than we need.

**Comment by xjensen** [comment]
We could use the oft-neglected Use Cases tab to show different uses of a component. 

I think we definitely need to show both examples (with and without a logo). We're already supporting that in production between Drought and Cannabis.

**Comment by m-sullivan7** [comment]
You're right--we definitely want those use cases. I could keep the demo as is or move one (I'd recommend the no logo version) to the use case tab. That might be a strategic decision, so I'm interested in @jaredwyee 's thoughts.

**Comment by chachasikes** [comment]
pinging @jaredwyee for a decision

**Comment by m-sullivan7** [comment]
@yesenia-gtz I think that this is a you decision now instead of Jared. My recommendation is to close this issue. We do need both header examples and probably don't want to put the development work into creating a use case tab for the page at this point. (But others correct me if I'm wrong!)
