### ISSUE TITLE
Base CSS changelog: Inconsistency in "ca.gov" vs" "CAGov"

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#518]

**Comment by chachasikes** [comment]
Left question for content team on what the preferred version should be

**Comment by m-sullivan7** [comment]
I am checking with our CDT partners for the preferred version. @chachasikes would you like me to take this ticket? It's a pretty easy change to make and that way you can use your time for other things. Ditto for https://github.com/cagov/design-system/issues/516

**Comment by m-sullivan7** [comment]
Per CDT, the preferred convention is `CA.gov`.

**Comment by m-sullivan7** [comment]
Content updated and published.
