### ISSUE TITLE
Accordion changelog: 2.0.6 content is "@TODO find old notes"

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#520]

**Comment by aaronhans** [comment]
Fixed here https://github.com/cagov/design-system/pull/556

**Comment by jaredwyee** [comment]
Confirmed no longer present  https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/components/accordion/changelog/
![image](https://user-images.githubusercontent.com/85529382/153273807-84c624fa-1ad0-43d5-ad59-be3201737dfc.png)
