### ISSUE TITLE
Feature card example: Do we want a working button in the demo?

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#521]
Goes to a page on cannabis. Do we want this? Could just be a non-functioning button

**Comment by m-sullivan7** [comment]
In other demos we've changed out links to `#` so they don't take people outside the Design System site and the link isn't that important itself. I'd be happy to make that change here.

**Comment by m-sullivan7** [comment]
@chachasikes Would you like me to implement the `#` solution? If so, I'll take this ticket and get it off your plate. 🙂

**Comment by chachasikes** [comment]
@m-sullivan7 sure!

**Comment by m-sullivan7** [comment]
Link updated and live!
