### ISSUE TITLE
Step List - step 3 has a mailto link in it. Do we want to remove?

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#523]

**Comment by zakiya** [comment]
@wrendo Where is the link? Screenshot?

**Comment by m-sullivan7** [comment]
Two options for addressing this:

- Remove the hyperlink
- Make the link `#` (our solution in other demos with regular hyperlinks)

I vote for the `#` solution.

**Comment by m-sullivan7** [comment]
Interpreting @aaronhans's assignment to me as agreement with my vote, I've updated the link to use `#`. It's easy to change back if I misinterpreted. 🙂
