### ISSUE TITLE
Base CSS changelog: Versions do not descend regularly.

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#525]
It starts with 1.0.4 and then moves to 1.0.13

**Comment by kkoryaka** [comment]
The latest [PR](https://github.com/cagov/design-system/pull/498) fixing it.

**Comment by aaronhans** [comment]
Fixed on live site

**Comment by aaronhans** [comment]
Assigned to @jaredwyee for review

**Comment by jaredwyee** [comment]
Assuming this is good based on from https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/components/base-css/changelog/
![image](https://user-images.githubusercontent.com/85529382/153265096-82d13b46-3582-4536-a69c-a751095a9b41.png)
