### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#526]
Please see any issue labeled "accessibility" in the "Windows desktop Chrome" and "Windows desktop Firefox" tabs in the QA sheet. 

Triage into single issues as necessary after discussing on how to approach accessibility QA.

https://docs.google.com/spreadsheets/d/1Q8HZTOdiDB2Yu5MNbriOu-tN7iUWKkjNXDVM3Uqn-BY/edit#gid=696506953

**Comment by chachasikes** [comment]
Updated and moved to Github
