### ISSUE TITLE
Changelogs have extra text at the top

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/design-system#527]
The changelogs for components have what looks like some kind of tag or extra text beneath the component stage tracker. Here's an example from [statewide footer](https://designsystem.webstandards.ca.gov/components/statewide-footer/changelog/):

![image](https://user-images.githubusercontent.com/69169190/151205337-e297a6f5-c324-4a24-8ef4-c323ab85633a.png)

It doesn't seem to add any value.

**Comment by m-sullivan7** [comment]
If this is as simple as just removing that blurb from the changelogs, I'm happy to take this issue @xjensen.

**Comment by m-sullivan7** [comment]
I removed the text in the changelogs, except for those in #602. I'm handing this to @xjensen for the remainder of that work.

**Comment by m-sullivan7** [comment]
Remaining changes made in https://github.com/cagov/design-system/tree/1.0.1-rc-post-launch-fixes. This issue will remain open until that branch is merged.

**Comment by jaredwyee** [comment]
Confirmed tag is not visible on https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/pr/1-0-1-rc-post-launch-fixes/components/statewide-footer/readme/ and did not notice any for other components
