### ISSUE TITLE
Improve content navigation UX

### ISSUE THREAD

**Issue by kmbrlygl** [cagov/design-system#529]
Two-related issues:
- [ ] Make content navigation for longer sections sticky (e.g., Visual Design Style Guide) or maybe a default?
- [ ] Hide content navigation when content is short 

Ehb mentioned these issues have been brought up before so maybe we need to discuss first

**Comment by adam-little** [comment]
For item #1, we have an open issue here: https://github.com/cagov/cannabis.ca.gov/issues/234

For item #2, I think this should be up to the discretion of the content editor.

**Comment by yesenia-gtz** [comment]
@kmbrlygl  have we validated if this UX recommendation would be an improvement to implement? @extinah This would  be a good candidate for testing with user.

**Comment by kmbrlygl** [comment]
No, we have not. Agree it would be something good to test.  

@Courtney-Chittock has brought up in a conversation that this is also an accessibility issue

**Comment by Courtney-Chittock** [comment]
Thanks @kmbrlygl!

Perhaps not _technically_ an accessibility issue, but definitely a usability issue that would negatively impact people with physical disabilities.

We might also want to look at vertical positioning and hover effects.
