### ISSUE TITLE
Issue: Print preview not optimized 

### ISSUE THREAD

**Issue by chachasikes** [cagov/design-system#531]
From QA notes: "Print preview - whole thing can be scaled down to print on less pages (on 9 pages).
The featured principle - text and image extremely large."

**Comment by chachasikes** [comment]
Print preview notes:
- Yes, it is 9 pages long. I think this request is more about saving paper & being more economical.
- I believe someone requested a printable version of the website already. 
Would love to understand more about this use case. @sarah-letson  
Especially because of our content: we are including principles and other useful information. 
* Print mode is how one can create a PDF to read later.
* A print-out may have some use on a team or other organizing methods some folks might be trying to use in order to do their jobs. 
* A print-out could be about accessibility (or something else)

- Accessibility issue: Feature card on light background (print) - has light grey text in print version cc @kkoryaka 
<img width="572" alt="Screen Shot 2022-02-09 at 9 30 49 AM" src="https://user-images.githubusercontent.com/149436/153256788-504493dc-3a2b-4178-8c43-fdbfe5b7789f.png">
- Some of the page-breaks could use some love (like not breaking in the middle of an image)

- @adam-little Think this needs to go back to you before we rebuild the print styles.

Q:
Sometimes it's helpful to suppress the footer on a print-version. Depending on the use case for the print version, do we have a recommendation?

Attaching PDF of Principles page.

[Principles _ California Design System.pdf](https://github.com/cagov/design-system/files/8034940/Principles._.California.Design.System.pdf)

**Comment by chachasikes** [comment]
@jaredwyee @aaronhans Moving this to next sprint, where this may need a design review.

**Comment by jaredwyee** [comment]
@extinah can you clarify if printing a page of the site is an accessibility factor? Otherwise, I'm inclined to say this is 'Won't do'.

**Comment by chachasikes** [comment]
msg'd @extinah on Slack

**Comment by extinah** [comment]
@jaredwyee  @chachasikes  Not a wcag accessibility issue. Depending on how you handle links (like URLs displaying), there could improvements made there. Otherwise it's a usability issue.

**Comment by jaredwyee** [comment]
@extinah got it, thanks for clarifying. 

@chachasikes I say we punt for now. If someone wants to print they can scale in their print to PDF.
