### ISSUE TITLE
"Be part of the "DS" CTA banner layout refinement

### ISSUE THREAD

**Issue by kmbrlygl** [cagov/design-system#533]
The form and the graphic should 50/50 in the banner in terms of proportions (see [Figma mockup](https://www.figma.com/file/A1DSo765cWjvBWoLd6tvEE/DS-website-screens?node-id=893%3A12106)) with 24px space between. The graphic should also be centered vertically.

**Comment by jaredwyee** [comment]
@kmbrlygl @adam-little 
Can you confirm whether this is updated to spec? https://1-0-2-a11y-design.pr.designsystem.webstandards.ca.gov/

**Comment by kmbrlygl** [comment]
Yes, overall looks good. The only thing I notice is that the graphic is vertically centered to the form rather than the whole section. It would be more ideal to have it centered to the entire section to balance spacing above and below. Might be more work than it's worth, thoughts @chachasikes? Otherwise, I think this works. Definitely better than before.

**Comment by jaredwyee** [comment]
Thanks for weighing in @kmbrlygl. Closing this issue in anticipation of merging in the release tomorrow. 

@chachasikes if updating to center to the whole section is warranted, please use a new issue. Thanks!
