### ISSUE TITLE
Spacing improvements

### ISSUE THREAD

**Issue by kmbrlygl** [cagov/design-system#534]
Minor spacing issues when time permits:

- [x] Home: Need 16px space after card titles under "What's in the DS" 
- [x] Mobile/Home: spacing between hero and "what in the DS" sections aren't balanced
- [x] Mobile/Home: Add space after "What design systems do" heading

**Comment by adam-little** [comment]
@kkoryaka The homepage spacing still does not look right to me. I expect to see more space between each block of content.

Can you confirm the following?

- For each block of content on the homepage (Meet the DS, What's in the DS, What DS do, Principles, Be a part...):
- Each block has top and bottom padding of S-4 (32px)
- There is 0px spacing between each block.

![image](https://user-images.githubusercontent.com/69167298/151426786-2821ca6e-1614-4cb7-9cc0-be35c842da41.png)
![image](https://user-images.githubusercontent.com/69167298/151426823-b8a965cf-245d-4517-bc6a-b238e9972cb1.png)

**Comment by jaredwyee** [comment]
@adam-little  @kmbrlygl  please confirm this is fixed as expected in https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/

**Comment by kmbrlygl** [comment]
@jaredwyee Yes, good to go for this release! There may still be some small refinements needed, but we can address them at a later time.

**Comment by jaredwyee** [comment]
Sounds good thanks
