### ISSUE TITLE
Site header - Consider a visible label to search

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#539]
See https://www.nngroup.com/articles/form-design-placeholders/

**Comment by chachasikes** [comment]
@zakiya Is this p1 or p2?

**Comment by zakiya** [comment]
It's a change to the component, the website doesn't have a search bar.  So I guess p2.

**Comment by kkoryaka** [comment]
Article is talking about forms. And I agree with it. But here we are dealing with very conventional  search box (just one text field). I wold ask our researchers to do research on it. Do you think many people will forget what they are focused on if there is only one text field? i doubt it.

**Comment by zakiya** [comment]
I'm definitely in favor of doing research before making assumptions.

**Comment by zakiya** [comment]
Though this article agrees with @kkoryaka that it's okay to hide the visually hide the label. http://web-accessibility.carnegiemuseums.org/code/search/
