### ISSUE TITLE
Component library graphic on mobile (on home)

### ISSUE THREAD

**Issue by kmbrlygl** [cagov/design-system#541]
The component library graphic on smaller phone sizes (Pixel 3a) looks funky: 
![srcreenshot](https://user-images.githubusercontent.com/20393247/151237267-d31e3b57-9875-4d8d-bd20-043fe1fce38d.png)

**Comment by xjensen** [comment]
This seems to be fixed already.

**Comment by kmbrlygl** [comment]
This looks good to go, checked on my Pixel 3a. Apologies for the delay. I saw this was still open.

**Comment by chachasikes** [comment]
I see this is marked as done. Can we close it @kmbrlygl ?

**Comment by kmbrlygl** [comment]
@chachasikes yes!
