### ISSUE TITLE
CA.gov logo is not a consistent size. It should be the same size in the header and footer.

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#544]
Header:

![image](https://user-images.githubusercontent.com/69167298/151231262-13aeea2a-9f0b-48fc-818b-1e1ce977c66e.png)

Footer:

![image](https://user-images.githubusercontent.com/69167298/151231303-cf16609c-e71c-4aeb-8825-6a9b7c7cb51c.png)

In Figma, the icon is 33x24px
https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/UI-Design-kit?node-id=432%3A5905

**Comment by jaredwyee** [comment]
Confirmed 33x24 for header and footer in Windows Chrome on https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/
