### ISSUE TITLE
Mobile: Page Index should appear below H1. See Figma.

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#545]
Current website:
![IMG_4EA33292023A-1](https://user-images.githubusercontent.com/69167298/151233301-35b4b120-0c99-4c8d-9759-8c0440aee71b.jpeg)

Figma design:
![image](https://user-images.githubusercontent.com/69167298/151233400-957e0a91-6b13-4fef-bf74-b413ffc53e21.png)

https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/UI-Design-kit?node-id=5%3A3219

**Comment by kkoryaka** [comment]
Have to add 24px margin-button to nav element to match the figma prototype.
