### ISSUE TITLE
Fix heading spacing

### ISSUE THREAD

**Issue by kmbrlygl** [cagov/design-system#549]
There should typically be less space between headings and respective paragraph content, and more spacing between headings. Spacing on the website should match what's in the [UI Kit](https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/UI-Design-kit?node-id=2%3A5593) 
Example: spacing before and after H2s looks equal on [Getting Started](https://designsystem.webstandards.ca.gov/get-started/) page, when it should be 32px before and 24px after

Notes from discussion with Adam:

- When headers appear on content pages, then we should follow this rule of thumb: headings should be closer to the text they introduce than the text that precedes them (use at least **1.5 times the amount of whitespace above the heading as below it**).
   - For this reason, we want whitespace between the top of a header and the bottom of the content that precedes it.
   - The amount of white space should be relative to the size of the header. For example, an H2 on a page will most likely indicate a new section of content. Therefore it warrants significant white space above it.
- That rule above does not apply when there is no content above the header. For example, the H2 in the featured hero card does not need space above it

**Comment by kkoryaka** [comment]
@kmbrlygl  Here what we currently have, we are using design tokens, it looks like you are right about H2, we need to fix it. Is there anything anything else would alarm you?
H1
```
font-size: var(--font-size-10); // 2.9375rem; //47px
margin-top: var(--s-5); // 3rem; // 48px
margin-bottom: var(--s-4); // 2rem; // 32px
```

H2
```
font-size: var(--font-size-8); // 2.3175rem; //37px
margin-top: var(--s-3); // SHOUD be --s-4?
margin-bottom: var(--s-3); // 1.5rem; // 24px
```

H3
```
font-size: var(--font-size-6); // 1.8125rem; //29px
margin-top: var(--s-3); // 1.5rem // 24px
margin-bottom: var(--s-2); // 1rem; // 16px
```

H4
```
font-size: var(--font-size-4); // 1.4375rem; //23px
margin-top: var(--s-3); // 1.5rem // 24px
margin-bottom: var(--s-2); // 1rem; // 16px
```

H5
```
font-size: var(--font-size-2); // 1.125rem; //18px
margin-top: var(--s-3); // 1.5rem // 24px
margin-bottom: var(--s-2); // 1rem; // 16px
```


```
  --font-size-xs: 0.75rem; //12px
  --font-size-sm: 0.875rem; //14px
  --font-size-1: 1rem; //16px
  --font-size-2: 1.125rem; //18px
  --font-size-3: 1.25rem; //20px
  --font-size-4: 1.4375rem; //23px
  --font-size-5: 1.625rem; //26px
  --font-size-6: 1.8125rem; //29px
  --font-size-7: 2.0625rem; //33px
  --font-size-8: 2.3175rem; //37px
  --font-size-9: 2.625rem; //42px
  --font-size-10: 2.9375rem; //47px
  --font-size-11: 3.5rem; //56px
  --font-size-12: 5rem; //80px

  --s-1: 0.5rem;
  --s-2: 1rem; // 16px
  --s-3: 1.5rem; // 24px
  --s-4: 2rem; // 32px
  --s-5: 3rem; // 48px
  --s-6: 4rem; // 64px
  --s-7: 6rem; // 96px
  --s-8: 12rem; // 192px
```

**Comment by kmbrlygl** [comment]
cc @adam-little could you review this as well?

**Comment by kmbrlygl** [comment]
I think it looks good. Nothing glaring for me, the H2 fix should definitely improve the spacing throughout.

On a related note, do we have anything in the CSS that tames the line height? 
I think line height affects the spacing we are adding in so that it's hard to get things pixel-perfect to the Figma. Here's an [article on that](https://css-tricks.com/how-to-tame-line-height-in-css/). Not a priority though, it's for type refinement.

**Comment by kkoryaka** [comment]
@kmbrlygl we have separate ticket for line heights, I am waiting for you to set them in stone. As soon as you do it in figma I will add line-height properties to headings. 
But here are preliminary line-hight tokens for your reference:
```
  --font-lineheight-xs: 0.95;
  --font-lineheight-sm: 1.1;
  --font-lineheight-1: 1.25;
  --font-lineheight-2: 1.375;
  --font-lineheight-3: 1.5;
  --font-lineheight-4: 1.75;
  --font-lineheight-5: 2;
```

**Comment by kmbrlygl** [comment]
@kkoryaka Thank you. Apologies, I wasn't tagged back on that ticket so I check back on it.

**Comment by adam-little** [comment]
Seeing the design tokens here is helpful.

Let's think about how to document that header spacing in Figma and/or the [Visual Design Style Guide](https://designsystem.webstandards.ca.gov/style/design/#typography).

**Comment by jaredwyee** [comment]
@adam-little @kmbrlygl  please confirm this is working as expected in https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/

**Comment by kmbrlygl** [comment]
@jaredwyee yes, this should be good to go. We still need to work out how to document spacing on the Visual Design style guide but this is implemented. Will create a separate ticket for documentation.

**Comment by jaredwyee** [comment]
Thanks!
