### ISSUE TITLE
Typography: create an approach for handling orphans

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#560]
I don't think there's a feasible way to control this across all of the content, but we can target Headings since orphaned type is more obvious on titles.

Some web links:
- https://techstacker.com/how-to-remove-text-widows-orphans-web-typography/
- https://medium.com/swlh/typographic-orphans-on-the-web-266e32f756fe

Ideas: 
- Target the space before the last word on a heading, and replace it with a non-breaking space `&nbsp;` (being careful to not target any spacing that may be inputted after the title by accident)

**Comment by kkoryaka** [comment]
Do you have example (DS site screenshot)  of the orphan?

**Comment by kmbrlygl** [comment]
Updated the description for more info ^

One example that Jared pointed out:
![image (1)](https://user-images.githubusercontent.com/20393247/153472002-97f2e83d-8bba-4ff4-bd18-80208f9bee8e.png)

**Comment by xjensen** [comment]
The `&nbsp;` solution suggested by @adam-little is probably the best way to address this, for now. I can't think of anything better.

There is supposed to be a proper way to control orphans and widows in CSS. It's been around for 20 years. Unfortunately, Firefox never supported it. The CSS spec people are currently putting forward an expanded role for orphans and widows in their [CSS Fragmentation Module Level 3](https://drafts.csswg.org/css-break-3/#widows-orphans) proposal. Hopefully this will shake Firefox out of its slumber.

But until then, I assume `&nbsp;` is the best option on the technical front.
