### ISSUE TITLE
Update "Whats in Design System" illustrations with versions that include background pattern

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#562]
Current website does not have background elements in the illustrations: 
![image](https://user-images.githubusercontent.com/69167298/151260358-2cfbf8f0-fd92-416a-9f3d-4a4c19b1e495.png)

In Figma, illustrations have a background design:
![image](https://user-images.githubusercontent.com/69167298/151260405-45b92f6e-1d13-4972-b324-578aa2c13e0f.png)

Here are SVGs for these illustration
![illustration-components](https://user-images.githubusercontent.com/69167298/151260644-15aaa06b-65c8-4ae0-b1d7-0e32ee9c45ae.svg)
![illustration-principles](https://user-images.githubusercontent.com/69167298/151260645-fa7b78d5-d155-44a8-a301-b9c687b94867.svg)
![illustration-style-guides](https://user-images.githubusercontent.com/69167298/151260647-62a5022d-9c3f-42e9-be62-f9683598b842.svg)
s:

**Comment by kkoryaka** [comment]
@adam-little please review
