### ISSUE TITLE
Issue: Update contact us form fields. Simplify form.

### ISSUE THREAD

**Issue by jaredwyee** [cagov/design-system#574]
**Context:**
We have a contact form in two spots on the DS site. On the homepage: https://designsystem.webstandards.ca.gov/ and on the contact us page: https://designsystem.webstandards.ca.gov/contact-us/

With soft launch, we don't know exactly what to expect as far inbound contacts. Thus, it would be good to simplify the form and keep it more to the basics: name, email, role, the comment/question.

**Requirements:**
Update the contact us form in the two spots (home page and /contact-us) 
* Remove: "How can we help you?" field and dropdown.
* Update "About yourself" to "Your main role"
* Under your role have the following options:
1. Analytics
2. Content
3. Design
4. Development
5. Product
6. Program
7. Research
8. Other

* change "What interests you about the design system?" to "How we can help*"
* Make "How we can help" required. This is the open text comment
* Ensure that Airtable structure is updated if needed for updated form fields

This Gdoc has a representation of what should be in the form: https://docs.google.com/document/d/1swI6mDK3IXFTxhA_8jETc6TKmplOvj6PAQ-8gE-PLQY/edit#

**Comment by jaredwyee** [comment]
@chachasikes updated, let me know if have any questions/concerns, thanks!

**Comment by jaredwyee** [comment]
Hi @chachasikes I see the update on the prod site, thanks. Feedback:

- For the role, 'Program' is missing as an option.
- Free form blob 'How can we help?' is not indicated as required, but should be. Otherwise we might just get name/email. Not the worse case, but would be good to know why they are contacting us :).

**Comment by chachasikes** [comment]
@jaredwyee Seeing your notes - will take a look at the differences 
Used the google doc

**Comment by chachasikes** [comment]
This is in a PR to staging already, needs to be merged into our main branch for our 1.0.1 release

**Comment by jaredwyee** [comment]
Confirmed roles and expected required fields are appropriate on https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/contact-us/ and https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/
![image](https://user-images.githubusercontent.com/85529382/153269352-41d314cc-d40e-41cb-9ebd-f64fd3747081.png)
![image](https://user-images.githubusercontent.com/85529382/153269372-9d11a1a2-0907-4445-839a-1cd92257eaac.png)
