### ISSUE TITLE
Issue: README convention is all caps

### ISSUE THREAD

**Issue by chachasikes** [cagov/design-system#584]
Our site is not using the standard convention of making READMEs all caps. Let's fix it because the filenames in github can be case sensitive depending on the merge strategy and github config settings.

Our team is not attached to the lowercase version. 

**Backstory**
Chach deep dove in the the history of READMEs and government READMEs at a lunch and learn. This convention began with ASCII machines to bump the file to the top of the file directory, and is the commonly recommended and widely adopted. It will be confusing and cause merge errors if we do not decide on one format and stick to it. 

Further validation from wikipedia: (lowercase variant is not even listed)
"A README file contains information about the other files in a directory or archive of computer software. A form of documentation, it is usually a simple plain text file called README, Read Me, READ.ME, README.TXT,[1] README.md (to indicate the use of Markdown), or README.1ST.[2]

The file's name is generally written in uppercase. On Unix-like systems in particular, this causes it to stand out – both because lowercase filenames are more common, and because the ls command commonly sorts and displays files in ASCII-code order, in which uppercase filenames will appear first."

**Comment by xjensen** [comment]
I like this.

Should we also apply all caps to other documents in our components, such as the Changelogs? I would be in favor of making all the documents all caps. But whatever we decide, it should be consistent across all components.

**Comment by zakiya** [comment]
I very much agree with this. I'd like to see CAPS for all documents.

**Comment by chachasikes** [comment]
Yes on all the ALLCAPS.

**Comment by chachasikes** [comment]
Did an initial pass on this, slating it for next sprint.
Ran into an issue where the tabs disappear, and logic isn't crystal clear - need to search for it.

**Comment by chachasikes** [comment]
<img width="311" alt="Screen Shot 2022-02-22 at 2 53 15 PM" src="https://user-images.githubusercontent.com/149436/155233197-afccddcd-f753-4d6d-848b-ab53648a6ca8.png">

These will still be in Title case. If we want to change them, need to discuss it & it probably would need a design review.

**Comment by zakiya** [comment]
Not sure if this is what you're saying but if we need to KEEP the title case after the file name changes to all caps (which I think we do), we can solve with CSS. 

https://codepen.io/zakiyadrupal/pen/jOaKVGd
https://caniuse.com/css-first-letter

**Comment by chachasikes** [comment]
This didn't merge successfully - looks like it got dropped off. Will retry with our next release roll up. (We are in the process of testing our repeatable processes right now.)

**Comment by jaredwyee** [comment]
@chachasikes 
How should this be validated Should readme.md = README.md in Git now? I found some examples where it is not below. Or is it the string README is updated in our content on the design system website?

https://github.com/cagov/design-system/tree/main/components
https://github.com/cagov/design-system/tree/main/components/back-to-top
https://github.com/cagov/design-system/tree/main/components/base-css
https://github.com/cagov/design-system/tree/main/components/combined-css

**Comment by chachasikes** [comment]
Thanks Jared!
