### ISSUE TITLE
Write README for design-system repo

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#586]
Content being edited here: https://docs.google.com/document/d/1EOc92KjNvYWY1kTz-tG6Xcp05NoNDiO_dNMmyBXS2CU/edit#

**Comment by aaronhans** [comment]
Currently in @m-sullivan7's court

**Comment by m-sullivan7** [comment]
I did a first pass edit based on my gut. It's probably worth resolving/rejecting edits as they feel right and taking a look at again to see how it feels. 🙂

**Comment by aaronhans** [comment]
PR https://github.com/cagov/design-system/pull/587
