### ISSUE TITLE
Process: Sort out our project metrics

### ISSUE THREAD

**Issue by chachasikes** [cagov/design-system#594]
We identified some threads of feedback, input and other project metrics that we want to consolidate and make sure our team can access when we need it.
- [ ] Page feedback report
- [ ] Event tracking (on website interactions) #590 
- [ ] Contact us
- [ ] Access to regular Google analytics
- [ ] Insights on code access (distinction from NPM package downloads)

**Comment by chachasikes** [comment]
Set as p1 for getting our basic plan rolling.

Some of these tasks may need to become their own issues.

**Comment by mediajunkie** [comment]
@jaredwyee
