### ISSUE TITLE
Notes within CDN builds

### ISSUE THREAD

**Issue by xjensen** [cagov/design-system#596]
I propose we add some notes, in comments, at the top of each file we build for CDN distribution. These notes might include the component name, version number, link to our site, etc.

For example...

```js
/*
    California Design System
    @cagov/ds-accordion 1.0.12
    https://designsystem.webstandards.ca.gov
    MIT License (https://github.com/cagov/design-system/blob/main/LICENSE)
*/

// Code follows...
```

We can't control how people are going to fetch/copy and integrate these files into their projects. It's a good idea to provide these details in the files themselves, so far-future developers will always be able to understand what they're using.

**Comment by chachasikes** [comment]
This is a valuable idea & based on my review of many ca.gov sites - this tracks & can be useful for locating State projects using the design system.

If we can keep our headers as consistent as possible, it will help this.

**Comment by chachasikes** [comment]
Tagging myself in case I get inspired while making CDN build.
