### ISSUE TITLE
Bug: main navigation creates gap on resize when mobile menu is expanded

### ISSUE THREAD

**Issue by kkoryaka** [cagov/design-system#598]
When you open menu in mobile and then resize the screen to desktop size it creates this huge white space gap.

### Operating system, device, browser, screen size, etc.

iMac Chrome

### Steps to reproduce
1. Resize your browser to mobile size
2. Click on open main menu button (in mobile mode) 
3. Then resize the screen back to desktop size 

### Expected result
It should go back to normal desktop view.

### Actual result
It will create this huge white space gap.

# Screen shot(s) or video capture
![Screen Shot 2022-02-01 at 3 07 31 PM](https://user-images.githubusercontent.com/31669748/152067727-fdab0ede-a794-4205-9497-abf5646cce44.png)

**Comment by zakiya** [comment]
Fix looks great at https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/ Test on Mac Chrome, Safari and Firefox.
