### ISSUE TITLE
Patterns: Social media cards (from website) aspect ratios and ALT text

### ISSUE THREAD

**Issue by chachasikes** [cagov/design-system#601]
Social media cards, "unfurls", "og meta content" are linked images in the `<meta>` region of a webpage to comply with the sharing protocols of different social media platforms.

## What exists so far
For drought.ca.gov and cannabis.ca.gov, we are using WordPress plugin called The SEO Framework which auto-crops to a file to the most common non-cropping aspect ratio.

Chach & Jon have done a lot of work to ensure we have a system that keeps our social media links for any government pages functional and configurable for any content editor. We have an API structure that will fill in what the social media platforms want and ensure *.ca.gov sites on design system stacks are up-to-date in this way. Social media cards are one of the first entry points a user sees, and can be a very important piece of content. (If you care about this, please reach out on our contact form!)

## ALT tags
There is also ALT tag support for images using 
`og:image:alt`
`twitter:image:alt`

## Aspect ratios
The rules change a little every year or two as platforms evolve.

Our original spec is
`1200x630` - Facebook will resize other dimensions to 500 pixels high and adjust the width

This helpful article explains Facebook's crops: "Whether you're sharing landscape, portrait, or square images, Facebook will resize it to 500 pixels wide and scale the height accordingly." [Social Media Image Sizes in 2021: Guidelines for Posts on 5 Major Networks](https://buffer.com/library/ideal-image-sizes-social-media-posts/#:~:text=The%20Facebook%20recommended%20image%20size,and%20scale%20the%20height%20accordingly.)

I’m attaching what our current crops on our 500x500 image look like in the Facebook Sharing Debugger. 

<img width="1030" alt="Screen Shot 2022-02-01 at 3 44 32 PM" src="https://user-images.githubusercontent.com/149436/152071552-ee156e49-9c06-4dfb-bbf9-29af8ca3fc9b.png">
<img width="511" alt="Screen Shot 2022-02-01 at 3 45 06 PM" src="https://user-images.githubusercontent.com/149436/152071555-9f13010d-4be4-40d6-a75a-9f0880518a76.png">

You can use other aspect ratios if needed, but *generally at least 1080x1080px* for good resolution across all platforms - and expect that FB may be cropped, so be sure to not include important content in the crop zones.

## What design system site supports

On our design system site, we are providing:
* A default image
* If desired: a custom image per page 

## Size requirements
Recommendation 1200x630 or at least 1080x1080 with acknowledgement that Facebook will crop your image. 

[Social Media Image Sizes 2022: Cheat Sheet for Every Network](https://blog.hootsuite.com/social-media-image-sizes-guide/)
You can get more detailed.
You can also provide multiple sizes for manual sharing (in an Instagram Story or on TikTok) - but this isn't connected to the shares that come when someone shares a web page directly in a platform - and is a different use case.

## Technical note for developers 
The meta spec for og/twitter content is handled in our system
* Markdown sites: Content editors are adding these properties in the front matter portion of the markdown file. We have some defaults in place in a config file that 11ty uses to compile the correct meta content. 
* Headless Wordpress:  Our beta WordPress plugin for design system components converts SEO Framework data into this same spec and makes it available to the REST API. 

There are two "slots" for images:
`og:image` - All the other platforms except Twitter use this. There is only 1 size of image supported.
`twitter:image` - Twitter has [its own rules](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup). You can use another size for Twitter, but the markup required to support it is different - and you may need to adjust.

Note: There can also be app icons with different dimensions, but the social media unfurls do not use this.

## Testing
These two tools can help you test how your content will appear on a site.
You will need to be logged in to a Facebook or Twitter account to test a page
* [Facebook sharing debugger](https://developers.facebook.com/tools/debug/)
* [Twitter card validator](https://cards-dev.twitter.com/validator) (will not work on a "no robots" site)

**Comment by chachasikes** [comment]
@m-sullivan7 can I tag you on this to make sure the content/design team are keeping an eye on this? It was stuck in triage & I tagged some folks on Slack and didn't get a response.
cc @xjensen

**Comment by m-sullivan7** [comment]
Thank you for tagging me, especially as this was not on my mind! I've made notes in #470 (thanks to you bringing it up over there). I've made a note on my side to make sure that decisions made there get noted in this issue. 🙂

**Comment by yesenia-gtz** [comment]
Need content support to unblock work.

**Comment by aaronhans** [comment]
related https://github.com/cagov/design-system/issues/803

**Comment by ashleydraper** [comment]
Technical infrastructure for social alt text: https://github.com/cagov/design-system/blob/main/components/components.11tydata.js

**Comment by xjensen** [comment]
To build on Ashley's comment, [this line](https://github.com/cagov/design-system/blob/741fce10fa96de7c2d5df8c7a8098e564b71b330/components/components.11tydata.js#L43) will need to be altered to add social alt text to component pages.

We'll want to [edit the defaults](https://github.com/cagov/design-system/blob/main/docs/site/_data/editable/defaults.json), probably, for any pages that don't have social media defined.

And we'll need to add more specific social images and alt text (at top of markdown files) to every page as needed.

```
social_image_path: /img/your-image.png
social_image_width: 500
social_image_height: 500
social_image_alt_text: Your alt text
```

**Comment by chachasikes** [comment]
@xjensen will your social_image_alt_text attribute render out to both of these tags? 

og:image:alt: 
twitter:image:alt

**Comment by xjensen** [comment]
@chachasikes yes and yes.

`og:image:alt`: https://github.com/cagov/design-system/blob/741fce10fa96de7c2d5df8c7a8098e564b71b330/docs/site/_includes/layouts/index.njk#L27

`twitter:image:alt`: https://github.com/cagov/design-system/blob/741fce10fa96de7c2d5df8c7a8098e564b71b330/docs/site/_includes/layouts/index.njk#L35

**Comment by ashleydraper** [comment]
@xjensen Not sure why I'm not able to insert my alt text at the link you shared above. But here is the alt text copy:

_The brown State of California grizzly bear is seated and surrounded by four circles. The circle colors are yellow, blue, orange and green representing various colors you see in nature. An abstract swirl connects the colors behind the grizzly bear._

**Comment by xjensen** [comment]
@ashleydraper Are you trying to insert it into [this file](https://github.com/cagov/design-system/blob/main/docs/site/_data/editable/defaults.json)?

**Comment by ashleydraper** [comment]
Great question! I'm actually trying to add it to [line 43](https://github.com/cagov/design-system/blob/741fce10fa96de7c2d5df8c7a8098e564b71b330/components/components.11tydata.js#L43).

**Comment by xjensen** [comment]
Got it. That's a special file that only gets applied to pages for each component (accordion, page-feedback, etc.). Those pages require a bunch of extra processing.

Another question. Looking at your draft text, do you intend to make the bear image **default** for social media images across the whole site? Or do you only want to use that image for social media on the homepage?

**Comment by ashleydraper** [comment]
I might not be the right person to answer that question. I could see it working across the whole site, but there might be pages that warrant something more tailored. 

@chachasikes What are your thoughts? Do we want the bear image as the **default** image for socials sitewide?
