### ISSUE TITLE
Issue: Internationalization (i18n) and localization guidance 

### ISSUE THREAD

**Issue by hunterowens** [cagov/design-system#604]
love this repo :+1: and the system. 

It might not be the right fit, but I noticed that the accessibility components didn't mention anything about translation, internationalization / localization. Given that [44% of Californians](https://kmph.com/news/local/44-percent-of-californians-speak-other-than-english-at-home) speak a language other than english, some guidance on internationalization and localization would be great! might be out of scope, however.

**Comment by jaredwyee** [comment]
Hi @hunterowens thanks for the comments. You're definitely right, translatability and related guidance is on our to-do. Thanks for speaking up for the many Californians who's primary or preferred language is not english!
