### ISSUE TITLE
Proposal: Icons

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#608]
### Requesting agency
*Who is requesting this component?*
Office of Digital Innovation

### Background
*What prompted you to submit this proposal?*
@kkoryaka: Currently we have css with reference to those icons but we don't have actual installation mechanism that will install package with actual font files and all css on the website. Because we and users have to manually install those font files on a website...[U]sers would use the package if they need those icons. If they don't need it then it will be less css and less http requests for them.
See also #299

### Name
*What should we call this component in conversation? This may not be the final name, but it will help get us started.*
Icons (`ds-icons`)

### About this component
*Please tell us more about the component.*
Use the existing [CA.gov Icon Font Library](https://template.webstandards.ca.gov/sample/icon-fonts.html) to build this component. 

### Description
*Describe how this component will be used and what needs it supports.*
Providing icons in this manner will be easier for developers and make sites faster for end users.

### Examples from ca.gov properties
*To help us understand your project, please include some reference URLS, screenshots or other helpful information about your project.*
N/A

### Examples from other design systems
*If this component is commonly found in other design systems, please provide links or other useful information.*

-[USWDS](https://designsystem.digital.gov/components/icon/) has a separate component for icons

-[UK.gov Design System](https://design-system.service.gov.uk/components/) - no icon component 

-[courts.ca.gov courtyard](https://github.com/JudicialCouncilOfCalifornia/courtyard#icons-and-images) - Uses icomoon.io

### Features
*Possible features to support.*
- Ability to create a limited icon set to reference without using entire sprite.  For instance`npm run icon-build warning star question-mark `
- Ability easily download individual icons as SVGs (useful for designers and developers)
- Ability to inline icons For instand <cagov-icon name="warning">

---

Thank you!

**Comment by yesenia-gtz** [comment]
Good to go!
