### ISSUE TITLE
Create illustration for 404 page

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#610]
Create an illustration to add some personality to the 404 page.

This is inspired by the bear with the spilled honey pot from the State Web Template.

Figma mockup: https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/UI-Design-kit?node-id=5%3A3009

- [x] Create illustration
- [x] Add to 404 page

**Comment by Angsv** [comment]
Added SVG file to repository

**Comment by adam-little** [comment]
I updated our 404 page template using the SVG. You can see it here: https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/UI-Design-kit?node-id=5%3A3009

**Comment by adam-little** [comment]
Assigning to @chachasikes please let us know if you need anything else.

**Comment by chachasikes** [comment]
Adding this into the next sprint

**Comment by zakiya** [comment]
Assigning to myself. 
- error.njk
- assets/illustrations/binco-bear.svg

**Comment by zakiya** [comment]
**QA Notes**
- Paths like /nonsense won't show a styled 404 page on non-production environments. 
- To QA visit [610-error-bear.pr.designsystem.webstandards.ca.gov/error.html](https://610-error-bear.pr.designsystem.webstandards.ca.gov/error.html)

**Comment by yesenia-gtz** [comment]
Good to go!
