### ISSUE TITLE
Design of Code Demo buttons

### ISSUE THREAD

**Issue by xjensen** [cagov/design-system#627]
Let's explore adding interactive buttons to our code previews.

Here's some background. In #622, we fixed a problem with the page-alert component's preview. When the page-alert is closed, the reader had no way to bring it back into the preview without reloading the page. So we added a "Reset demo" button that could bring the page-alert back.

<img width="818" alt="Screen Shot 2022-02-04 at 16 16 42" src="https://user-images.githubusercontent.com/1208960/152836047-b54b873c-c9b3-4c0c-a039-9d37ded49b53.png">

First, do we like this approach from a design perspective? Do we want to do anything differently visually?

Second, are there other buttons that we might want to add? For example, we might consider adding buttons that could change the viewport of the preview, so the reader could see the mobile version as well.

**Comment by chachasikes** [comment]
* Change language dropdown button

**Comment by chachasikes** [comment]
We built a language button for another project (for PDFs) & have some work on translated content we could merge into this idea if needed.

**Comment by chachasikes** [comment]
Storybook also has some UI toggles for accessibility - but (FWIW) not sure rebuilding Storybook in our UI would be a good idea.
