### ISSUE TITLE
Color Contrast does not pass AA standards on Step Lists.

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#631]
**Context:**
See [Accessibility Review document](https://docs.google.com/document/d/13FEjWgNYisN_1ahSffZApXYrCw7Kli7Uw1t1qK4YmG8/edit#): 
![image](https://user-images.githubusercontent.com/69167298/153073521-cc47d530-322e-4da3-8021-41d07ed83f5d.png)

**Suggested approach:** 
I suggest we chance the text color on the selected state from #ffffff to #000000
![image](https://user-images.githubusercontent.com/69167298/153073414-77446404-8c5e-4be3-9be6-d4e20707a144.png)

**Comment by jaredwyee** [comment]
Confirmed working. Closing. Pending move to done tomrrow after release merge.
