### ISSUE TITLE
Visual design style guide: The way the color tables are laid out currently the screen reader only reads the table header when it arrives on the color rows.

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#632]
See [Accessibility Review document](https://docs.google.com/document/d/13FEjWgNYisN_1ahSffZApXYrCw7Kli7Uw1t1qK4YmG8/edit#)
![image](https://user-images.githubusercontent.com/69167298/153070508-9c99b162-64f6-4656-89b3-af189be907c8.png)

**Comment by kkoryaka** [comment]
I would not use table at all. Lets use normal normal columns layout with color chips as div containers (that will be ignored by screen readers) and the color values text that will be normally read by screen readers.
![Screen Shot 2022-02-08 at 4 31 47 PM](https://user-images.githubusercontent.com/31669748/153099139-0f384e57-1a8c-4740-82ff-cb07ae62d6b0.png)

**Comment by jaredwyee** [comment]
@kmbrlygl please confirm this issue is as expected https://1-0-2-a11y-design.pr.designsystem.webstandards.ca.gov/style/design/

**Comment by kmbrlygl** [comment]
@jaredwyee Yes, good to go! Thanks for checking.
