### ISSUE TITLE
sass compilation mystery

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#64]
Why can't I define a sass variable at the top of a file and then use the variable name as the value for a CSS variable declaration at the bottom of the same file?

Tried this before and it wasn't working so just temporarily hardcoded the values for the CSS variables. It would be cool if this worked though because then inside a single component we could share sass variables across files and do advanced sass stuff like darken and then export those values to other components by defining CSS variables

**Comment by kkoryaka** [comment]
maybe because Sass variables only have one value at a time, so you can't define them if they were defined somewhere in the project. But I could be wrong.

**Comment by chachasikes** [comment]
Is this sorted out now?

**Comment by chachasikes** [comment]
Closing this issue. Feel free to reopen it if it comes up again.
