### ISSUE TITLE
Add close icon to components menu

### ISSUE THREAD

**Issue by xjensen** [cagov/design-system#640]
We recently fixed the arrow icon on the components menu in #468. We now need to add the close "X" icon when the menu is open.

<img width="482" alt="Screen Shot 2022-02-09 at 09 34 24" src="https://user-images.githubusercontent.com/1208960/153257557-d3e11a9b-f624-4da1-8248-2be8396e902b.png">

**Comment by alexhu00** [comment]
I can take this!

**Comment by xjensen** [comment]
Thanks, @alexhu00! Just let us know if you come across any questions.
