### ISSUE TITLE
Components header space is broken for a number of the component pages

### ISSUE THREAD

**Issue by jaredwyee** [cagov/design-system#644]
In QAing the release cut site: https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/, noticed that a number of the change log pages (and one readme page) have huge spacing issues with the header. Inconsistent depending on the page.

https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/components/back-to-top/changelog/
https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/components/link-icon/changelog/
https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/components/pagination/changelog/
https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/components/skip-to-content/changelog/
https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/pr/1-0-1-rc-post-launch-fixes/components/base-css/readme/
https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/components/feature-card/changelog/
https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/components/link-grid/changelog/
https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/components/page-alert/changelog/
https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/components/regulatory-outline/changelog/
https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/components/step-list/changelog/

**Examples**
![image](https://user-images.githubusercontent.com/85529382/153271034-b73c2e15-e8ef-40b4-bfd4-d0295b58c99b.png)

![image](https://user-images.githubusercontent.com/85529382/153271109-477438f0-f879-4978-bbeb-f453afd8d85c.png)

**Comment by xjensen** [comment]
@jaredwyee We have a fix incoming at #645.
