### ISSUE TITLE
Create logo for Design System website, as a way to make the page more visually engaging and model the intended use of the site header

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#647]

**Comment by adam-little** [comment]
Here;s an example provided by @artuoma 
![image](https://user-images.githubusercontent.com/69167298/153298463-e09fee49-6c00-41cd-902a-ec1160b2f15d.png)

**Comment by sharon-rabang** [comment]
Did research, mood board, and a few explorations in Figma: [Design System Logo](https://www.figma.com/file/pHUQ0skV20xIXIO1VvDYnZ/Design-System-Logo?node-id=0%3A1)

Will work on the next round of explorations, based on feedback received from our 04/12/22 web design meeting.
