### ISSUE TITLE
dynamic sample HTML in readmes

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#65]
Right now we are pasting HTML snippets into readmes. This code needs to be part of the readme but it is also used as fixtures for tests and live preview links. If this HTML snippet could be stored and updated in a single place it is less likely the duplicated versions will drift and one (probably the readme) would get left behind which will cause frustration for users.

Possible way to solve this:

- Use husky pre commit hooks: https://github.com/typicode/husky
- runs local script from package.json scripts section command
- local script gets sample html from template.html
- replaces sample token in readme with retrieved content

If this block is in a readme the samp tags don't show up in preview but they provide good regex hooks to replace this block:
  
sample code:
<samp>
```
<div>hello world</div>
```
</samp>

**Comment by aaronhans** [comment]
@kkoryaka @chachasikes any thoughts, suggestions, objections to doing something like this to make part of the readmes generated on commit?

**Comment by chachasikes** [comment]
This sounds great.

**Comment by aaronhans** [comment]
Open PR which implements this for all js based components: https://github.com/cagov/design-system/pull/366

**Comment by aaronhans** [comment]
sample HTML driven by scripts has been merged for all components
