### ISSUE TITLE
Consider unique link text for example websites under "Who's using the DS"

### ISSUE THREAD

**Issue by jaredwyee** [cagov/design-system#657]
Recommendation:  Change the link text descriptions so they are not identical.

![image](https://user-images.githubusercontent.com/85529382/153973431-d43054f0-e9de-4b8c-874f-52cee6e22f71.png)

**WCAG 2.1 Guideline** [2.4.9 Link Purpose (Link Only)](https://www.w3.org/TR/WCAG/#link-purpose-link-only)
These two links have the same accessible name but go to different resources. They open completely different pages.

**Comment by jaredwyee** [comment]
@m-sullivan7 Input? Maybe `Visit cannabis.ca.gov` and `Visit covid19.ca.gov` respectively?

**Comment by m-sullivan7** [comment]
That's exactly what I was thinking. I believe I can make this change in the code, so I'm claiming this issue.

**Comment by m-sullivan7** [comment]
New text published. Closing issue.
