### ISSUE TITLE
Pattern: Forms

### ISSUE THREAD

**Issue by jaredwyee** [cagov/design-system#659]
Recommendation: If an input error is automatically detected and suggestions for correction are known, then the suggestions are provided to the user.

We have three required fields:
* name
* email
* `how we can help?` text input

**Design consideration**
* If the submit button is pressed and one or all of the above fields is missing, where should be place the error message? And what should it read? eg next to submit: "[Name, email, how can we help?] input is required to submit". 

* If the error state text is a color (say red) when shown on the blue background contact form on the homepage, consider the appropriate color on https://designsystem.webstandards.ca.gov/contact-us/ where there is a gray background. We need to ensure appropriate contrast.

**Contact us form on https://designsystem.webstandards.ca.gov/**
![image](https://user-images.githubusercontent.com/85529382/153975254-6488165c-79fc-4280-aaaf-c3a3e25201bb.png)

**Contact us form on https://designsystem.webstandards.ca.gov/contact-us/**
![image](https://user-images.githubusercontent.com/85529382/153975226-461b8b02-78f0-4482-92f5-221c76f4e069.png)

**WCAG 2.1 Guideline**
[3.3.1 Error Identification (Level A)
](https://www.w3.org/TR/WCAG/#error-identification)
[3.3.3 Error Suggestion (Level AA)](https://www.w3.org/TR/WCAG/#error-suggestion)

**Comment by jaredwyee** [comment]
@adam-little @kmbrlygl do you have input on a good pattern for error state after pressing submit, when all required fields are not filled out?

My first inclination is a message next to the Submit button because you just pressed that. Then list all the missing fields.

**Comment by adam-little** [comment]
We'll look into this!

It relates to: https://github.com/cagov/design-system/issues/558

**Comment by chachasikes** [comment]
Any follow up on this?

**Comment by adam-little** [comment]
Yes, sorry for the delay.

Please see Figma for updated form field states for the two contact forms on the Design System website.

https://www.figma.com/file/A1DSo765cWjvBWoLd6tvEE/DS-website-screens?node-id=0%3A1

We might need a separate ticket to document copy for error states. What do you think @m-sullivan7?

As a side note, we have additional thinking for form fields but will hold off on documenting that until we decide to make form components.

**Comment by m-sullivan7** [comment]
I took a look and made one edit in Figma ("cannot" for "can not"). Those look good to me!

Regarding a separate issue for documentation, would this be for standards around error state text or specifically for this use case?

**Comment by adam-little** [comment]
> Regarding a separate issue for documentation, would this be for standards around error state text or specifically for this use case?

Just for this use case (for now), so the updates you made in Figma should be good enough.

**Comment by yesenia-gtz** [comment]
**UPDATE:**
We are adding Form as a pattern using various inputs options. These inputs will be broken out to the component level.

Needs:
- [ ]  Labels
- [ ] Required fields
- [ ] Disabled fields
- [ ] Inputs (check boxes, radio, text fields, etc)
- [ ] Error messaging
- [ ] Use guides and standards
- [ ] Technical documentation
- [ ] Integration considerations for data collection

Available components and design items:
- Button
- [Input explorations](https://www.figma.com/file/4kfjgYBUbX6gi2yQZaBCwy/Focus-states?node-id=0%3A1)

cc @rkojik @extinah @sharon-rabang @zakiya
