### ISSUE TITLE
Show page structure and clean starter template code sample (for devs)

### ISSUE THREAD

**Issue by kkoryaka** [cagov/design-system#669]
It would be helpful to display essential webpage structure example and clean starter template html code sample for developers. We have component library  but we don't show entire page structure and how do we tie structural components together. 

Here is example from ca state template page structure example (refer to "Clean Starter Template" code sample: https://template.webstandards.ca.gov/getting-started.html.

US Design System: https://v1.designsystem.digital.gov/documentation/developers/#installation

**Comment by jaredwyee** [comment]
@kkoryaka @chachasikes confirmed that https://release-1-0-3-ahjumawi.pr.designsystem.webstandards.ca.gov/structure/#webpage-code-template exists

However, should webpage-code-template be linked to from /components or elsewhere?
![image](https://user-images.githubusercontent.com/85529382/157728648-79fb77f6-0051-4f5b-a3e6-c870c4c9cb85.png)

**Comment by kkoryaka** [comment]
@jaredwyee , this is not components based code, this is e entire page structure, it's shell in which components can be placed.

**Comment by chachasikes** [comment]
Is the goal to ship the page, unlinked in menu structure? 

I think we do want to link it somewhere, but have not decided. 
I am OK with shipping the page & then adding a new issue to decide where it can be linked from.

Sound good @kkoryaka  and @jaredwyee

**Comment by kkoryaka** [comment]
@chachasikes It is liked from in getting started > for developers section

**Comment by chachasikes** [comment]
Ah ok - the "Developers" section is hidden & only available in dev mode.

Think we should still ship it and decide on when/how to launch a developers menu in next couple of weeks.

**Comment by jaredwyee** [comment]
Sounds good. I think I've previously commented that https://designsystem.webstandards.ca.gov/technical-approach/ should be emphasized further in the nav structure too. That seems related to a "developers" section as well.

**Comment by kkoryaka** [comment]
@chachasikes  It is here. (Not the hidden nav item)
![Screen Shot 2022-03-10 at 2 13 21 PM](https://user-images.githubusercontent.com/31669748/157763767-2dc959de-17a3-4b6c-b727-db2fc2eb466c.png)

**Comment by chachasikes** [comment]
Ah! OK, good to know, thanks @kkoryaka!
