### ISSUE TITLE
Possible enhancements to page-navigation

### ISSUE THREAD

**Issue by xjensen** [cagov/design-system#672]
Following work on #670, there are a few things we might want to reconsider within the page-navigation component.

* There's a lot of polyfill JS code to help smooth scrolling work in Safari. We may want to remove this given (1) the next version of Safari will have support for native CSS and JS implementations of smooth scrolling and (2) I'm not sure if it's worth the bloat to support one animation in one browser (progressive enhancement, etc.).
* There's been discussion on the team about needing a page-navigation component that can link between pages, rather than just between sections on one page. We've already cobbled this together for the components pages on the DS site. We're looking at doing it again on the DS site's content design pages too. And many other departments currently do something like this on their sites. We may want to add that capability to this component.
* Investigate removing `.focus()` from the JS, so we can remove `tabindex=-1` from our headings. See #661 and #670.
* I think it's a good progressive enhancement goal to enable pre-populating this component with static mark-up. This might also line up with the previous point about inter-page linking.
* There's a long-standing bug where header `id` that lead with a number result in broken links. See "2021 overview" link [here](https://drought.ca.gov/current-drought-conditions/) for an example. This appears to be a problem whether the `id` on the header is pre-generated or not.
* The dependency on the `<sidebar>` element should be removed from CSS. Especially considering `sidebar` is not a valid HTML element name.

**Comment by chachasikes** [comment]
* good note on the <sidebar> - some of that code (probably) came from everylayout & if so I blame Koji for the recommendation :P 

Great summary of suggested improvements @xjensen 
Do you know about when the Safari update will happen?

**Comment by xjensen** [comment]
@chachasikes Smooth scrolling is currently in the [Safari 15.4 beta](https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes). I'm assuming it'll release with the next version of macOS.
