### ISSUE TITLE
Update copy on 404 page

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#675]
Noticing that our 404 page content may need to be polished.
![image](https://user-images.githubusercontent.com/69167298/154538943-590e041d-bb8a-4bb1-af5e-97294fa83e10.png)

This is what we have in the Figma UI Kit:
![image](https://user-images.githubusercontent.com/69167298/154539378-cbfc1b88-1405-4190-9d97-d83c52069737.png)

**Comment by adam-little** [comment]
As a sidenote: we will be adding an illustration to this screen - https://github.com/cagov/design-system/issues/610

**Comment by adam-little** [comment]
@m-sullivan7 - Can you clarify for me: Is including "Page not found" intentional? Or should we take this away since we have "We can't find the page you're looking for."

I'm asking because it might impact how we think about the 404 page illustration

**Comment by xjensen** [comment]
@adam-little "Page not found" probably snuck into the page when I changed how titles are rendered. It's an oversight on my part. I can fix it.

**Comment by adam-little** [comment]
Thanks!

**Comment by jaredwyee** [comment]
@xjensen @zakiya 
Is this not testable on the release branch?
https://1-0-2-a11y-design.pr.designsystem.webstandards.ca.gov/alskdjfadsf
![image](https://user-images.githubusercontent.com/85529382/155410379-832221dc-ddf7-484b-939d-48371b169db9.png)

**Comment by xjensen** [comment]
@jaredwyee That's right, it's not testable on the PR branch. Apologies for that. It's a limitation of our PR sites. It should be possible to see it at the following URL.

https://1-0-2-a11y-design.pr.designsystem.webstandards.ca.gov/error.html

**Comment by jaredwyee** [comment]
no worries, thanks for confirming. Will say this is working as best as we can tell now. Will need to reconfirm once in prod :).
