### ISSUE TITLE
Design: The "Icons" component needs illustration.

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#678]
A [new component to handle icons](https://608-icons-11ty.pr.designsystem.webstandards.ca.gov/pr/608-icons-11ty/components/icons/readme/) is in the works. 

In order to launch it, we'll need an illustration for the [components page](https://designsystem.webstandards.ca.gov/components/).

**Comment by kmbrlygl** [comment]
This is the direction we generally landed on @zakiya 
Here's the SVG for the component library page: 
![icon-library.svg](https://user-images.githubusercontent.com/20393247/158706842-371dc671-7f41-41ba-adec-cabe81652827.svg)

Here is the png (for social share): 
![icons-library.png](https://user-images.githubusercontent.com/20393247/158707104-47d68f34-fc38-4df7-b85b-0ac06a624d01.png)

Let me know if you have any questions!

**Comment by zakiya** [comment]
@kmbrlygl 

The illustration is in place at https://608-icons-11ty.pr.designsystem.webstandards.ca.gov/components/

Share https://608-icons-11ty.pr.designsystem.webstandards.ca.gov/pr/608-icons-11ty/components/icons/readme/ to see the social media icon. 

Once reviewed/approved you can assign this back to me.

**Comment by kmbrlygl** [comment]
Looks great! Thank you @zakiya

**Comment by yesenia-gtz** [comment]
Good to go!
