### ISSUE TITLE
Documentation: Icons 

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#679]
A [new component to handle icons](https://608-icons-11ty.pr.designsystem.webstandards.ca.gov/pr/608-icons-11ty/components/icons/readme/) is in the works. 

In order to launch it, we'll need to complete the documenation

**Comment by zakiya** [comment]
We have used used the icons throughout the site and on other ODI projects. We use the CA.gov icon library as our source.  This effort isn't just to bring create the component but to also give guidance on how they should be used by engineers (currently we have many inconsistencies) and also provide a reference for designers. I'm in favor of scheduling a swarm/meeting to explain further. If the button conversation is including the use of icons, I should be included in those. 

Here's a list of components that currently use icons:

page-alert 
site-footer  
site-header
statewide-footer 
statewide-header
back-to-top
link-icon
site-navigation
accordion
link-grid

We also have an additional icon on the buttons on design page of the website.

**Comment by jaredwyee** [comment]
@zakiya Thanks for the additional context. Will setup a sync for us next week.

**Comment by m-sullivan7** [comment]
I'm changing the content team assignment on this to @LizNobriga as she has volunteer to be the point person for this documentation. I'll still be at the sync and am looking forward to this!

**Comment by zakiya** [comment]
Here's the readme Template that @chachasikes created: https://github.com/cagov/design-system/wiki/Component-README-template-(DRAFT)

**Comment by jaredwyee** [comment]
Did a high-level overview as a team.

@LizNobriga will let us know when to expect anticipated first draft - consider structure (eg icons should be in a separate page to disentangle from component documentation), intro, usage guidance (dos/dont's), and general copy editing.

@adam-little share any design/layout refinement improvements that could be made. If it comes down to it, such changes would not be blockers to moving forward. Just iterative improvements. Adam will also consider how designers might want access to icons to have the set availability locally (Figma link, other design tool use). 

@jaredwyee work with research if we need a developer to read/"usability test" the documentation after draft is ready.

**Comment by zakiya** [comment]
@LizNobriga sorry to add these last minute:

We will also need a short description for the [Components page](https://608-icons-11ty.pr.designsystem.webstandards.ca.gov/components/)

![CleanShot 2022-03-17 at 10 59 16](https://user-images.githubusercontent.com/915352/158866239-48051abf-1a27-4b55-86c9-6688d929291c.png)

And I noticed we don't have real intro text to the [Visual components section](https://608-icons-11ty.pr.designsystem.webstandards.ca.gov/components/#visual-components):

![CleanShot 2022-03-17 at 11 00 03](https://user-images.githubusercontent.com/915352/158866331-07f00a22-1613-4073-9aa2-b2ae284ca2ed.png)

**Comment by zakiya** [comment]
@LizNobriga This is the url for the preview site: https://608-icons-11ty.pr.designsystem.webstandards.ca.gov/

**Comment by LizNobriga** [comment]
Hi @zakiya. Content is ready for the [Icons component](https://608-icons-11ty.pr.designsystem.webstandards.ca.gov/pr/608-icons-11ty/components/icons/readme/) page. It includes this link, [Version 5.6.1 of the CAGov icon library](https://california.azureedge.net/cdt/statetemplate/5.6.1/fonts/CaGov.svg). Is there a better link or should we keep this one for now?

The Icons blurb on the [Components page](https://608-icons-11ty.pr.designsystem.webstandards.ca.gov/components/#visual-components) is also ready. 

The intro sentence for [Visual components](https://designsystem.webstandards.ca.gov/components/#visual-components) is already updated on the main site.

**Comment by zakiya** [comment]
Thanks @LizNobriga! I updated the link  in question to reference the Icon Library on the same page. 

https://608-icons-11ty.pr.designsystem.webstandards.ca.gov/pr/608-icons-11ty/components/icons/readme/#icon-library

Is that cool?

**Comment by LizNobriga** [comment]
Oh I see now. Yep, looks good.

**Comment by yesenia-gtz** [comment]
Good to go!
