### ISSUE TITLE
Process: Consider using Architectural decision records for our major technology decisions.

### ISSUE THREAD

**Issue by chachasikes** [cagov/design-system#687]
Architectural decisions records could help us record our technology choices for long term memory.

About: 
https://18f.gsa.gov/2021/07/06/architecture_decision_records_helpful_now_invaluable_later/

Example:
https://github.com/transcom/mymove/tree/master/docs/adr

Example of a decision: 
https://github.com/18F/piipan/blob/main/docs/adr/0013-use-private-links.md

Let's try this in a future sprint.

**Comment by chachasikes** [comment]
Helpful post from Spotify blog:
https://engineering.atspotify.com/2020/04/when-should-i-write-an-architecture-decision-record/

**Comment by chachasikes** [comment]
Tons of links: https://adr.github.io/

**Comment by xjensen** [comment]
It's a neat idea. Here are some random feelings.

* I like the 18F approach to proposing new decisions via PR. I think it would also be a good idea to hold a regular meeting to discuss new proposals as a team, at least at first.
* We may want to back-write all of our previous decisions. Sounds like an opaque but important task. Easier to do while the Design System is still young.
* My preference is that we keep our template simple.

**Comment by chachasikes** [comment]
@xjensen Thanks Jon - I created a planning doc file 

Public: https://chach-sikes-odi-notes.notion.site/chach-sikes-odi-notes/DRAFT-PROPOSED-Design-System-Architecture-Decision-Records-Planning-Doc-39612337efe9436eb56c1d2a781c96e6

Edit: https://www.notion.so/chach-sikes-odi-notes/Design-System-Architecture-Decision-Records-Planning-Doc-39612337efe9436eb56c1d2a781c96e6 (lmk if anyone wants to help)

**Comment by chachasikes** [comment]
Trying this in cannabis.ca.gov data viz project:

Template:


# x. Decision name

Date: 

## Status

## Context

## Decision

## Consequences

## Architectural Decision Records
Exploring this idea of embedding more long-term context in State gov github repositories.
REF: https://github.com/cagov/design-system/issues/687 (can change reference)

**Comment by chachasikes** [comment]
Work in progress:
https://github.com/cagov/cannabis.ca.gov/tree/feature/cannabis-legal-access/src/js/charts/cannabis-legal-access/adr
