### ISSUE TITLE
Create design tokens reference page

### ISSUE THREAD

**Issue by kkoryaka** [cagov/design-system#688]
Create page with css variables listing and usage examples similar to this pages: https://open-props.style or https://designsystem.digital.gov/design-tokens/

---
Create following sections showcasing design tokens and their usage: 
- Responsive tokens (Container widths variables)
- Measure tokens (spacing and size variables)
- Color tokens (color scheme primary, secondary and gray color variables)
- Typography tokens (font weight, font size, line height variables) 
- Borders (border width and border radius variables)
- Shadow variables
- Animation tokens (transition and animation variables)

**Comment by jaredwyee** [comment]
Confirmed https://release-1-0-3-ahjumawi.pr.designsystem.webstandards.ca.gov/style/tokens/#animation-tokens page exists and can be accessed under style guides part of nav.

Confirmed left nav anchor links work to bring you to that area of content

![image](https://user-images.githubusercontent.com/85529382/157728912-77e3b0e3-516b-43f2-93c5-8cff6d093a9a.png)
![Uploading image.png…]()

**Comment by chachasikes** [comment]
Great, thanks so much.
