### ISSUE TITLE
Create color system docs

### ISSUE THREAD

**Issue by chachasikes** [cagov/design-system#69]
@adam-little shared his work on the color system for the design system. 

We set a time to start an outline of how we can document the color system, and start to gather references about the design research and accessibility features for the color choices and how it is intended to be applied. This integrations with the CSS variables already in place for the design system.

We will review this with design system team.

**Comment by chachasikes** [comment]
Co-assigning cause this is a collaborative issue.

**Comment by chachasikes** [comment]
Update: Adam created a google doc with this information.

@adam-little  
Two questions:
1. Did you include a spot in your doc for any references for choices you were making? That was the main thing that we were trying to make sure gets included in the docs.
2. Can you provide a link to your doc? If it's not in the Google Drive folder, can you add a new folder for Design & put it in our shared folder?

**Comment by adam-little** [comment]
Here's a link to the doc with updated documentation about decision making rationale. I moved it to the CA.gov + Design System folder.

https://docs.google.com/document/d/17MtpWf1rZIl_Ge05DEQqIsd_NxBYha6krjRBhSUhdXg/edit?usp=sharing
