### ISSUE TITLE
Styles: Convert social media graphic to PNG and add as share card

### ISSUE THREAD

**Issue by chachasikes** [cagov/design-system#695]
Angelina uploaded a SVG for the social media share. Let's convert it to PNG for ubiquitous file sharing on all social media networks, and confirm that the file will work.

Would like to cross-train someone on the card debugging with someone at the end of this sprint during QA.

**Comment by kmbrlygl** [comment]
Hey @chachasikes here's the social media graphic in the 1200x630 size. Let me know if this doesn't work. Thanks!
![hero-bear-social-share_1200x630](https://user-images.githubusercontent.com/20393247/166320928-2db0b870-2a4d-4a40-904d-a71318b489e7.png)
