### ISSUE TITLE
Styles: Icons

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#699]
- [ ] Make icon library searchable. 
- [ ] Demonstrate color and size changes. 
- [ ] Provide zip of all icons for designers
- [ ] Remove link from icon name in Icon Library like: 
       zoom-out.svg
       [Download](https://608-icons-11ty.pr.designsystem.webstandards.ca.gov/cagov-icons-svg/zoom-out.svg)

**Comment by zakiya** [comment]
Un-assigning myself so my Issue list is current. Feel free to assign to me when/if it leaves the backlog.

**Comment by yesenia-gtz** [comment]
Closing, added details and consolidated with https://github.com/cagov/design-system/issues/779
