### ISSUE TITLE
Component: Branding Block (informs DS)

### ISSUE THREAD

**Issue by kkoryaka** [cagov/design-system#7]
Create branding component that will include: 
- brand/logo, 
- organization/entity/Dept./ project/website name 
- search input box (search button in mobile)
- menu button (in mobile)

This component might include search ID  JavaScript code and some expand and collapse functions javaScript code for search and menu buttons in mobile.

Figma link: https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/cannabis.ca.gov-screens?node-id=381%3A3318

Layout: 
<img width="1013" alt="Screen Shot 2021-05-10 at 3 58 49 PM" src="https://user-images.githubusercontent.com/31669748/117734815-1253c000-b1a9-11eb-9066-03c72f66de35.png">
<img width="296" alt="Screen Shot 2021-05-10 at 3 58 03 PM" src="https://user-images.githubusercontent.com/31669748/117734817-12ec5680-b1a9-11eb-9e5f-5f370dfd4b94.png">

Where will this live?
design-system/components/branding/template.html
design-system/components/branding/index.css
design-system/components/branding/index.js

**Comment by abquirarte** [comment]
I like where this is headed.
I wonder if we could merge this part with the split of COLD.govops.ca.gov.

CC @James Bumgardner ***@***.***> and @Aaron Hans
***@***.***>

Angelica Quirarte, "Angie"
Deputy Director | Office of Digital Innovation
c: 916-526-5510 or 916-812-6864
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by kkoryaka** [comment]
Added branding WP manual styles: https://github.com/cagov/cannabis.ca.gov/commit/f7d3f760e7c25f06fdaf78deb36649827967fd81
