### ISSUE TITLE
Styles: Design focus states

### ISSUE THREAD

**Issue by kmbrlygl** [cagov/design-system#700]
Brought up during Design Team meeting (with OET/CDT folks), we discussed wanting to design focus states on interactive elements that work on dark and light backgrounds

**Comment by adam-little** [comment]
This relates to https://github.com/cagov/design-system/issues/755 since they both appear to be about colors of focus states

**Comment by sharon-rabang** [comment]
Did research and initial set of explorations in Figma: [Focus states](https://www.figma.com/file/4kfjgYBUbX6gi2yQZaBCwy/Focus-states?node-id=0%3A1)

Will work on the next round of explorations, based on feedback received from our 04/12/22 web design meeting.

**Comment by sharon-rabang** [comment]
In Slack: cagov-design-system-design

Hello! Update on [#700](https://github.com/cagov/design-system/issues/700) Design focus states (related to [#755](https://github.com/cagov/design-system/issues/755) Links and button outline on focus is not accessible)

Thanks for all of the helpful feedback at our 4/12/22 weekly design meeting and from today's mini meeting. I did more studies and found a single color that works on both our light and dark backgrounds. 

Here's the direction I propose moving forward with in [Figma](https://www.figma.com/file/4kfjgYBUbX6gi2yQZaBCwy/Focus-states?node-id=8%3A143):
	• Custom focus style: Box-shadow (has the widest range of aesthetic design capabilities)
	• Focus color: 
		○ 4px #2491FF on light, #FFFFFF
Contrast ratio 3.2:1 
		○ 4px #2491FF on dark, #003688
Contrast ratio 3.5:1
		
Let me know if you have any feedback, before moving forward with a developer.

Thanks!

**Comment by yesenia-gtz** [comment]
@sharon-rabang moving to in progress.

**Comment by sharon-rabang** [comment]
06/15/22: Met with Ashley Draper from the Content Team about this project and the draft content.
06/17/22: Ashley provided us with revised content. Will share it at the 06/21/22 design team meeting.

**Comment by sharon-rabang** [comment]
The "Focus state" content (revised by @ashleydraper) has been reviewed and approved by the Design Team. 

@yesenia-gtz We can update the [Visual design style guide](https://designsystem.webstandards.ca.gov/style/design) page with this content, once the focus states have been developed. 

[Visual design style guide](https://designsystem.webstandards.ca.gov/style/design) page content updates:
1. Add the “Focus state (h2)” content after the “Buttons (h2)” content
### Focus state
Some people use keyboards or other assistive devices to navigate through a page. A focus state highlights the interactive page element the visitor is currently on.  As they tab through the page, jumping from one element to the next, the visitor has a visual cue of their current location.

The Design System uses a blue outline style to signify a focused state around a component. Focus blue #2491FF meets visibility and color contrast accessibility on both our light and dark backgrounds.

Focus states apply to all interactive components:
- Buttons
- Cards
- Text fields
- Icons
- Selection controls

![focus-state-examples](https://user-images.githubusercontent.com/99768807/174897014-c249606f-15d9-4128-a010-3ac578424b1d.png)

Caption 1: 
Light background
Stroke: 4px
Color: #2491FF
Contrast ratio: 3.2:1 

Caption 2: 
Dark background
Stroke: 4px 

Color: #2491FF 
Contrast ratio: 3.5:1

2. Under “Accessibility” in the third bullet, "Provide visual focus indication for keyboard navigation", add a link to "visual focus indication" that goes to “Focus state(h2)”.

**Comment by yesenia-gtz** [comment]
@zakiya this one is ready for development, please have engineers work with @sharon-rabang to design details

Tasks needed:
- [ ]  update style guide on website
- [ ] ensure figma UI kit aligns

**Comment by yesenia-gtz** [comment]
Issue related to https://github.com/cagov/design-system/issues/755
