### ISSUE TITLE
Bug: Step list has oblong shaped circles around numbers

### ISSUE THREAD

**Issue by chachasikes** [cagov/design-system#703]
Thank you for helping us build a better design system. Fill any of the fields that are relevant to your issue as best you can. 

### Url where issue was found

Reported to DS team by State employee trying Design System on a Sharepoint instance.

### Operating system, device, browser, screen size, etc.

Not available

### Steps to reproduce

Design System team reproduced & recreated the issue in the browser.
* Change body font to `Helvetica`
* Comment out "Public Sans" in `components/step-list/src/index.scss`

We found a fix and will submit it in a PR.

### Expected result

Rounded shapes, no interference with font choice.

### Actual result

Oblong shape

# Screen shot(s) or video capture
![Screen Shot 2022-03-01 at 3 19 47 PM](https://user-images.githubusercontent.com/149436/156269098-d7766e03-9a82-40e4-8214-5b45ff5a2418.png)

**Comment by jaredwyee** [comment]
@chachasikes how should this be verified? Or does another dev need to try and confirm the oblong shape is no longer there in the step list?

**Comment by chachasikes** [comment]
Yes, another dev can help. 
Maybe @zakiya can verify as she is familiar already with this issue.

Steps to verify: 
- In code editor, change the font to be any other font besides Public Sans
- Ensure that the circles do not become oblong 
- Ensure that the font changes in the step list.

**Comment by zakiya** [comment]
This is ok for release but I don't think we can reliably guarantee the shape of the circle using a font other than Public Sans. ![CleanShot 2022-03-10 at 14 44 26](https://user-images.githubusercontent.com/915352/157767585-70e6822b-ccff-473e-92b8-361e470881a9.png)

I tried changing the units from pixels to ems and it didn't help much. I still prefer we take the approach "Webmasters are welcome to use any font. Our components work best with Public Sans." In lieu of that we can advise people to override the padding.

**Comment by chachasikes** [comment]
Glad it's okay for release. Thanks for checking.

For future: Wonder if a min-max or another approach to the circles would help.
