### ISSUE TITLE
Pattern: Cards

### ISSUE THREAD

**Issue by kkoryaka** [cagov/design-system#711]
Create a flexible design system card component based on figma UI kit. It should include options for image, header card content and link button.

### What is card
The card" is a small rectangle associated to a singular thought or topic.  It might have multiple variants and options. The card includes options for for image, header card content and link button. 

### What does it help you do?
Card are interactive element and it meant to engage a user.  Cards goal is to provide an overview of a certain topic in a condensed space and, if the reader is interested, with just one click he or she can open the subject in another page.

### Where does it appear?
Cards can be used on a home page or on a landing page where they can feature a important content topics while saving webpage's precious real estate.

### How should you use it?
Use multiple cards as a group in some king of grid pattern. 

### Name of component
Card

### Machine name
ds-card

### Current version number
1.0.0

### What type of component is this?
- [ ] Visual
- [ ] Content

![Screen Shot 2022-03-07 at 1 02 52 PM](https://user-images.githubusercontent.com/31669748/157117693-a7f2bceb-5125-49b4-b496-b4ff49cb6230.png)

**Comment by yesenia-gtz** [comment]
https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/UI-Design-kit?node-id=0%3A1

**Comment by yesenia-gtz** [comment]
@Angsv  can you work with @sharon-rabang on breaking out the card design to function as a **pattern**? This 

**Needs**

- Design recommendation for various card states
- Breakout components used in card design
- Document usage guidelines for cards
- Document development specs for cards

Target completion: Before end of Q4

Example: 
https://www.duetds.com/components/card/#properties

![Image](https://user-images.githubusercontent.com/98193284/194632640-b3df8420-98a4-40f9-8069-09b3ac0081a6.png)
