### ISSUE TITLE
Developer Tool: Component Packager

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#718]
Provide way to include multiple components or whole system in a single step via script tag or npm install. This documentation should refer to unused css docs and and js trimming instructions

**Comment by yesenia-gtz** [comment]
@zakiya @chachasikes @aaronhans Can we look into how #770 relates to this issue?

**Comment by yesenia-gtz** [comment]
Will need to setup backend to start work in next months sprint.

**Comment by zakiya** [comment]
@yesenia-gtz This and several other issues have been inaccurately tagged as Documentation. This issue is to create a tool that would help developers choose which components they want to include in the their code.

**Comment by yesenia-gtz** [comment]
@zakiya thank you for the clarification and update to the name, much appreciated!
