### ISSUE TITLE
Documentation: Put Wordpress code in a separate module

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#720]
All Wordpress stuff MUST GO. Put it in a separate module.

**Comment by aaronhans** [comment]
I am running into one aspect of this now. This little file https://github.com/cagov/design-system/blob/main/components/base-css/src/_core.scss#L8 has a bunch of WordPress inserted class specific styles. These cause unexpected problems in development.digital.ca.gov posts which are using WordPress headlessly. I don't see any benefit to these rules on that site.

I plan to:
- Remove that wordpress specific include from the base-css component and do major version bump on base-css explaining the removal
- I recommend we do not publish these WordPress specific rules as their own npm package but if a site needs rules like this it should have them in their own css file local to that site.

We still have other WordPress specific css in other components so these changes don't fully address this issue

**Comment by aaronhans** [comment]
tagging @chachasikes @zakiya @xjensen for discussion

**Comment by chachasikes** [comment]
You can move that file out of base-css.

We need a place to store the design system integrations code - for wordpress. 
If they all do cause conflict with DS static sites & use WP core elements & removing them is painless, that would be good

Looking at the `_wordpress` file - most of the custom code that does need styling for core WP features as well as some attempts at making a grid. (Hopefully outdated by now) - I'm open to another repo, or other documentation space, but we don't have that yet for DS integrations & really really need to make a space that can be shared by many & is easy to find. Maybe spec'ing out what we need from that will be a good place to start - but including support files for WP Core that sneaks into sites using WordPress REST API & out-of-the box core WP blocks (such as buttons, columns, anchor links & anything else that may have non-standard markup - would be good until we can override the WP output. 

@aaronhans if you can let us know if any features are critical for existing site layouts that will be helpful - but as is there are needed on some of the sites & also are inheriting conflicts from the CAWeb CSS space (making everything much more difficult to suss out)

Recommend we continue to focus on a clear & validated HTML/CSS/web component spec for Design System - the more clear we are with that, the easier it is for developers doing integrations to align and simplify the systems. 

🐛 There is a CSS bug here - no end brace. 
https://github.com/cagov/design-system/blob/2f0544c7fb10b37af37518e1ea4c53015eaaca3b/components/base-css/src/_wordpress.scss#L55

**Comment by yesenia-gtz** [comment]
Per @aaronhans  we will be removing any wordpress specific css from design system code.
