### ISSUE TITLE
Bug: Keep yalc from triggering prepublishOnly hook.

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#721]

**Comment by zakiya** [comment]
Un-assigning myself so my Issue list is current. Feel free to assign to me when/if it leaves the backlog.

**Comment by zakiya** [comment]
Locally when using yalc to manage packages, yalc publish will trigger the pre-publish hook which also publishes the package to npm. 

The work around is to use `yalc publish --no-scripts` but it's an easy thing to forget.

**Comment by xjensen** [comment]
PR ready at #925.

**Comment by zakiya** [comment]
Since there isn't an elegant solution here, I'm going to close it.
