### ISSUE TITLE
Components: delete abandoned components

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#722]
There are some component directories in this repo that we used to use but no longer do. These should be removed:

- google-translate (Make sure this isn't used in any other projects. If it is move the component to that project)
- plus & minus (no longer used in latest version of accordion)

**Comment by aaronhans** [comment]
Yeah, plus and minus have already been removed.

The google-translate component and the following references can be deleted https://github.com/cagov/design-system/search?q=google-translate to complete this task

**Comment by xjensen** [comment]
Served hot and fresh: #918.

**Comment by xjensen** [comment]
Merged into the 1.0.10 release, and published to NPM. This can be closed.
