### ISSUE TITLE
Page Feedback for Broadband site

### ISSUE THREAD

**Issue by jaredwyee** [cagov/design-system#732]
**Goal:**
Enable Page Feedback widget for https://broadbandforall.cdt.ca.gov/

**Background:**
The Page Feedback widget is still in early stages as a "productized" offering to provide to other state entities. This is primarily due to the need to vet how we might deliver a full service product with the API, database storage, data cleaning, and access to reporting aspects. 

OET/CDT's recently stood up Broadband For All site is an opportunity to carefully increase the usage of the Page Feedback widget while we keep assessing the overall system involved to make it successful and eventually scale up to a broader set of state sites.

**Requirements:**
- [ ] Setup API layer for Broadband site so that the UI component can be added to the broadband site
- [ ] assist broadband site frontend team with integration
- [ ] update inbound endpoint to use a friendly domain name
- [ ] Coordinate with Syntasa on the data flowing into GCP BQ
- [ ] Setup Google Data Studio template for Broadband site
- [ ] Determine approach users to invite being mindful of access management
- [ ] (Jared) Clarify PII and data access aspects to end user team

**Comment by jaredwyee** [comment]
@aaronhans I took a stab at this. Can you clarify high-level requirement steps or point me to a prior example.

@extinah FYI

**Comment by aaronhans** [comment]
Good set of steps. We haven't documented this yet. I'd like to add:

[] update inbound endpoint to use a friendly domain name
[] assist broadband site frontend team with integration

**Comment by jaredwyee** [comment]
Thanks, added to original comment

**Comment by extinah** [comment]
@yesenia-gtz  Oops here is this one.
