### ISSUE TITLE
Issue: Component workshop

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#739]
- Better workshop (as opposed to showroom) tools for developing components.
- Would be good to have a place independent of base-css to test how components react to theme changes.

**Comment by zakiya** [comment]
https://incredible-madeleine-8c4f8a.netlify.app/
https://github.com/zakiya/odi-ds-content-tests

- [ ] link icon - instructions don’t work, the fonts aren’t loaded or referenced
- [ ] page-alert - looks like latest hasn’t been published to npm (template.html was updated)
- [ ] page-navigation - not sure what kind of markup is needed to make this work
- [ ] skip to content - needs content to skip to
- [ ] statewide footer - links are not inline

**Comment by yesenia-gtz** [comment]
Still in progress, @zakiya can you update with status?

**Comment by zakiya** [comment]
The comment above references the remaining items.

**Comment by zakiya** [comment]
I"m going to move this to Done. I'll will create new ticket as more needs arise for the workshop.
