### ISSUE TITLE
document our jsdoc patterns

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#74]
We are doing some cool things with jsdoc comments now.

Assigning to @carterm first so he can document the ts-check setup he has working now that he uses in his code.

Once we've got the instructions and reasoning behind Carter's practices documented we can reassign to Aaron to augment this with the jsdoc patterns used in order to generate custom elements manifest files. Here is an example: https://github.com/cagov/design-system/blob/main/components/pagination/src/index.js#L7

This is an information collection ticket that will become part of the component development documentation

**Comment by chachasikes** [comment]
This should be tagged on odi-engineering.

**Comment by chachasikes** [comment]
but we can't connect it.

**Comment by chachasikes** [comment]
Is this done?
