### ISSUE TITLE
Documentation: Dependabot

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#740]
Would be good to have training materials for how to use dependabot with our packages. Describe our recommended settings: Auto merge minor version bumps, open PR but do not auto merge major version updates

**Comment by yesenia-gtz** [comment]
To be  completed by 4/22

**Comment by aaronhans** [comment]
That sounds perfect @zakiya

Thanks for noticing it isn't enabled yet on the design system site too, we should enable it

**Comment by aaronhans** [comment]
Yeah it is a constant thing to keep up with and could occasionally notify us of something urgent we need to do immediately so will be good to rotate responsibilities but somebody has to keep an eye on it. Maybe the release ranger can review open dependabot PRs and assign a task for upgrades

**Comment by zakiya** [comment]
I like that.
