### ISSUE TITLE
Patterns: Animations for Components

### ISSUE THREAD

**Issue by Angsv** [cagov/design-system#743]

**Comment by jayliquek** [comment]
Hihi I played around with a hover animation on a card so it would be more noticeable for users that it is a clickable component. 
The current animation right now shows the cursor changing and users have to click on the title to go to the next page shown here

https://user-images.githubusercontent.com/45698971/162263732-73972a31-c819-4a5c-964f-76b1ee7810ca.mov


## Changes made and suggestions
I played around with the card component animations and would love some feedback. 

**On the [component page](https://designsystem.webstandards.ca.gov/components/)** 

https://user-images.githubusercontent.com/45698971/162263913-171e8045-f251-4bd5-8ee9-6f23c27f4c40.mov

on the component page upon hovering, the card highlights has an overlay effect. 

**On the main page**


https://user-images.githubusercontent.com/45698971/162264142-0467de5f-e6b0-4cf8-bf8d-16e5cc0553c6.mov

Similar to component page, for each card there is a hover effect. 

I would love to get your feedback on hover effects on component page versus the main page. 

Might look slightly inconsistent especially with the hover effects on the cards below on the bottom of the page. Maybe is there a way to add a limitation for particular cards have a hover animation? Would love your thoughts on this!

**Comment by yesenia-gtz** [comment]
Moving into next sprint.

**Comment by yesenia-gtz** [comment]
@Angsv need to document animation guidelines for design system and components to share with NYU partners.

- [ ] Documentation by end of week 4/15 @Angsv 
- [ ] Share documentation with NYU partners 4/22 
- [ ] @aaronhans Need to make tickets as appropriate

**Comment by Angsv** [comment]
@jayliquek 

I like that you are thinking about the card as a single element in your example for the main page cards. The hover effect for the component cards is a bit too disjointed and may cause confusion for some. I would encourage consistency for all card components to follow the same effect. However, there is talk about making certain cards distinct from the rest. 

The hover overlay is a good animation to have because it provides a visual cue that this is an interactive object on the site, making it especially accessible for those who have learning and/or cognitive impairments.  However, the grey may be too dark for those who have low vision to be able to see the text clearly when hovering.

**Comment by jayliquek** [comment]
Thanks for the feedback @Angsv !

Will possibly look into creating consistency of the hover overlay among all cards and try out the colors for it to be more accessible. 

Otherwise might try some other explorations!

**Comment by yesenia-gtz** [comment]
need to audit components, moving to backlog.

**Comment by yesenia-gtz** [comment]
@zakiya  @Angsv  this is completed, need to understand where we should share/publish this documentation. How have we done this in the past? @kkoryaka mentioned integrating design tokens. can we workshop this one?

**Comment by zakiya** [comment]
- We should keep design resources in Figma for reference. I'm unclear if that part has been done.   
- If there are specific components or webpages that need to be updated, let's create an issue for engineering. 
- It is probably also a good idea to add an "Animation" section [on the Visual Design page](https://designsystem.webstandards.ca.gov/style/design/)
