### ISSUE TITLE
Patterns: Site navigation organization to accommodate new pages and new content

### ISSUE THREAD

**Issue by kkoryaka** [cagov/design-system#744]
The [Visual design style guide](https://designsystem.webstandards.ca.gov/style/design/) page is getting too long. And with more of documentation content coming to the color and buttons  sections we will need to break that page appart. 
Propsed new pages are:
Color
Buttons
Typography

We need to restructure our site navigation to include those pages.

![Screen Shot 2022-03-15 at 4 12 27 PM](https://user-images.githubusercontent.com/31669748/158487269-d84658d9-7e56-4370-a19d-00640b288ab3.png)

**Comment by m-sullivan7** [comment]
I'd like to bring @adam-little and @kmbrlygl into this discussion as they own this page before I get into solutions, including impacts to the navigation. Adam, before I start thinking about information architecture and the menu, what should we think about?

**Comment by adam-little** [comment]
After chatting with @kmbrlygl about breaking the [Visual Design Style Guide](https://designsystem.webstandards.ca.gov/style/design/) into multiple pages, we see two approaches:

A. Put them in the "Style guides" dropdown.
B. Create subpages that exist _below_ a Visual Design landing page.

The latter approach is consistent with how pages are organized in the [Content Style Guide](https://designsystem.webstandards.ca.gov/style/content/). 

As pointed out in [Issue 402](https://github.com/cagov/design-system/issues/402), that approach is not ideal. But if we use a navigation component similar to the [Components](https://designsystem.webstandards.ca.gov/components/) page, then I think we can make it better.

**Comment by adam-little** [comment]
Here's an example of how that component can be used to improve the Content Style Guide

![Content style guide - landing page](https://user-images.githubusercontent.com/69167298/158675595-6dee470e-9fc7-4bf7-816f-b7ad93c2c529.png)

![Content style guide - principle](https://user-images.githubusercontent.com/69167298/158675631-4c08a0f6-6297-4c69-8601-c0592c4bcc02.png)

**Comment by adam-little** [comment]
Here's an example of how it can be used to break apart the Visual Design Style Guide into multiple pages

![Design style guide - landing page](https://user-images.githubusercontent.com/69167298/158675721-02ca0c80-250d-4bac-9632-6cdfb0f5a1ef.png)

![Design style guide - typography](https://user-images.githubusercontent.com/69167298/158675743-b1cb7dbe-8f2d-4098-81b0-1147bc3a3393.png)

**Comment by m-sullivan7** [comment]
I like the navigation component in the screenshots, coupled with option B of not including those pages in the site menu.

**Comment by yesenia-gtz** [comment]
@Courtney-Chittock can you lead this based on the state template navigation design that was done? good one to review and inform to get the design system updated.
