### ISSUE TITLE
Add latest web releases to be showcased on website (BB4A, and others)

### ISSUE THREAD

**Issue by yesenia-gtz** [cagov/design-system#746]
We need to add a section to the design system website to showcase recent adoption releases. Suggest we showcase most recent releases under "Who's using the Design System" and add a gallery section for all implementations. 

**Please include the following websites, listed by priority:**
1. https://broadbandforall.cdt.ca.gov (Primary showcase)
2. https://drought.ca.gov/
3. https://cannabis.ca.gov
4. https://covid19.ca.gov (nice to have, but not priority)

**Comment by m-sullivan7** [comment]
@ashleydraper and @extinah as the primary content people for Broadband for All, are you aware of anything about that Design System implementation worth mentioning when we feature this site on the Design System homepage?

**Comment by adam-little** [comment]
For design team reference: this issue relates to https://github.com/cagov/design-system/issues/559. We can work on both simultaneously.

**Comment by m-sullivan7** [comment]
@extinah Sounds like a pretty standard implementation (which is not a bad thing). How about we approach it from a "this was easy to set up and looked great" angle? If that's not accurate...then we won't use that approach. 🙂 

I've also asked the ODI engineers if they can send me the performance dashboard we have. I'm interested to see where Broadband for All comes in!

**Comment by extinah** [comment]
@m-sullivan7  the performance is no bueno lol. It's in WP that's completing with the existing template and the WP bloat - but go forth! :)

**Comment by yesenia-gtz** [comment]
@m-sullivan7 @adam-little I will open a separate issue for the gallery option, for now lets swap out Covid for BB4A as we are being asked when it will be completed by Rick.

cc: @artuoma

**Comment by m-sullivan7** [comment]
@yesenia-gtz Can you point me to someone who can help me with the content? I'm looking for information about how the Design System made for a better Broadband for All site. My inquiries thus far on that point have not turned anything up.

**Comment by m-sullivan7** [comment]
Thank you @extinah and @ashleydraper ! That's just what I needed!

@yesenia-gtz Thanks to the information above, here's what I propose for the content to accompany the homepage feature.

> Homepages are often the hardest part of a website to make. The Design System components let the Broadband for All team focus on content, not engineering. The principles aligned the team around a foundation for the content and design of the site.

Think that will work? If so, I'll have a screenshot soon and can make updates later today (assuming I get in before code freeze).

**Comment by ashleydraper** [comment]
@m-sullivan7 I am also going to bring this up during our team sync this morning. The Broadband for All site utilizes a bit of API and features a couple different tables, I think it would be helpful to gather our developer's points of view of how the design system helped their efforts or not.

**Comment by ashleydraper** [comment]
What time is code lock?

**Comment by yesenia-gtz** [comment]
New issue added to backlog for gallery: https://github.com/cagov/design-system/issues/760

**Comment by yesenia-gtz** [comment]
@adam-little  @ashleydraper Can we please have image and content completed and ready to add to this release by noon?

**Comment by yesenia-gtz** [comment]
> Here's a screenshot of B4A
> 
> <img alt="Group 60" width="466" src="https://user-images.githubusercontent.com/69167298/159763001-1434897d-72a2-43fc-aeb6-9a0ea7dd5e64.png">

Thank you!

**Comment by extinah** [comment]
@yesenia-gtz  michael wants you to review and approve the content.
@ashleydraper  the tables could've used design system help but there isn't a table component yet. :( Hopefully soon!

**Comment by yesenia-gtz** [comment]
> Thank you @extinah and @ashleydraper ! That's just what I needed!
> 
> @yesenia-gtz Thanks to the information above, here's what I propose for the content to accompany the homepage feature.
> 
> > Homepages are often the hardest part of a website to make. The Design System components let the Broadband for All team focus on content, not engineering. The principles aligned the team around a foundation for the content and design of the site.
> 
> Think that will work? If so, I'll have a screenshot soon and can make updates later today (assuming I get in before code freeze).

This is approved, thank you @m-sullivan7

**Comment by ashleydraper** [comment]
@m-sullivan7 @Courtney-Chittock Looking for feedback on this language. If it works for the homepage blurb, then I'd like to get it to Konstantin before the noon cut off.

_The Design System allowed the Broadband for All team to plug-and-play with components on the homepage. With less time spent on engineering, the team could focus more on content and design._

**Comment by yesenia-gtz** [comment]
Thank you for getting this one added! Very much appreciated. Good to go!
