### ISSUE TITLE
Fix "State of California" label on statewide header

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#748]
Currently, the statewide header displays "State of California" on desktop.

It should display “Official website of the State of California” (on desktop) or “State of California” (on mobile).

This makes it less redundant with the site header and more explicitly tells people that the website is an official product of the State of California, which increases user trust.

See documentation [here](https://designsystem.webstandards.ca.gov/components/statewide-header/readme/).

**Comment by alexhu00** [comment]
https://codepen.io/alexhu00/pen/QWambGp

@aaronhans @adam-little 

Would something like this suffice? Mainly added CSS like the snippet below so that it says “Official website of the State of California” when the screen width is larger than 800px and “State of California” when the screen width is less than 800px

```
@media screen and (min-width: 800px) {
  .desktop-only {
    display: inline;
  }
}
```

**Comment by adam-little** [comment]
@alexhu00 this is the desired behavior. Thanks! I noticed that it's not the correct font, but I assume because this is just a  prototype.

I'm assigning this issue to @aaronhans to give you feedback on technical approach..

**Comment by aaronhans** [comment]
Right @alexhu00!

**Comment by aaronhans** [comment]
Great work on this @alexhu00! This update is live on the production design system site now.

I'll publish the latest version of the package to npm

**Comment by adam-little** [comment]
Thanks, @alexhu00! 

@aaronhans i'm noticing some cosmetic issues with the new version.

1. Can you make the background color gray-50 (#FAFAFA)?
2. I see a bottom border. Can we either remove this? Or make it the same color as the background (gray-50)?
3. Top border - it looks like there's a 1px white border or 1px of empty space above the banner. Can you remove this?

Here's the Figma link: https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/UI-Design-kit?node-id=432%3A5905

**Comment by yesenia-gtz** [comment]
will be ready for next release.
