### ISSUE TITLE
April DWSN: DS Design updates / insights slides

### ISSUE THREAD

**Issue by yesenia-gtz** [cagov/design-system#752]
Collaboration between Art, Adam and Sarah.
Prepare DS Design updates / insights slides for a 10 min segment during the April 21 DWSN at 10am. 

- Showcase new websites using design system
- Updates to components
- Ability to install components individually and as custom bundles
- More easily integrate into requested tools like web-pack
- Improvements based on feedback: ex. We successfully responded to a good suggestion from a web developer at FTB. We released a major rewrite of one of our components based on that feedback which improved progressive enhancement
- [Work with Research on details] Include CTA/Poll  - Understanding Component needs for future work 
- 
**Final slides due by: April 7, 2022**

Draft Presentation Deck:
https://docs.google.com/presentation/d/1CtmO-eVORamDetepZNHv_VcmImCY7dYLMkW7wyCAQr8/edit#slide=id.g11d4a91cd2f_0_7

**Comment by adam-little** [comment]
The latest draft is organized by discipline. Have we settled on that as the right approach? 

I see some pros and cons (particularly if Design System updates will be a regular feature of DWSN):

Pro: Makes it easier for our team to divide responsibility
Pro: Ensures that we are respecting the contributions of everyone on the team
Con: Less product focused - makes it harder to answer the question: _What do users of the design system need to know right now?_
Con: Could lead to repetitive or disjointed storytelling - For example, if we want to tell the story of a component release from research to launch, then that story might be spread out across the whole presentation. 

A more product-centric outline could be:

1. **Site launches** 
- Put a spotlight on the sites/products that have used the design system
- It's not about our team, it's about the work being done by teams across the state

2. **Latest release updates** 
- Update people about the latest changes and share the story behind it 
- E.g. With input from a developer at FTB, we did a major rewrite of the accordion component

3. **What's coming** 
- Provide insight into what we're currently working on and what can be expected in upcoming releases

I might be biased by the USWDS monthly presentation I attended yesterday. They followed a similar agenda and I thought it was really easy to follow. All of the updates were in the context of specific releases/changes.

**Comment by yesenia-gtz** [comment]
@adam-little love this breakdown, thank you for the thoughtful approach as we have have not yet finalized talking points and this makes a lot of sense. I suggest a workshop to build up the presentation in this format. I will schedule it for the group.

**Comment by yesenia-gtz** [comment]
@extinah @ashleydraper CCing for awareness
