### ISSUE TITLE
Contact request: Would love to contribute to project! 

### ISSUE THREAD

**Issue by jayliquek** [cagov/design-system#754]
Hello! 

We're seniors in an Open Source class at New York University. We have some experience with design systems and would love to help contribute to this project! 

We noticed that are a few issues we would love to help out with such as [animations](https://github.com/cagov/design-system/issues/743) but don't have any description. Are there any other issues that you could point us to that could be of help!

**Comment by alexhu00** [comment]
Hello! My name’s Alex, I’m from Toronto, and I’m a senior at NYU Stern studying Business and Computer Science. I am also part of the Open Source class at New York University and would love to contribute to this project if possible!

**Comment by yesenia-gtz** [comment]
@aaronhans Moving this issue to done since we are working on issues :)
