### ISSUE TITLE
Website: DS Gallery section for all implementations

### ISSUE THREAD

**Issue by yesenia-gtz** [cagov/design-system#760]
Need content strategy and design guidance for adding a website gallery section for all Design system implementations to our website.

Please include the following websites:
https://broadbandforall.cdt.ca.gov/
https://drought.ca.gov/
https://cannabis.ca.gov/
https://covid19.ca.gov/

**Comment by yesenia-gtz** [comment]
added @kmbrlygl  for Visual Design

**Comment by yesenia-gtz** [comment]
Hi team, Rick shared some ideas on how to approach a gallery section long term. Adding here for consideration and discussion.

**One thought -- you could imagine this growing to dozens​ or more in the months/years ahead. A streamlined (possibly even automated) way of surfacing / discovering / incorporating these would be great. 

Brainstorming:
A 'registry' in the CA Design System github repo that anyone deploying the design system would submit to, listing their URL, pointer to a thumbnail image representing the site, name, etc.

I suspect this would best be represented as a lightweight XML file that becomes part of the new site's fork / deploy
we wouldn't want to auto-publish any sites that write to the registry, but have an approval queue that one of the design system reps would approve submissions.

Final step would be for the Design System website to auto-generate a gallery by pulling / parsing the XML files from the 'approved' bucket. 

 I realize this may seem like over-engineering the solution for a situation where we have ~4 examples. But in a world where we have a new site a week, you could imagine the manual maintenance of this could become quite onerous.

--Rick**

**Comment by m-sullivan7** [comment]
@ashleydraper Remind me: would this work be in your court to start?

**Comment by Courtney-Chittock** [comment]
@m-sullivan7 we have a kickoff meeting tomorrow at 11. You should have an invite.

**Comment by m-sullivan7** [comment]
@Courtney-Chittock No invite on my side. As it is, I have a conflict at 11:00. If @ashleydraper is the primary content person, it should be OK for me to not be there.

**Comment by Courtney-Chittock** [comment]
Oh snap, I didn't send it yet as I was waiting to hear back from you. If you're ok missing we can keep the Wednesday. If you prefer to be involved reach out to me on Slack and I will reschedule. :)

**Comment by ashleydraper** [comment]
@m-sullivan7 Good thought on this question, it would make sense! I've not heard much about this gallery piece and would need a bit of orientation to what we're tasked with. Happy to join you both on Wednesday.

**Comment by m-sullivan7** [comment]
@yesenia-gtz I discussed this work with @ashleydraper. In keeping with our previous conversation, we recommend that Ashley run point on Design System content. As such, we propose that she attends this design review. She'll scope the work and decide if it's a one-person or two-person job (bringing me in for the latter case). Does that sound like a plan, or was there something in particular you thought would benefit from my presence that we're missing?

@Courtney-Chittock For now proceed without me (but if the meeting is on Wednesday and not Tuesday, I could actually make that).

**Comment by Courtney-Chittock** [comment]
@m-sullivan7 I moved it to Wednesday because Adam also can't make Tuesday and I would like ODI representation. I'm waiting to hear back from Adam if he can make Wednesday.

**Comment by yesenia-gtz** [comment]
> @yesenia-gtz I discussed this work with @ashleydraper. In keeping with our previous conversation, we recommend that Ashley run point on Design System content. As such, we propose that she attends this design review. She'll scope the work and decide if it's a one-person or two-person job (bringing me in for the latter case). Does that sound like a plan, or was there something in particular you thought would benefit from my presence that we're missing?
> 
> @Courtney-Chittock For now proceed without me (but if the meeting is on Wednesday and not Tuesday, I could actually make that).

Sounds like a plan to me, thank you @m-sullivan7
