### ISSUE TITLE
Documentation: Web components

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#769]
We get questions from potential design system consumers on what are web components, why we made those decisions.

We have good reasons for this which we should describe in our design systems documentation:

Why we chose web components
What are the advantages
How you can create your own web component
Links to additional resources

**Comment by aaronhans** [comment]
Here is a draft document explaining what we are up to with web components in the design system:

# Web components

There is a component model built into the browser now. The design system takes heavy advantage of the custom elements part of the web components specification. This allows us to define new HTML tags like <cagov-accordion> or <cagov-feedback> which we can use in our pages and are inert until upgraded by provided javascript.

## Why bother with web components?

### Web components work anywhere

They are [supported by all frameworks](https://custom-elements-everywhere.com/) and you get this component model with its API built into all browsers. If there is still a need to support IE there is a polyfill available. We use @webcomponents/webcomponentsjs on the covid site.

### Using web components helps ensure longevity of code

Preferred web stacks evolve. It is common for mature organizations to currently be maintaining applications written in a variety of frameworks. Each rewrite or new launch is an opportunity to update codebases to the “modern approach” but that changes over time. Web components allow us to take our frontend widgets off this treadmill. Features which are standardized and built into all browsers are supported forever. We aren’t subject to breaking changes in new versions of frameworks or the whims of developers who prefer not to write widgets using an older methodology.

### Components encapsulate code

The code for each widget is within the custom element class. We have some protection from accidentally influencing global variables by following component patterns which keep our variables local. The custom element API provides a clear interface for interacting with the rest of the application. It receives events responding to instantiation, removal and attribute updates.

### Easier component management

Using a component model and publishing each component individually lets us take advantage of separate versioning. Our site owners are in the update loop receiving dependabot notifications of available updates to each npm package. This comes with associated semver compliant version numbers and published changelogs which they can evaluate to can decide if they want to upgrade or ignore the change on their own timeline. A single component can be added, upgraded or removed easier than code which is intertwined with the rest of a site.

## When are web components appropriate?

We only need web components when we need javascript. We don’t always need javascript. If HTML and CSS provide the desired features that is all a component uses.

We still need to progressively enhance functionality. We can’t depend on web components being supported on a visitor’s device even if they work in the latest version of all browsers. Older devices get locked out of update cycles and people avoid freely available software updates. Components which are critical for users like accordions have always been progressively enhanced. Now those elements use details and summary elements so their content can be read even if the javascript fails to execute and the visitor doesn’t get the advantage of extra styling or open/close animations. Some components are not critical to a site’s mission. We haven’t made the feedback widget at the bottom of site pages progressively enhanced yet because it is not why people are visiting the page. That element will not be visible unless the visitor’s browser successfully executes its code. We use script type=module so if a very old browser is being used that code will not even be delivered.

## How do they work in practice?

We are using plain custom elements. This doesn’t preclude us from depending on advanced base classes but we are getting a lot of mileage out of the supported API now.

Web components help limit development to the local scope of the custom element. You also get good [lifecycle tools](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#using_the_lifecycle_callbacks) for building up and tearing down JS features; in other words, no waiting for "DOMContentLoaded" or any other old hacks
Applying CSS only to instantiated elements
We can use the :defined CSS selector to apply styling rules only when the custom element’s javascript has run. We are importing and delivering this CSS as part of the javascript package because it is only used in the js powered version o the component

### Custom events

We often communicate between components with custom events. This isn’t a web component specific tool but it works nicely with any DOM element including our own custom elements ([MDN custom events docs](https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events)). We have a reusable county search box component on covid site pages that fires events with county details when a visitor chooses from the autocomplete list. Chart components on that page that need to respond to county state changes can subscribe to the custom event fired by the search custom element and update its data as needed.

### Lots of other ways to communicate data between components

The lifecycle callbacks responding to attribute changes require that information being passed in as attributes be strings. This limitation of the built in callbacks has drawn some criticism. There are many workarounds. A custom element is able to be assigned an object in the DOM via: meElement.bigOjbect =  myJSON. This can then be referred to inside the component via this.bigObject.

We have integrated components into a site’s underlying translation infrastructure by passing translated DOM nodes as interior HTML. This is consumed by complex elements like charts that need different strings for tooltips and legends. We use this pattern with our 11ty static site generator that builds a different version of each HTML page for each language we support. Then the charts on that page receive their translated strings in the page HTML.

**Comment by aaronhans** [comment]
@jayliquek you mentioned you were interested this documentation. Here is a draft. Any suggestions?

**Comment by jayliquek** [comment]
Hey Aaron, 
Thanks for looping me in on this! 

I had a read through and everything looks great. I wanted to add in at the top with "What is a web component" section which would lead up to your section of the advantages of components. I tried to break it down as simple as possible, so it would be approachable to new developers and designers wanting to work on a design system. Would love to hear your thoughts! The edit is below: 

### What is a web component? 

A website is made of different types of components (e.g a button, a card, a hero banner).

- Button component on CA GOV's design system website
<img width="189" alt="button_component" src="https://user-images.githubusercontent.com/45698971/161460137-38fcb01c-78ff-4d8e-8cb8-f1fc39ab5ff7.png">

- Several card components being used on CA GOV's design system website
<img width="962" alt="card_component" src="https://user-images.githubusercontent.com/45698971/161460240-12752c4e-221f-4be8-b3e6-effb5d7cb46a.png">

- Hero banner component on CA GOV's design system website
<img width="1097" alt="hero_component" src="https://user-images.githubusercontent.com/45698971/161460252-e9651d28-98bb-45ab-a075-cd7ceb974a02.png">

In some cases, components can be embedded in other components. For example, the button in the hero banner. Similar to lego bricks, components are bite-sized sections of code that are interlinked together to create a website. Often uniform and re-usable, components help developers and designers save time in re-writing redundant code, and is easily able to be plugged in and out of code using html tags.

**Comment by chachasikes** [comment]
Especially "components are bite-sized sections of code that are interlinked together to create a website"

**Comment by aaronhans** [comment]
Great addition @jayliquek! Helpful to get your perspective on this. I have integrated your suggestions into a new draft and we'll have our editorial team review it

**Comment by jayliquek** [comment]
Awesome to hear!

**Comment by m-sullivan7** [comment]
@aaronhans Let me know when you're ready for content design review. This is on my list and I'm ready to activate when you are. 🙂

**Comment by m-sullivan7** [comment]
@aaronhans I finished my content design review. I'm handing the assignment back to you, but am happy to do additional work if needed. 🙂

**Comment by ashleydraper** [comment]
@aaronhans I'll be carrying this task across the finish line, so I'd to your take on this navigation recommendation.
![image](https://user-images.githubusercontent.com/62437425/163869625-6886ee40-3180-41c6-b0be-a7e0cd429a35.png).

Michael shared with me this [Github link](https://github.com/cagov/design-system/blob/main/docs/site/homepage.njk) to update the homepage, if this looks good to you, I can add it here.

**Comment by aaronhans** [comment]
Thanks @ashleydraper! I love that placement. I'd like the title to be "Why web components" specifically because there has been confusion about why we are basing development on the custom elements part of the W3C's v1 web components specification.

**Comment by ashleydraper** [comment]
@aaronhans How do you feel? We good to close this out?

**Comment by aaronhans** [comment]
Yes! I just merged our PR https://github.com/cagov/design-system/pull/802

Thank you @ashleydraper!

**Comment by ashleydraper** [comment]
#Teamwork!!
