### ISSUE TITLE
codepen prototyping instructions

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#777]
When chatting with contributors we discovered it would be helpful to have more instructions on how to contribute to interactive prototypes via codepen

**Comment by aaronhans** [comment]
Here is a good article on working with codepen in general: https://dequeuniversity.com/rules/axe/3.5/link-name

Here are some sample pens the team has been sharing with each other to get feedback:

https://codepen.io/rkojik/pen/MWoeJwV
https://codepen.io/aaronhans/details/ZEaEagR

Codepen is a great tool to prototype a small widget like a component in isolation. When building the new version of the accordion I copied the HTML and CSS from the current component then applied the new HTML structure we were discussing along with the completely new javascript version to verify it could run successfully as described.

**Comment by aaronhans** [comment]
@alexhu00 is the above helpful codepen information, were you looking for something else?

**Comment by alexhu00** [comment]
@aaronhans Thank you this is helpful!
