### ISSUE TITLE
deprecate @cagov/ds-feedback on npm in favor of @cagov/ds-page-feedback

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#778]

**Comment by aaronhans** [comment]
FYI @yesenia-gtz this task is not done. This page https://www.npmjs.com/package/@cagov/ds-feedback should be marked as deprecated and redirect visitors to the latest name of the component here https://www.npmjs.com/package/@cagov/ds-page-feedback

**Comment by yesenia-gtz** [comment]
@aaronhans thanks for the heads up, is this task something you are able to work on? If so, I will reopen it. Can you give me an estimate on time commitment for having this completed? Otherwise, I will keep it closed and if it is important enough it will make its way back to the project.
