### ISSUE TITLE
Styles: Icons

### ISSUE THREAD

**Issue by Courtney-Chittock** [cagov/design-system#779]
Currently the icon font collection is not complete (in Figma), and is not organized in a usable way. 

Improvements will include:

- [ ] Add all icon font icons to the UI KIt in Figma.
- [ ] Make the library more usable (consider labels, groupings, pagination, search, etc.)
- [ ] Make sure all icons are centered in their containers (spot check shows that many are not).
- [ ] Convert all icons to Figma components.
- [ ] Update the DS website as needed.
- [ ] Make icon library searchable. 
- [ ] Demonstrate color and size changes. 
- [ ] Provide zip of all icons for designers
- [ ] Remove link from icon name in Icon Library like: 
       zoom-out.svg
       [Download](https://608-icons-11ty.pr.designsystem.webstandards.ca.gov/cagov-icons-svg/zoom-out.svg)

**Comment by adam-little** [comment]
This plugin will be helpful: https://www.figma.com/community/plugin/836508016102947880/Batch-Create-Component
