### ISSUE TITLE
Issue: Generic DS Contact form response

### ISSUE THREAD

**Issue by yesenia-gtz** [cagov/design-system#781]
We need to pause on scheduling calls based on the design system contact form and take time to strategize a plan for communications. This was a big take away during the retro and It makes sense to hold. There is no urgency to respond to ALL inquiries at this time.

**Needs:**
- [ ] Generic DS Contact form response 
- [ ] Configure response in Airtable to send automatic replies.

https://airtable.com/app4B5KqaCTSHAdCS/tbliV5kSgz7jBnIyT/viwDkwTUo3wZOqYhF?blocks=hide

![Screen Shot 2022-04-06 at 9 23 01 AM](https://user-images.githubusercontent.com/98193284/162021800-fd02c723-c2cc-4156-bc9c-9657caadcae1.png)

**Comment by ashleydraper** [comment]
@yesenia-gtz Thoughts on this draft of a [generic DS contact form response](https://docs.google.com/document/d/1A3aeYZUNMxeIPOxk3T0sCnZJFlbXBg73MJW7Y6ZjujE/edit)?
Cc: @chachasikes

**Comment by yesenia-gtz** [comment]
@ashleydraper  I added a suggested response in a comment, please edit as needed, Thank you for having this ready so Quickly!

**Comment by ashleydraper** [comment]
@yesenia-gtz I incorporated your suggested sentiment in this version. How's this read?

[generic DS contact form response](https://docs.google.com/document/d/1A3aeYZUNMxeIPOxk3T0sCnZJFlbXBg73MJW7Y6ZjujE/edit)

**Comment by yesenia-gtz** [comment]
Thank you, this works well. Can you work with Chach to get this into the airtable form?

**Comment by ashleydraper** [comment]
Sure can.

**Comment by ashleydraper** [comment]
@chachasikes How/where would you like me to integrate the form response in [airtable](https://airtable.com/app4B5KqaCTSHAdCS/tbliV5kSgz7jBnIyT/viwmmpW1gGgwnBQQd?blocks=hide)?
