### ISSUE TITLE
Sunset CA Design Handbook

### ISSUE THREAD

**Issue by ashleydraper** [cagov/design-system#783]
Sunset the [CA Design Handbook](https://handbook.digital.ca.gov/design/style-guide.html) and fold in it content with the CA design system

**Comment by ashleydraper** [comment]
@artuoma Adding this issue so that we can sunset the CA design handbook when the time comes.

**Comment by jayliquek** [comment]
Hello! 

Not sure what the timeline of sunsetting the CA design handbook is but I looked into similarities and  added comments on compilation of CA design handbook into the current CAGOV [get started tab](https://designsystem.webstandards.ca.gov/get-started/). 

Hopefully this is helpful! You can find the flows, similarities and comments [here](https://www.figma.com/file/x1KWFgdibBgLCsiEy9Ojfy/CAGOV-Sunsetting?node-id=0%3A1)

**Comment by ashleydraper** [comment]
@jayliquek There wasn't a definitive timeline given for sunsetting the handbook, but I'm thinking after the V6 release of the state template. Thoughts on this @artuoma?
The idea is to replace the handbook with the design principles on the design system so that we don't have duplicative info, but a confirmation on timing would be helpful.

**Comment by m-sullivan7** [comment]
This handbook was started by ODI to capture some of our guidance. I sunset the [content portion](https://handbook.digital.ca.gov/content/) once the Design System site launched. Adam and Aaron could have ideas about sunsetting the design and engineering sections, respectively.

**Comment by ashleydraper** [comment]
@m-sullivan7 Very helpful to know. Thank you for commenting.
