### ISSUE TITLE
Statewide footer: Make links inline by default

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#791]
When viewed outside of the design system following our installation instructions, the Statewide footer looks like this:

https://incredible-madeleine-8c4f8a.netlify.app/ds-statewide-footer.html

<img src=https://user-images.githubusercontent.com/915352/163018766-e18bfd62-fc16-4734-92b8-569f4cf79e0e.png>

The links on the left should be inline by default.

See #739 for more context.

**Comment by alexhu00** [comment]
@zakiya Wanted to get more context on this issue? Are the links not already inline by default?
<img width="810" alt="Screen Shot 2022-04-14 at 1 02 40 PM" src="https://user-images.githubusercontent.com/46389157/163438190-b7c08efc-f50c-49ae-ab30-5d882b11dee5.png">
<img width="1216" alt="Screen Shot 2022-04-14 at 1 02 52 PM" src="https://user-images.githubusercontent.com/46389157/163438224-b11e6ac3-a314-4ebb-b02f-cc87abab2bed.png">

**Comment by zakiya** [comment]
Hi @alexhu00  I should have been referenced the parent in the description. I've been working on a component workshop space where components can be tested outside of the context of the design system websites. This is how the component looks on its own:

<img src=https://user-images.githubusercontent.com/915352/163018766-e18bfd62-fc16-4734-92b8-569f4cf79e0e.png>

I'll update the main description.

**Comment by zakiya** [comment]
Code merged into 1.0.6-bodie

**To QA** - there should be no visual regression only the site's statewide footer.
