### ISSUE TITLE
Styles: base-css explode

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#794]
The base-css component includes many several important pieces which need to be split out and have their own documentation and packages. This is helpful because pieces of it may not be desired by some design system users and when spkit out we can upgrade the individual parts easily. When we split out these separate pieces we can retire the base-css package itself. This process should include stripping the wordpress classname references from the CSS and sample HTML.

Pieces of this package which can be separated:

- normalize
- buttons
- typography
- layouts
- forms
- grid
- design tokens
- theme examples
- utility classes

The wordpress css rules currently in this component should be deleted.

**Comment by saldanaj27** [comment]
Should I just remove the file and create a pull request? Is there any other context involved?

**Comment by aaronhans** [comment]
We need to bump the major version of the component since we are making a potentially breaking change.

I have published a beta version of the component without the wordpress file (https://www.npmjs.com/package/@cagov/ds-base-css/v/2.0.0-beta.1) which I am using while developing a new version of the digital.ca.gov site. 

I was thinking this was a good opportunity to remove a lot of other pieces of base-css and split them out into separate components but it is probably better to do that separately.

@saldanaj27 if you want to do a PR that removes this file, bumps major version in package.json and explains the update in the changelog that would be great

**Comment by yesenia-gtz** [comment]
@kkoryaka  to review needs

**Comment by yesenia-gtz** [comment]
Recommended to bring together a team to own and deliver needs related to base CSS. This issue requires dedicated support from a Lead engineer to push forward.

**Comment by aaronhans** [comment]
The first step here can be straightforward:
Publish separate components for each of the following using the existing code in the base-css component:

[] normalize
[] buttons
[] typography
[] layouts
[] forms
[] grid
[] design tokens
[] theme examples
[] utility classes

Each of these will require their own readme. Some of these may be in really early states but breaking them up so we can iterate on them individually will make it easier to notice their maturity level and address issues specific to forms or our normalize approach separately.

[] update the design system site to inherit these components individually

Also removing the wordpress specific code which is causing problems for a few implementations will be a big upgrade.

There was some concern that breaking up this component makes it harder to inherit the functionality. That functionality is already provided by tools that package up collections of components like combined-css and will be provided by other tools like https://github.com/cagov/design-system/issues/718. Those can easily include all these separate packages if desired.
