### ISSUE TITLE
UX Review: 404 page content design

### ISSUE THREAD

**Issue by yesenia-gtz** [cagov/design-system#796]
There has been exportation on how to approach 404 page content design following recent implementation with the NextGen Open Data Portal project.

Early on we discussed this project as a partnership for process improvements and design system feedback.

As we continue to make design updates to the 404 exploration can we also think about how to knowledge share usability improvements and user pathways from a 404 page as design system feedback? This is a great opportunity to continue to identify items missing from the design system and share learnings.

https://github.com/CA-Data/Open-Data-Portal/issues/24

**Comment by yesenia-gtz** [comment]
@extinah @sharon-rabang added to DS board for team collaboration

**Comment by extinah** [comment]
@yesenia-gtz  thanks!
@sharon-rabang - I'll try to set up a meeting for tomorrow afternoon. worst case I can't be there for it!

**Comment by chachasikes** [comment]
@extinah What's the status of this

**Comment by chachasikes** [comment]
Can you confirm that "in review" is correct?
