### ISSUE TITLE
Component: Page Alert (informs DS)

### ISSUE THREAD

**Issue by kkoryaka** [cagov/design-system#8]
Create alert component that will have:
- Alert title
- Alert text block
- Link or dismiss button

Figma link:
https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/cannabis.ca.gov-screens?node-id=0%3A3

Layout:
<img width="1020" alt="Screen Shot 2021-05-10 at 4 14 57 PM" src="https://user-images.githubusercontent.com/31669748/117735764-f9e4a500-b1aa-11eb-8ce6-a885b308bb58.png">

Alert might require JavaScript code for dismiss button.

Where will this live?

design-system/components/alert/template.html
design-system/components/alert/index.css
design-system/components/alert/index.js

**Comment by kkoryaka** [comment]
Modified alert component, switched css styles to scss,  added JavaScript file (for dismiss button)

**Comment by wrendo** [comment]
For clarification: This is regarding the yellow box page alert and not the blue statewide alert banner.

![Screen Shot 2021-06-13 at 8 53 06 PM](https://user-images.githubusercontent.com/1387973/121836950-601c8600-cc89-11eb-8945-1ed42ae3b082.png)
