### ISSUE TITLE
Styles: Animation Documentation

### ISSUE THREAD

**Issue by Angsv** [cagov/design-system#819]

**Comment by Angsv** [comment]
@kmbrlygl @Courtney-Chittock @kkoryaka @sharon-rabang @aaronhans 
Take a look at the documentation (hopefully the upload works). I took in a lot of what people have been saying about the goals of the Design System and I combined those with the various best practices in UX and animation in general to create the high level Guiding Principles and then a more explanatory document that (hopefully) provides enough background information for someone to get a good understanding without getting overwhelmed by too much information. I aimed for keeping the documents as simple and too the point as I could, let me know if there's anything you think should be expanded upon. 

[Guiding Principles for Motion Design.docx](https://github.com/cagov/design-system/files/8809936/Guiding.Principles.for.Motion.Design.docx)
[Guidelines for UI Animations.docx](https://github.com/cagov/design-system/files/8809938/Guidelines.for.UI.Animations.docx)

**Comment by aaronhans** [comment]
Fantastic work @Angsv!

**Comment by Angsv** [comment]
Updated the Principles with Sharon's feedback. 

[Guiding Principles for Motion Design.docx](https://github.com/cagov/design-system/files/9236548/Guiding.Principles.for.Motion.Design.docx)

**Comment by ashleydraper** [comment]
@Angsv Is this document ready for a content pass?

**Comment by Angsv** [comment]
@ashleydraper yep it's ready and so is
[Guidelines for UI Animations.docx](https://github.com/cagov/design-system/files/9237242/Guidelines.for.UI.Animations.docx)
