### ISSUE TITLE
incorporate linting/prettier

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#82]
During pair programming with Timothy a few minor stylistic preferences came up. I don't have strong opinions about this and prefer to rely on a standardized code formatting regimen like semistandard/prettier

Implement these tools on existing packages so they conform to standards. Review choices again with team to make sure there are no problems with these choices. We've discussed these before but bring up again to verify

**Comment by chachasikes** [comment]
Update: We had a great team session on linting led by Aaron. We are using open-wc linting.

**Comment by chachasikes** [comment]
We sorted this out, closing.
