### ISSUE TITLE
State template component data and usage tracking

### ISSUE THREAD

**Issue by yesenia-gtz** [cagov/design-system#820]
How can we better understand what components are being used in the state template currently?

Would like to track the following if possible:

- Component Usage patterns
- Component searches

Is this a way to track this type of data?

**Comment by yesenia-gtz** [comment]
@ashleydraper please reach out to Linda Tracy from Koji's group who is familiar with analytics.

**Comment by ashleydraper** [comment]
Here is an [analytics report](https://github.com/cagov/design-system/files/8604756/template-webstandards-20210427-20220427.2.xlsx) from the template.webstandards.ca.gov site for the period of 4/27/21 - 4/24/22. 
Providing a Teams link to the same report in case it's useful: https://stateca-my.sharepoint.com/:x:/g/personal/linda_tracy_state_ca_gov/Ebggibl77WJLl68zxubZa5IBmhrxq44o9h5HtCyB_8FCVQ?e=BfM2XM

**Comment by ashleydraper** [comment]
@yesenia-gtz I think we might be crossing wires. Should this issue live on the [state template board](https://github.com/Office-of-Digital-Innovation/California-State-Web-Template/issues)?

**Comment by chachasikes** [comment]
Update:
* Have created some data for sites
* Need to sync on the analytics portion
