### ISSUE TITLE
Create sprint plan for content

### ISSUE THREAD

**Issue by ashleydraper** [cagov/design-system#834]
Create sprint plan with milestones and deadlines for content, dev and design

**Comment by ashleydraper** [comment]
This [sprint plan](https://coda.io/d/Web-Design-and-Development_d_Km5FVkYnQ/State-Template-Sprint-Planning_su2EF#_luRCz) should be used as our north star in getting us to the finish for content, design and dev. Please feel free to markup as you see fit. It is meant to be somewhat of a living doc.
Cc: @artuoma @Courtney-Chittock @yesenia-gtz @kkoryaka

**Comment by ashleydraper** [comment]
Anyone want to add to this?
@artuoma @Courtney-Chittock @yesenia-gtz @kkoryaka

**Comment by Courtney-Chittock** [comment]
Looks like we may need to update and rearrange some stuff based on our recent standup discussion and workloads?
