### ISSUE TITLE
Component: Tabs

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#837]
A new component has been requested: tabs so visitors can move between multiple content sections on a single page

We built one during the recent digital.ca.gov redesign so could use it as a prototype and run it through out user research process

**Comment by yesenia-gtz** [comment]
Review work in progress for State template beta.
- https://beta.template.webstandards.ca.gov/sample/tabs.html

Recent design explorations:
https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=511%3A4269

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/98193284/181838877-4b330e63-cf10-471f-ba9e-811220943154.png)




![Screen Shot 2022-07-29 at 1 28 31 PM](https://user-images.githubusercontent.com/98193284/181838507-94bbd113-f794-4d54-a15f-ad86fb162d6f.png)
