### ISSUE TITLE
translate link improvements

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#839]
The translate widget has a few options in the state template. The plain translate link which goes to a separate page is a good alternative which was introduced because of feedback the google language dropdown was ugly.

If we move to this version we can create a new page that it links to that shows the full translate options

Here is an example of the translate link option: from https://www.ca.gov/ which links to https://www.ca.gov/translate/
<img width="573" alt="Screen Shot 2021-08-11 at 9 06 17 AM" src="https://user-images.githubusercontent.com/353360/129064302-8ec1504e-9b57-4bdc-8850-680f2025720f.png">

We can also take this option to upgrade the translate component to support this use case as well as the possibility of some pages having human translated versions available which it can read from the url.
This last use case can be used on the rent relief website where they are currently getting negative feedback from the press because of some rude machine translations users are finding via the google translate widget even though human translated versions of the pages are available

**Comment by chachasikes** [comment]
Moved this over from cannabis site - was a suggestion & probably belongs in design system backlog.
