### ISSUE TITLE
Process: issue template cleanup

### ISSUE THREAD

**Issue by yesenia-gtz** [cagov/design-system#910]
I order to simplify external feature requests we will be moving to a non-git form in coda to ensure issues added to GitHub are relevant to product and project needs. 

Tasks:
- [ ] Keep the following templates: general, bug 
- [ ] Remove all other templates

**Comment by yesenia-gtz** [comment]
@zakiya are we able to clean up the templates sometime this month? I would like to move forward with directing  requests into [CA Design System Feature Requests](https://coda.io/d/CA-Design-System-Feature-Requests_dEK44SrnH6p/CA-Design-System-Feature-Requests_suP4M) . Who can help with this?

**Comment by zakiya** [comment]
Assigning to @xjensen. He is and will be the primary ODI Engineer on the project for the time being.
