### ISSUE TITLE
Legal microcopy to warn users not to  submit personally idendifable info (PII) in page-feedback forms

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#916]
This came up with reviewing page feedback with ODI legal counsel. 

Steps to complete are:

- [x] Content team writes copy
- [x] Legal team approves copy
- [ ] Design team updates Figma
- [ ] Engineering team implements
- [ ] QA
- [ ] Deploy to all sites using the component

Assigning to @yesenia-gtz for labeling. This is high priority.

**Comment by ashleydraper** [comment]
@zakiya Once we've identified the SME/ contributor, can we also identify where this copy will be housed? I have access to [this folder](https://drive.google.com/drive/folders/1d4TWRfIvAr5DPbQwhCzQFMHv-HOIhJBz), but want to be sure we're all using it.

**Comment by reganking** [comment]
Hi @ashleydraper & @yesenia-gtz, I'm the PF owner on the ODI / CalInnovate side, so I can help to clarify/align with @zakiya and @mediajunkie on slack #odi-website-analytics. I will take note of the Design System folder.

**Comment by chachasikes** [comment]
On the UI end - I synced already on this with @aaronhans  & the way we discussed for making this happen would be:

* add a data attribute on the wrapper of the custom element that can include the text for the finalized microcopy
* Connect that data in the UI of the component to display on the front end
* update the web component

Keeping the markup as an attribute will allow any legal team to update text to suit their needs.

**Comment by ashleydraper** [comment]
@chachasikes I'm glad you two were able to discuss this, but I'm lost in what you're describing! Can you explain that in a way that's less technical?

**Comment by zakiya** [comment]
@reganking Sorry it wasn't communicated that you were the  product owner for page feedback. We'll need to coordinate closely as page-feedback is also a design system component. 

@ashleydraper I have no preference about where copy should be housed. Liz is our only content designer at the moment. 

@chachasikes comment refers to the implementation plan for engineering.

**Comment by ashleydraper** [comment]
@zakiya How do folks feel about this statement. _Personally identifiable information_ can read a little jargony outside of the state, so I went with terms that resonate with more people.

![image](https://user-images.githubusercontent.com/62437425/182251675-dcbd65f9-897d-4795-9c64-3dadabf47803.png)

_Do not include any personal or confidential information like your address or phone number._

**Comment by zakiya** [comment]
@ashleydraper Looks good to me. Will run it by legal.

**Comment by zakiya** [comment]
@ashleydraper 

The language is ok with legal.

They also suggested we instruct people who use the widget to scrub any PII.

I think we can move forward with updating Figma but we should probably also add some copy to the readme.

**Comment by ashleydraper** [comment]
@zakiya 

That's great. 

Can you say more about what they mean by "scrub?" If we're telling folks not to include PII in the first place, what are they scrubbing? Also, just some quick analytics on that word choice (see screenshot).
![image](https://user-images.githubusercontent.com/62437425/182650745-0d913506-3b8a-41c9-accd-74bb9727e934.png)

I don't have the Figma board,  is the readme section be on there too?

**Comment by mediajunkie** [comment]
Poking my nose in here because I have some of the context from the past, I
think they’re suggesting that we recommend to users of the report that they
remove PII from comments when they see it, which I don’t believe is a
feature that we offer.

Also there are times when the PII is knowingly submitted in hopes of a
response.

Giving the reviewers discretion and making them aware of the risks involved
with PII was the plan of record as I recall.

-- 
Christian Crumlish (he/they)
Senior Product Manager | CA Office of Data & Innovation
916-272-5214 | ***@***.***

follow us: web <https://innovation.ca.gov/> | blog
<https://innovation.ca.gov/blog/> | twitter
<https://twitter.com/californiaodi>

**Comment by ashleydraper** [comment]
OH, now I see. Okay this is making sense!!

See notes in the screenshot.

![image](https://user-images.githubusercontent.com/62437425/182661610-fd000099-b7e3-4b2c-bdb6-16bf8900d05a.png)

**Comment by chachasikes** [comment]
Those are both great notes @ashleydraper. 
Correct, it's a service we provide right now, and an interested dept/agency would need to work with us.

A feature we would need to add is the ability to flag and remove PII data from the reports that the departments would get.

**Comment by ashleydraper** [comment]
@zakiya @mediajunkie Thoughts?

**Comment by ashleydraper** [comment]
To round out the initial ask, seems like this should be assigned to design to add to Figma. Is that Kimberly?

**Comment by zakiya** [comment]
@ashleydraper Let's put a pin in this until I can connect with @reganking and @mediajunkie  Product ownership on this has been unclear and we've had personnel changes and I want to make sure all parties are moving in the same direction. Will have an update for you by end of day.

**Comment by ashleydraper** [comment]
Works for me, ping me when ready.

**Comment by zakiya** [comment]
Just a quick update on this -- we realized we have some work to do internally about the direction of this product. We have a meeting to level set next week. I'm going to remove the Urgent tag and and move it to in Progress. 

I really appreciate the quick turn around @ashleydraper!

**Comment by ashleydraper** [comment]
Very welcome! Happy to jump back in when the time is right.

**Comment by zakiya** [comment]
@mediajunkie @ashleydraper 

We met about this product on Monday. Per that conversation, I think we should make the following changes to the Page Feedback readme:

![CleanShot 2022-08-18 at 08 42 44](https://user-images.githubusercontent.com/915352/185438449-0899f4bd-a52b-4812-925e-7ee42e06b4b4.png)

I can make the update myself if approved. 

I think we can work the addition of microcopy into the website we're working on in another repo.

**Comment by ashleydraper** [comment]
@zakiya I support these edits. Should this issue remain open until we're able to address the microcopy?

**Comment by zakiya** [comment]
I made the edits. Yes let's keep this open until we address microcopy. Going to assign to myself for now. Thanks for your help!
