### ISSUE TITLE
DX: all components should have a dist folder which holds file to be imported by consuming site (both css and js)

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#923]
Request originated from Danny when integrating many design system components into new projects he discovered that the following components don't have any dist directory:

- ds-link-icon
- ds-site-footer
- ds-site-header
- ds-skip-to-content
- ds-statewide-footer
- ds-statewide-header

We intentionally set things up this way, only using dist for js build output and this is documented. The request to have the files a site needs to import all available in a dist directory for any component is valid though and may simplify component integration. We should consider outputting css files generated from scss into dist.

Action items:
Discuss requested change with design system team. If we have consensus we can modify the components to output to dist and update the directory docs to reflect that decision:

https://github.com/cagov/design-system/tree/main/components:
```
If a component includes javascript and uses a build step all built files will be written to a distribution folder:
```

Notes:
- If a component uses js it should already have a dist folder
- ds-link-icon is a special case: has js but is missing a dist folder, could be modified to have one and use more encapsulation
- The code change required to use dist folders for html/css only components is minor but would require updates from any end user because they have to change their import paths so we should bump major versions of all components where we make this update

**Comment by xjensen** [comment]
I'm going to give this a try in PR #919. I think we have enough consensus in #324 to proceed. Let me know if I should hold.

**Comment by xjensen** [comment]
This is mostly ready in #919.

**Comment by xjensen** [comment]
This is now merged into the [release branch](https://github.com/cagov/design-system/tree/release/1.0.10-fremont-peak) and published to NPM.
