### ISSUE TITLE
Bug: v2.2.0 of @cagov/ds-page-navigation confuses JAWS

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#931]
There is a bug that surfaces only in the JAWS screen reader on Windows with the latest version(2.2.0) of the page-navigation component. When you follow the anchor links in the sidebar JAWS seems to get lost and has to announce where you are in the document from the top including page title and how many regions there are. This is annoying. This issue is not present in any other screen reader tested: VoiceOver on mac, TalkBack on Android and NVDA on Windows all work perfectly with the latest version of page-navigation.

Other sites like innovation.ca.gov didn't exhibit the issue because they were still running an earlier version of page-navigation(2.1.0). 

The latest version of the code in v2.2.0 looks great and I don't know what the underlying cause of the issue is but we were able to only reproduce this issue on v2.2.0 on JAWS on Windows and when we downgraded it went away. It is also interesting that this is only a problem in JAWS but is fine on all other screen readers.

**Comment by xjensen** [comment]
One important observation: the new version of page-navigation does work (in JAWS) on the Design System site. But none of our other sites.

It looks like JAWS wants `tabindex="-1"` on the headings. On the Design System site, we add this `tabindex=-1` to the headings through our custom Markdown processor.

I will attempt to add `tabindex` dynamically via the component's JS. Let's see if that helps.

**Comment by aaronhans** [comment]
Great discovery, thanks @xjensen!

**Comment by chachasikes** [comment]
Thanks for tracking this down @xjensen.
