### ISSUE TITLE
Plan to move this repo to ODS ownership

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#932]
https://github.com/Office-of-Digital-Services

Notes:

- We should do a test run to make sure github actions and other automated script stay intact
- We'll need to update all links to cagov/design-system in this repo and in others
- Investigate whether we can hold onto or post a message at https://github.com/cagov/design-system/ notifying others of relocation
- Would it be too confusing to just do a fork?
- Does ODS also need to own the npm repo?
- Validate the 14 owners of the ODS repo
- Do a test run before we commit to this plan

**Comment by yesenia-gtz** [comment]
@zakiya I will add, If this proves to be an issue there is no requirement to move it as long as access to edit and triage remains. The board is also built out here, so that will also need to be rebuilt if its moved.

**Comment by yesenia-gtz** [comment]
Staying with ODI for now, closing out.
