### ISSUE TITLE
Upgrade Contact Form API Key for Airtable

### ISSUE THREAD

**Issue by chachasikes** [cagov/design-system#963]
Airtable will be switching to personal access tokens.
https://support.airtable.com/docs/airtable-api-key-deprecation-notice

Reminder: The UI form targets a microservice/function app. 
- The API Key that can write to the Airtable base is stored with the function app so that it’s more secure. 
- The function app uses Airtable’s API to write new records, which populates the table when there is a new request. 
- This could be a good opportunity to move from Azure to Lambda if we didn’t already & switch the API key to the new method with personal access tokens.

We invested time in this pattern in order to create a light & simple way to do basic database set up for business/product-focused teams to be able to set up data collection tools more easily and make use of the information sharing features of Airtable. This similar approach could be used to integrate with other business systems. This is intended to help avoid the extra burden of passing around excel spreadsheets and extra work to load simple data into tools that are used for day-to-day business operations. The pattern is meant to be agnostic to the technology. The kind of technologies are "collaborative spreadsheets" - so this pattern could work with Airtable, Coda, related Microsoft products, etc.

Current component function & Docs
- https://github.com/cagov/services-design-system-cagov-airtable-form

**Comment by aaronhans** [comment]
New form backend here https://github.com/cagov/design-system/pull/964

Before creating that new endpoint on AWS I reviewed the airtable no-code form creation tools. It was cool to see that they publish a relatively lightweight form. The engineering team probably still wants to do our own frontends so we can make them super lean and cleanly styled but the no-code versions not being as huge as feared was encouraging. I'd recommend that for business users in many cases.
