### ISSUE TITLE
Bug: Google Translate conflicts with main navigation links

### ISSUE THREAD

**Issue by Greg-Watanabe** [cagov/design-system#985]
Issue occurs on these sites:

https://broadbandforall.cdt.ca.gov/
https://www.govops.ca.gov/
https://climateaction.ca.gov/

I also downloaded the design system template and replicated the issue locally.

Click the "translate" link at the top right. Select any language. Click any main navigation link text. Nothing happens.

Google translate inserts font tags around the text, which might be interfering with a click handler.

Note that if you click outside the text but within the \<a> tag, it works. e.g Clicking the red area doesn't work but the green area does work:
![image](https://github.com/cagov/design-system/assets/24966826/32042b85-04fc-456f-af1d-57a14a6b7589)

**Comment by zakiya** [comment]
Hi Greg. 

Thank you for your contribution and your  easy-to-follow bug report. Your update is available now via the [npm package](https://www.npmjs.com/package/@cagov/ds-site-navigation). Will have a full new Design system release next week. 

Let us know if this fix works for you in the other environments.

**Comment by zakiya** [comment]
No comments or action for over a month, Assuming the fix was good and closing.
